### ISSUE TITLE
Super Quick Info Could Broke the GoTo.All Box

### ISSUE THREAD

**Issue by vinaychandra** [wmjordan/Codist#103]
This issue is similar to #86 

The GoTo.All window looses focus when Codist is enabled (this could kick in some time after the installation). The keyboard shortcut opens the search box but the keyboard focus does not exist on it and requires another click on the search box to start typing.

![image](https://user-images.githubusercontent.com/5670927/63563598-6bcc1500-c516-11e9-81e4-168aab02f35d.png)

**Comment by wmjordan** [comment]
I am sorry that I could not reproduce this issue.
Could you download the latest beta and see whether the problem persists?

**Comment by vinaychandra** [comment]
@wmjordan, I still see this issue on the current beta. I cannot provide a way to reproduce it but it still happens to me. My steps for repro are like reinstall/repair vs 2019, install codist, setup a shortcut for GoTo.All. Use the code for sometime. After sometime, the GoTo.All shortcut invocation will not have keyboard focus immediately.

**Comment by wmjordan** [comment]
I tried quite a few times, on both VS2017 and 2019, with single or multiple documents opened, with or without pinned symbol lists opened, with or without GoTo box already opened, nothing wrong happened.

1. What other extensions have you installed?
1. If the keyboard focus was not on the GoTo box like expected, where was it?

**Comment by vinaychandra** [comment]
1. There are no other extensions that are installed. Only Codist for my testing.
1. There was no keyboard focus. I was unable to tell what it is actually focusing on.

**Comment by wmjordan** [comment]
Would the keyboard respond to up/down cursor keys when the "focus" was lost?

**Comment by wmjordan** [comment]
If the drop-down menu of Codist Navigation Bar, or a Symbol List was displayed, the keyboard focus would be switched to them when you activate the document via the GoTo box.

**Comment by vinaychandra** [comment]
- The keyboard does not respond to up/down cursor keys when the focus is lost
- The only features enabled are Syntax Highlight and Super Quick Info. I disabled all other features. I even enabled a different theme for Syntax if that matters.

![image](https://user-images.githubusercontent.com/5670927/63630499-3257e000-c5d0-11e9-92e1-6850ae6c2ed7.png)

**Comment by vinaychandra** [comment]
On my machine, i can trigger it like this.
- Open an existing project (GoTo.All shortcut works as expected)
- Open different files (GoTo.All still works)
- Start typing something and backspace. Click Save. Press F12 to Goto definition. (GoTo.All no longer will have automatic focus)

**Comment by wmjordan** [comment]
Thanks for providing the info.

If I disabled the Navigation Bar, I could reproduce the weirdness you encountered. The keyboard focus was lost after pressing Ctrl+T.

**Comment by wmjordan** [comment]
However, it could not be definitely reproduced yet. :(

**Comment by wmjordan** [comment]
This problem seemed to be quite tricky.

Had you once enabled the Navigation Bar feature when the keyboard focus was lost before you disabled that feature?

**Comment by vinaychandra** [comment]
I think by default Codist enables it. If that is the case, I have disabled it manually because it was slowing my experience. But after the initial stuff, this issue persists between restarts. I haven't touched any other settings of Codist in these restarts

**Comment by wmjordan** [comment]
It seems that this issue has something to the WPF GUI hack.
You can safely turn on the Syntax Highlight, and the Scrollbar Marker.
For Super Quick Info and Smart Bar, as long as you don't bring out the symbol list, the GoTo box may not get broken either.

**Comment by wmjordan** [comment]
I tracked down the issue to the symbol list.
This issue could be 100% reproduced by opening the symbol list first (from symbol analysis commands) then execute the GoTo command.

**Comment by wmjordan** [comment]
I think that I have fixed your problem after hours' work.

Please download the new file in the release section.
https://github.com/wmjordan/Codist/releases/tag/v5.3

**Comment by vinaychandra** [comment]
Looks like that fixed the issue. Will reopen/update if I stumble onto it again. Thank you so much!

**Comment by wmjordan** [comment]
You are welcome.
Thanks for the quick feedback.
