### ISSUE TITLE
Suggestion: Preview String Constant concatenation in QuickInfo tooltips

### ISSUE THREAD

**Issue by fitdev** [wmjordan/Codist#105]
Consider the following code:

```
class Foo {
  const string A = "A1";
  const string B = "B1";
  const string AwithB = A + B;
}
```

Currently, whenever user hovers over `AwithB`, QuickInfo displays: `Foo.AwithB = A + B`, which is useful. However, it would be nice to asee the actual "calculated" (concatenated) value as well: `Foo.AwithB = "A1B1"`. Perhaps it can be shown in parenthesis, or on a new line?

**Comment by wmjordan** [comment]
Good suggestion.
I also have this in mind actually--not only for string concatenation, but also arithmetic calculations from numeric constants as well.
There must be a way to do so.

**Comment by wmjordan** [comment]
Please test with the new beta.
You need to enable the "string length, hash, content" option to show the string info.

**Comment by wmjordan** [comment]
Another improvement is that the evaluation info not only applies to constant variables or fields, but to other places where the evaluation can be performed. For instance,

````C#
Console.WriteLine(1 << 28); // hover on "<<"
var a = "t" + nameof(Console); // hover on "+"
````

**Comment by fitdev** [comment]
Excellent! Works great and is very useful! Thanks for acting so quickly on this, glad you had the same idea as well!

**Comment by wmjordan** [comment]
Great!
Feel free to post any feedback about Codist :)
