### ISSUE TITLE
Suggestion: Find Methods with Same Signature

### ISSUE THREAD

**Issue by fitdev** [wmjordan/Codist#106]
It would be nice if it was possible to search for a member (within a solution) that has the same signature as the highlighted method. This is especially useful for generic methods with several parameters. It is also useful when you are trying integrate a small library within your own, and the small library has various small utility methods, which you may not remember already exist in your bigger library.

**Comment by wmjordan** [comment]
> especially useful for generic methods with several parameters

Could you please give me an example demonstrating the usefulness of this function for generic methods?

> you may not remember already exist in your bigger library

I'd ran into this problem myself sometimes as well.

**Comment by fitdev** [comment]
In my case I had to "port" several `IDictionary<T>` extension methods from another library / project, and I could not easily remember if I had those already defined and where. Searching entire solution by signature in this example could have easily solved the problem.

**Comment by wmjordan** [comment]
Another usage may be finding methods as candidates to make `delegate`s.

The version 5.4 is about to be released.
I will work on this after the release.

**Comment by wmjordan** [comment]
Please test with the latest beta.

**Comment by fitdev** [comment]
Thanks for the new beta!

Concrete types seem to work quite well. But generics do not work at the moment:

```
  static class DictionaryExtensions {
    public static TValue Find<TKey, TValue>(this IDictionary<TKey, TValue> dictionary, TKey key) {
      if (dictionary == null) throw new ArgumentNullException(nameof(dictionary));
      return dictionary.TryGetValue(key, out var result) ? result : default(TValue);
    }
  }

  static class DictionaryExtensions2 {
    public static TValue GetOrDefault<TKey, TValue>(this IDictionary<TKey, TValue> dic, TKey key) => (!(dic is null) && dic.TryGetValue(key, out var val)) ? val : default;
  }

```

`Find` and `GetOrDefault` both have the same signatures, yet neither is being found.

Also, perhaps a few more things to consider to make it really useful:

 - Ability to ignore optional parameters (in the "candidate" methods, not the main method for which we are trying to find similar ones)
 - Generic constraints - probably these can be ignored for the moment, as I would imagine it not to be very useful to filter down the list too much
 - Nullability in C# 8 - again probably ignore this, i.e. treat `sting` and `string?` as the same for the purposes of this - seems more useful.
 - Inehritance - in the example above, if one of the methods had `Dictionary` instead of `IDictionary`, perhaps it should still find such cases.

**Comment by wmjordan** [comment]
For the generic type parameters, please try the new version.
The type constraints are ignored.
The other stuff is not implemented yet.

**Comment by fitdev** [comment]
Generic type parameters now work well. Thank you!
