### ISSUE TITLE
Suggestion: Indicate User-Code Items in Intellisense Dropdowns

### ISSUE THREAD

**Issue by fitdev** [wmjordan/Codist#107]
It would be real nice if items (members, types) that appear in the Intellisense dropdown that are defined in the user-code (i.e. within the solution) would be somehow indicated separately - either with an icon overlay, or a different style (bold for example). If possible, filtering ability would be great as well (now you can only filter my item kind - field, property, method, etc.).

**Comment by wmjordan** [comment]
I had been thinking of hacking the completion list for quite a few months, to be specific, at the time when Codist was released publicly.

Unfortunately, the current API does not offer any capability to alter it, what we can do is completely overriding it, or adding new items to it (like what Intelli-Code does nowadays). No way to change icons, font styles, filters or other things in the list.

**Comment by fitdev** [comment]
I see. That's a significant limitation. I guess we'll need to wait until VS team makes it more extensible.

**Comment by wmjordan** [comment]
This feature request has something to do with #13. Both of them require hacking into the completion list.

**Comment by fitdev** [comment]
Closing this issue, since I basically reopened a new and a more detailed one #139 (having forgotten about this one, sorry).
