### ISSUE TITLE
VS 2019 falls when you click F12 on the handler's name in the XAML element.

### ISSUE THREAD

**Issue by DkmS1953** [wmjordan/Codist#111]
There are no falls when Codist is disabled.
Event message in the system log:

> Приложение: devenv.exe
Версия платформы: v4.0.30319
Описание. Процесс был завершен из-за необработанного исключения.
Сведения об исключении: System.InvalidOperationException
   в System.Windows.Threading.Dispatcher.VerifyAccess()
   в MS.Internal.Media.VisualTreeUtils.AsVisual(System.Windows.DependencyObject, System.Windows.Media.Visual ByRef, System.Windows.Media.Media3D.Visual3D ByRef)
   в MS.Internal.Media.VisualTreeUtils.AsNonNullVisual(System.Windows.DependencyObject, System.Windows.Media.Visual ByRef, System.Windows.Media.Media3D.Visual3D ByRef)
   в System.Windows.Media.VisualTreeHelper.GetParent(System.Windows.DependencyObject)
   в System.Windows.UIElement.GetUIParentWithinLayoutIsland()
   в System.Windows.ContextLayoutManager+LayoutQueue.Add(System.Windows.UIElement)
   в System.Windows.UIElement.InvalidateArrange()
   в **_Codist_**.Margins.CSharpMembersMargin+MemberMarker+<OnTagsChanged>d__9.MoveNext()
   в System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1(System.Object)
   в System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   в System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   в System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   в System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   в System.Threading.ThreadPoolWorkQueue.Dispatch()
   в System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by wmjordan** [comment]
Thank you for the bug report.
I'd reproduced the issue and made a new version to fix it.
Please download the new beta version at https://github.com/wmjordan/Codist/issues/108.

**Comment by DkmS1953** [comment]
With version 5029 Studio no longer crashes. Cheers! 🤸‍♂️🙋‍♂️

**Comment by wmjordan** [comment]
Good to hear that. :)
