### ISSUE TITLE
Incorrect syntax highlight in call of method/

### ISSUE THREAD

**Issue by DkmS1953** [wmjordan/Codist#112]
Methods calls use the names of parameters. At the same time, not only the names, but also the parameters themselves are painted in the colors of the parameters names.
![image](https://user-images.githubusercontent.com/25905429/69494104-a3a57880-0ec8-11ea-9f07-f92de6f68f93.png)

**Comment by wmjordan** [comment]
It is by design.
The declaration of parameters, the names and their occurrences are sharing the same style, indicating that they are parameters, not variables or other things.
