### ISSUE TITLE
C# Comment Tagger Not Working in .cshtml or Other Razor Documents

### ISSUE THREAD

**Issue by wmjordan** [wmjordan/Codist#116]
This issue was originally posted under #108 by @fitdev.

**Comment by wmjordan** [comment]
@fitdev Please download the new beta and execute the _Show Document Content Type_ command from the File menu when a Razor document is opened, then post a screen shot here so I can get the document content type, which the syntax highlight engine should know about.

**Comment by fitdev** [comment]
![2019-12-17 21_02_16-Codist](https://user-images.githubusercontent.com/8166847/71022113-c8c88800-2110-11ea-988f-7e8967756cd2.jpg)

**Comment by fitdev** [comment]
Strangely, most of the Codist styles do work correctly in _cshtml_ files. Only custom comments seem to be problematic.

**Comment by wmjordan** [comment]
Thank you.
Please test the new beta.

**Comment by fitdev** [comment]
Thanks for the new beta. But I have not noticed any changes. What was supposed to be different? Various `TODO`-type comments are not formatted in `cshtml` files. Other Codist styles however seem to work just fine (so it's really just the comment formatting, but that's a minor thing).

**Comment by wmjordan** [comment]
It seems that more things have to be done...

**Comment by fitdev** [comment]
Just an idea... Perhaps you can generalize `TODO`-type comments to all languages, not just C#. Basically, if the region of code in an editor is classified by VS as "comment", then look for comment tags like `TODO` at the start of every line or something like that, and then apply the style.

**Comment by wmjordan** [comment]
Unfortunately it is not mandatory that comments must be classified as "comment".
Nevertheless, I had installed the ASP.NET Core workload and verified that your case should be able to be "generalized", once I find out why the comment tagger did not work as expected.

**Comment by wmjordan** [comment]
Please test with the new beta.

**Comment by fitdev** [comment]
Works really well now! Thank you!

**Comment by wmjordan** [comment]
@fitdev Have you ever met with any problem regarding syntax highlighting when working with Razor documents?

**Comment by fitdev** [comment]
I will let you know soon next week, as I took a small break recently from working with razor, but will continue next week, so will let you know then. I have not yet installed recent version of Codist from this week though - still on 5453. Should I update to the latest "buggy" version before trying it again with Razor?

**Comment by wmjordan** [comment]
I am sorry to tell you that the beta installed on your VS may be even BUGGIER than the latest one :P

Don't modify any setting with the version on your computer.
Please backup the config file before trying it. The config file should be located at `%appdata%\Codist`.

**Comment by fitdev** [comment]
Thanks for letting me know. I did not modify any of the styles yet - just took a look at how you implemented the new Syntax Highlight dialog which I liked. I will then backup the config and install the latest version and let you know. Thank you for all your work!
