### ISSUE TITLE
Hovering on await Keyword Could Cause Error

### ISSUE THREAD

**Issue by DkmS1953** [wmjordan/Codist#117]

**Comment by DkmS1953** [comment]
From activityLog.xml:

> 

System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.   at Microsoft.CodeAnalysis.CSharp.CSharpExtensions.Kind(SyntaxNode node)   at Codist.QuickInfo.CSharpQuickInfo.ShowParameterInfo(QiContainer qiContent, SyntaxNode node) in E:\Codes\Open Source Projects\Codist\Codist\QuickInfo\CSharpQuickInfo.cs:line 1071   at Codist.QuickInfo.CSharpQuickInfo.<GetQuickInfoItemAsync>d__7.MoveNext() in E:\Codes\Open Source Projects\Codist\Codist\QuickInfo\CSharpQuickInfo.cs:line 157 --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoSession.<ComputeSourceContentAsync>d__39.MoveNext() --- End of stack trace from previous location where exception was thrown ---   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)   --- End of inner exception stack trace ---   at Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoSession.<UpdateAsync>d__32.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoPresentationSession.<UpdateAsync>d__5.MoveNext() ---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.   at Microsoft.CodeAnalysis.CSharp.CSharpExtensions.Kind(SyntaxNode node)   at Codist.QuickInfo.CSharpQuickInfo.ShowParameterInfo(QiContainer qiContent, SyntaxNode node) in E:\Codes\Open Source Projects\Codist\Codist\QuickInfo\CSharpQuickInfo.cs:line 1071   at Codist.QuickInfo.CSharpQuickInfo.<GetQuickInfoItemAsync>d__7.MoveNext() in E:\Codes\Open Source Projects\Codist\Codist\QuickInfo\CSharpQuickInfo.cs:line 157 --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoSession.<ComputeSourceContentAsync>d__39.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)<---
--

**Comment by wmjordan** [comment]
Please try the new beta.

**Comment by DkmS1953** [comment]
I've already set it up.

This issue doesn't happen very often, I've had it twice. Both times - when
editing methods with nullable types in parameters or in results.

Wbr, Dyakov K.M.



ср, 4 дек. 2019 г. в 13:28, wmjordan <notifications@github.com>:

**Comment by DkmS1953** [comment]
Same error with last beta:

> 

System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.   at Microsoft.CodeAnalysis.CSharp.CSharpExtensions.Kind(SyntaxNode node)   at Codist.QuickInfo.CSharpQuickInfo.ShowParameterInfo(QiContainer qiContent, SyntaxNode node) in E:\Codes\Open Source Projects\Codist\Codist\QuickInfo\CSharpQuickInfo.cs:line 1070   at Codist.QuickInfo.CSharpQuickInfo.<GetQuickInfoItemAsync>d__7.MoveNext() in E:\Codes\Open Source Projects\Codist\Codist\QuickInfo\CSharpQuickInfo.cs:line 157
--

**Comment by wmjordan** [comment]
Thank you for the bug report.
I have reproduced this issue and I will post a new beta version to solve this later.

**Comment by wmjordan** [comment]
Please try the new beta.
