### ISSUE TITLE
SuperQuickInfo is not always shown

### ISSUE THREAD

**Issue by fitdev** [wmjordan/Codist#119]
Using latest version of Codist and VS 2019 16.5 Preview 1.

Sometimes, whenever I hover over type names in the editor, Codist's detailed tooltip is not displayed, and instead VS standard tooltip is shown with much less information. Sometimes, after repeatedly moving mouse in and out of the type name will trigger Codist's tooltip. Sometimes you need to close the document and open it again.

Actually this happened from time to time even with previous versions of both Codist and VS. There are no error messages displayed.

**Comment by wmjordan** [comment]
I encountered this previous as well. However, it occurred only when the solution was loading and Roslyn was too busy analyzing the code files to obtain enough information for the Quick Info; or it occurred when the mouse cursor was on an operator or somewhere else that VS used a different approach to locate the syntax symbol than Codist.

**Comment by fitdev** [comment]
In my case it happens from time to time even long after solution was fully loaded, and typically on type names (it's common for me to see inheritance hierarchy or Interface members). It can also happen multiple times even on the same document without closing it. So it would work, then some time later would not work, then a few minutes later (or after clicking and switching) it starts working again.

**Comment by wmjordan** [comment]
Would it occurred after that you made some editing, typically renamed a symbol, etc., in a large solution?
If you can observe the situation when this occurs, it may help me to reproduce and eliminate this issue.

**Comment by fitdev** [comment]
I don;t think it has anything to do with renaming a symbol. That is, the Type over which I moved my mouse was _not_ renamed recently. However I do rename things quite often in a large solution, so perhaps that's what causing it. But the issue is _not_ with the symbol I just renamed but some completely different symbol.

I will try to take a not more carefully when it happens.
