### ISSUE TITLE
A Better Way to Configure Syntax Highlight

### ISSUE THREAD

**Issue by wmjordan** [wmjordan/Codist#120]
Hi, Codist users, and @ghost, @fitdev, @laicasaane since you have posted issues about the syntax highlight feature before, I'd love to hear your suggestions.

I am planning rewriting the configuration module recently in order to fix #42, which has impeded my work for quite a few times. Maybe it has occurred to you previously as well.

The rewriting procedure of the options pages were almost done, except the syntax highlight one, which could be quite time-consuming for its complexity.
Anyway, since it is to be rewritten, do you have a better idea to implement the syntax highlight configuration module?

**Comment by fitdev** [comment]
As for me, the current implementation seems to be quite well structured and logical. I like the current UI.

**Comment by wmjordan** [comment]
I have an idea, which had been there since the first day when the Comment Tagger function was developed, that _Codist_ could potentially let you customize the style of **EVERY** syntax highlight classifications, even if _Codist_ was unaware of when and where the classification would be used, for instance, highlighting F# language syntax classifications.

The current UI was good for those classifications which were known when _Codist_ was programmed. However, for unknown ones, it was not possible for me to program it into the options page.

**Comment by fitdev** [comment]
That's a great idea! I could use some more customization for html / razor / css files!

**Comment by laicasaane** [comment]
Truthfully, the current implementation is quite slow on my machine, compare to VS native functionality. I don't know if you could make any improve on this matter, other custom highlighting extensions too have this issue. The only Codist features I'm using frequently are Super Quick Info and Navigation Bar, rarely Smart Bar.

**Comment by laicasaane** [comment]
I see you have a beta for 5.6. Is it ready for testing the new syntax highlighting? I will give it a try on a large project.

**Comment by wmjordan** [comment]
@laicasaane 
> Truthfully, the current implementation is quite slow on my machine, compare to VS native functionality.

Did you mean the syntax highlight function?
How big are your projects?
I opened a project with 3000+ code files, some of which had more than 4000 lines, on my laptop, which was purchased more than 5 years old, but I did not feel obvious slowdown. Of course, the CPU was busy when I edited the code files, since Roslyn was parsing the project in the background.

The new syntax highlight **configuration** module was not ready yet. There are checkboxes under the download links. Checked items were implemented. Unchecked were not yet, but planned.

**Comment by fitdev** [comment]
In my experience with some large solutions, the syntax highlighting is not slow. It does not appear right away - you have to wait a few seconds after the project is loaded, but that's normal. There is also a small 1-2 sec delay when opening a file, which again is normal.

I did experience very serious slow downs under specific circumstances (some code blocks it does not seem to like in otherwise small files), but it was rare, and I am not sure if Codist was the problem, or was just Roslyn.

What is a bit slow is the Syntax Highlighting Options page, but since I very rarely change the highlights, that's not an issue for me.

**Comment by wmjordan** [comment]
I have gotten an idea to improve the configuration module of Syntax Highlight, which operates like the following way.

1. User opens a document.
2. User clicks a word or a punctuation which is to be configure.
3. User executes a new command, such as "Customize Syntax Highlight..." from the Tools menu.
4. A dialog will popup, listing only the classification covering the word or punctuation that the caret is located. Since the configuration items listed are filtered to applicable ones to the active token, the user no longer needs to figure out what syntax classifications he wants to configure are located in the options page like nowadays.
5. User makes adjustments to those classifications the same way as he is doing in the Syntax Highlight options page. As he is making changes in the dialog, results are immediately applied to the document window.
6. User clicks the OK button to confirm his changes, or the Cancel button to revert to previous settings before the dialog popped up.

With this new configuration module, a user can change the syntax highlight settings much easier. Every changes are done immediately. The full preview is straightforward. And it may even work a little bit faster than ever.

**Comment by wmjordan** [comment]
> I did experience very serious slow downs under specific circumstances (some code blocks it does not seem to like in otherwise small files)

The slow downs I experienced were usually in a bit complicated projects. I guess it was related to Roslyn, since the compiler warnings and errors were also slow to reflect the changes in the editor, when the syntax highlight was slow.

**Comment by fitdev** [comment]
I really like your idea! It's great! Though, to be fair, there should also be an overview of all configured and available highlights as well (something similar or the same to what is currently in the options).

**Comment by wmjordan** [comment]
> there should also be an overview of all configured and available highlights

The problem is that unfortunately I could not predict the whole set of highlights available in the users VS and categorize them. The second problem is that the necessity of the overview list.

The APIs of VS extensions provide a way to listing all available highlights. The list can be very long, on my machine--about 300 items, but there is no way to categorize items, or even worse, some items were never used or not functioning after they were configured.
The "All language", "C#", etc. stuff nowadays you see in the options page of Codist/Syntax Highlight are done manually.

My teammates which were new to Codist felt difficult to find out what to configure and got **overwhelmed** by those lists, even when I, the author of this extension, was standing beside of them. Maybe it was because they were not English speakers and Codist was in English only at this moment, but I think the current implementation have not help them enough.

If a user does not feel good about his customization, he will want to revert the changes.
His feeling should come from the visual appearance of some items in the document window.
Thus, he will repeat the configuration procedure once again, click and configure (or revert). He may not be willing to go back to search within the long lists.

Anyway, I will try to make an implementation of the new module and let's test the user experience without the "all highlights" lists.

**Comment by wmjordan** [comment]
@fitdev 
I've uploaded a new beta which provides a new way to configure the syntax highlights.
I felt that you were right about an _overview of all configured and available highlights_ during my tests. Please try the beta and share your opinions.

**Comment by fitdev** [comment]
Thank you for the new beta! I see that there is now a "Mark symbol" command on the Quick Bar, allowing me to highlight a specific symbol with one of 9 available highlights, but that's all I noticed.

Glad that the overview of all highlights is still available in the Options. While it is certainly highly valuable to be able to adjust a highlight simply by "selecting" the desired item / symbol in the editor, I strongly feel that an overview is also very useful. Those that feel overwhelmed by it are welcome to use the new "pick and choose" approach.

I also think that the way you implemented overall syntax highlight categories in the options is very good. They are well organized and structured, and All Languages vs C# make it even more powerful. At least for me, it makes perfect sense. So perhaps you are right that your colleagues might have had trouble figuring these highlights out due to language barrier (and NOT because of inherent complexity in the way you organized the highlights).

**Comment by wmjordan** [comment]
There's a new beta released today.
A lot of works have been put into the new syntax highlight configuration dialog, which provides a better preview to the syntax styles.

The _"customize the style of EVERY syntax highlight classifications_" feature has not been finished yet. Changes could be made to unknown syntax highlight styles by Codist at run-time, but not saved.

**Comment by fitdev** [comment]
I like the new dialog. Good work! I will provide more feedback as I use it (didn't have a need to change any styles lately).

Perhaps it can be opened from Codist's Options dialog as well?

Also, are you planning on actually persisting syntax highlights for unknown syntax highlight styles, or is that not possible (because they are not known by Codist)?

**Comment by wmjordan** [comment]
> Perhaps it can be opened from Codist's Options dialog as well?

Sure it can. Previously I placed a button to do so. I will add it back in the next release and let's see whether it helps.

> are you planning on actually persisting syntax highlights for unknown syntax highlight styles, or is that not possible (because they are not known by Codist)?

It is possible. I am planning to do so.
The difficulty is compatibility.
I have to refactor the part of syntax highlight settings in the configuration persistence models. I am trying to make the new model compatible with the current one so we don't have to reconfigure our syntax settings after upgrading to the new version.

**Comment by fitdev** [comment]
> I am trying to make the new model compatible with the current one so we don't have to reconfigure our syntax settings after upgrading to the new version.

I see. Makes sense! It would be very inconvenient if users have to reconfigure all the various customizations they have made over time.

**Comment by wmjordan** [comment]
I've just uploaded a new version which enables customizing any syntax highlight settings persistently. Be sure to backup the config.json file before upgrading or you can't rollback to previous version without loosing your customization.

**Comment by fitdev** [comment]
Thank you! Will check it out soon!
