### ISSUE TITLE
OutofRange Vs2019 Crashing

### ISSUE THREAD

**Issue by evanricard** [wmjordan/Codist#121]
```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. Parameter name: length   at Microsoft.VisualStudio.Text.Span..ctor(Int32 start, Int32 length)   at Codist.Taggers.TaggedContentSpan.get_Span() in E:\Codes\Open Source Projects\Codist\Codist\Taggers\TaggerResult.cs:line 102   at Codist.Taggers.TaggerResult.Add(TaggedContentSpan tag) in E:\Codes\Open Source Projects\Codist\Codist\Taggers\TaggerResult.cs:line 47   at Codist.Taggers.CommentTagger.<GetTags>d__18.MoveNext() in E:\Codes\Open Source Projects\Codist\Codist\Taggers\CommentTagger.cs:line 110   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.<GetTagsForBuffer>d__47.MoveNext()
```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. Parameter name: length   at Microsoft.VisualStudio.Text.Span..ctor(Int32 start, Int32 length)   at Codist.Taggers.TaggedContentSpan.get_Span() in E:\Codes\Open Source Projects\Codist\Codist\Taggers\TaggerResult.cs:line 102   at Codist.Taggers.TaggerResult.Add(TaggedContentSpan tag) in E:\Codes\Open Source Projects\Codist\Codist\Taggers\TaggerResult.cs:line 47   at Codist.Taggers.CommentTagger.<GetTags>d__18.MoveNext() in E:\Codes\Open Source Projects\Codist\Codist\Taggers\CommentTagger.cs:line 110   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.<GetTagsForBuffer>d__47.MoveNext()

Hey @wmjordan I think I might have made an issue before regarding some strange behavior and but I can't find any prior issue in your repo here that I would have opened or closed.

Getting a lot of these errors in the Event Log whenever I boot up Visual Studio and when my files get particular big Visual Studio just crashes because I'm probably working with too little memory. Posted above is the same error but in two different In any event, let me know if this helps or if you need more info. Thanks!

**Comment by wmjordan** [comment]
I am sorry for this bug.

It is caused by the comment tagger.
Please disable it by unchecking the check box labeled "Enable comment tagger" in the options page of Codist/Syntax Highlight/Comment.
This should prevent it from crashing your VS.

I will look into it and get it fixed.

**Comment by evanricard** [comment]
Ok thanks @wmjordan ! Not a problem at all just wanted to bring it to your attention! Cheers

**Comment by wmjordan** [comment]
Hi, do you have a code file which could definitely trigger this bug?

**Comment by wmjordan** [comment]
I just checked the source code and located the place where your problem was.
I have a working-in-progress version, which may have fixed your problem. Would you like to test it?

**Comment by evanricard** [comment]
Sure @wmjordan I'll give it a spin

**Comment by wmjordan** [comment]
Good.
Please try the newly uploaded beta.

**Comment by wmjordan** [comment]
Hi, do you have time test the newly uploaded beta, which should have fixed your problem?

**Comment by evanricard** [comment]
hey @wmjordan unfortunately my laptop is out of commission & I'm not working in the same environment at the moment....hoping to get the device back running again soon I need to flash the BIOS

**Comment by wmjordan** [comment]
Thank you for replying. Hope that everything on your side is OK.
