### ISSUE TITLE
Feature Request: Show Namespace in Super Quick Info Tooltips

### ISSUE THREAD

**Issue by fitdev** [wmjordan/Codist#123]
It would be nice if in addition to Assembly, Namespace could also be shown for members inside the Super Quick Info. For example in `new TypeName(...)` when I hover over `TypeName`.

**Comment by wmjordan** [comment]
Hover your mouse on the Quick Info items, the tool tip has the namespace of the member.

**Comment by fitdev** [comment]
Thank you for a quick response. You are right, but it's quite hard to notice and difficult to see in the secondary tooltip...

In the screenshot below, the secondary tooltip only shows information about hovered over `key` (and in fact does not provide any extra useful info).
![2020-05-21 14_54_41-DotNet - Microsoft Visual Studio Preview](https://user-images.githubusercontent.com/8166847/82556849-37ec5180-9b73-11ea-9d71-16afe0110c18.jpg)

Now, if the mouse was moved literally a few pixels down, this is what would be shown:
![2020-05-21 14_55_06-DotNet - Microsoft Visual Studio Preview](https://user-images.githubusercontent.com/8166847/82556964-7124c180-9b73-11ea-912b-244fe9ee849c.jpg)
I guess that's what you are referring to.

However I still think it would be more valuable to put this info directly on the primary tooltip. Perhaps next to or above / below Assembly. In fact, both the namespace and code file (in case of user code) should be included.

Additionally, it would be great to improve those secondary tooltips (as seen in the first screenshot) by replacing them with basically similar tooltips to the primary one being displayed (i.e. replace those by Super Quick Infos too).

**Comment by wmjordan** [comment]
The "first screenshot" was dominated by VS 2019. If you revert back to VS 2017, you won't see such kind of thing, which is not my style 😎 .
I suggest you try the "Alternative Style", which I believe to have better usability, if you stick to VS 2019.

![shot](https://user-images.githubusercontent.com/12182730/82559146-aba55300-9ba1-11ea-9f3f-8cf09a499213.png)

**Comment by fitdev** [comment]
Thank you for the tip. Unfortunately there is no option for me to use anything other than the latest VS 2019 Preview. But I did turn on the Alternative style as you suggested and will see how it goes. Still, I think having namespace and file information directly available in the main tooltip is of great value!

**Comment by wmjordan** [comment]
Actually I've been using the alternative style for at least a year, since it was developed.
I did not feel missing anything. I noticed that I **never** care to take a look at the symbol type icon at all.

The reason may be the advanced syntax highlight of Codist--all type of symbols have been very clearly distinguished, thus I did not need to identify the kind of a symbol by the icon.

Getting rid of that icon even makes me somehow feel good--I couldn't tell why though, perhaps it is because I can immediately see the signature of the symbol.

**Comment by wmjordan** [comment]
> I think having namespace and file information directly available in the main tooltip is of great value!

Actually I have been considering removing that option. Partially because that the secondary tool tip has served that purpose. However, if you say so, I will keep it there.

**Comment by fitdev** [comment]
> The reason may be the advanced syntax highlight of Codist--all type of symbols have been very clearly distinguished, thus I did not need to identify the kind of a symbol by the icon.

That's a good point! However personally I do not customize Codist syntax highlight to that degree. In my case it is usually just static / constant vs instance and user code vs non-user code.

> Actually I have been considering removing that option. Partially because that the secondary tool tip has served that purpose. However, if you say so, I will keep it there.

Please do keep it! I use it all the time. And, like I suggested, if you can, maybe you can squeeze in the namespace and clickable file name in there as well. At least that could be one of the options (either show it as part of the main tooltip, or have it be displayed in the secondary tooltip).

**Comment by wmjordan** [comment]
Please try the new beta.

**Comment by fitdev** [comment]
Wow, that was fast! Very nice! The namespace inclusion is already quite helpful. It is even helpful for members defined in the currently active document in files like *.razor or *.cshtml where there is no enclosing `namespace { ... class { ...` to which you could scroll to check the namespace.

On a related note, perhaps you can add a tooltip to the NavBar's namespace so it shows full namespace "path":

![2020-05-22 18_10_45-DotNet - Microsoft Visual Studio Preview](https://user-images.githubusercontent.com/8166847/82682251-a99dcb80-9c57-11ea-94ef-e76d729a3953.jpg)

And maybe you can also add the clickable link to the source code file where the member is defined (for example below assembly and namespace).

**Comment by wmjordan** [comment]
> perhaps you can add a tooltip to the NavBar's namespace so it shows full namespace "path"

I still remember the request #67 . The tool tip will be of little use if that feature is implemented.


> add the clickable link to the source code file where the member is defined (for example below assembly and namespace)

Why not clicking the signature on top of the Quick Info instead of this link which serves the same purpose?

**Comment by fitdev** [comment]
You are right! I forgot about #67 . That would be even better, and I certainly miss that functionality. In part because I have a somewhat rare situation of namespaces like this:

- Root.Area1.SubAreaA
- Root.Area2.SubAreaA

And since the NaviBar will only show `SubAreaA` namespace, I may not immediately know whether it's the one in `Area1` parent namespace or `Area2` (which may be tricky to know just by looking at the opened file if `Area1` and `Area2` namespaces are similar in what they do).

> Why not clicking the signature on top of the Quick Info instead of this link which serves the same purpose?

You are right. I completely forgot about this. Though for me, it may still be useful to be able to see source file's path within the project at the bottom of the tooltip, and perhaps clicking on that would select it in Solution Explorer instead of opening the file. This is not really important like the namespace was, but still would be nice to have, perhaps as an option turned off by default.

**Comment by wmjordan** [comment]
> it may still be useful to be able to see source file's path within the project at the bottom of the tooltip

The paths will probably be long, which will make the tool tip take much more space than without them. If we convert them to relative to the project file, that will be better. I will consider this, but I can't warrant that will be implemented.

**Comment by fitdev** [comment]
You are right. I meant paths relative to project root (since Assembly item already shows what project a member belongs to).

**Comment by wmjordan** [comment]
I am closing this issue since the namespace display has been implemented in the latest version.
For the display of path, let's open a new issue and track it.
