### ISSUE TITLE
Codist 5.7 Beta Version + Chinese

### ISSUE THREAD

**Issue by wmjordan** [wmjordan/Codist#124]
Download:
[Codist 5889](https://github.com/wmjordan/Codist/files/4839575/Codist.zip)

[Codist 5840](https://github.com/wmjordan/Codist/files/4803428/Codist.zip)
[Codist 5798](https://github.com/wmjordan/Codist/files/4778472/Codist.zip)
[Codist 5793](https://github.com/wmjordan/Codist/files/4773772/Codist.zip)
[Codist 5778](https://github.com/wmjordan/Codist/files/4757556/Codist.zip)
[Codist 5691](https://github.com/wmjordan/Codist/files/4715410/Codist.zip)
[Codist 5664](https://github.com/wmjordan/Codist/files/4686350/Codist.zip)

- [x] General Interface
   - [x] Supported localization to other languages
   - [x] **支持中文了！Chinese interface** (b5691, b5778)
       ![shot](https://user-images.githubusercontent.com/12182730/85916130-3869bd80-b880-11ea-86d0-a6230c9e4222.PNG)
   - [x] Added an option to use compact menu like VS 2019 for VS 2017 (b5889)
       ![shot](https://user-images.githubusercontent.com/12182730/85916179-bcbc4080-b880-11ea-996e-1e64984dca92.PNG)
- [x] Syntax Highlight
   - [x] Fixed #72 improper highlight precedence of identifier (b5664)
   - [x] Improved the working experience when customizing syntax styles, making the Selected Code section reflecting syntax settings in real time to user actions in editor (b5798)
   - [x] Corrected the syntax naming of local variable (b5798)
   - [x] Addressed #125 incorrect highlight for punctuation and some other elements in VS 2019 (b5840, still working in progress)
- [x] Super Quick Info
   - [x] Fixed VS Extension info could cause problem in some cases (b5793)
- [x] Navigation Bar
   - [x] Fixed a crash when right clicking #region in drop down member list (b5778)

**Comment by fitdev** [comment]
I noticed that in the recent version the dropdown for NaviBar when displaying members of a `partial` type, it shows the file names (where various members of the partial type are defined) in _exactly the same way as the members themselves_.

I think it's best to draw the file names slightly differently, so that:
- They can act as a header for a list of the members it contains and that visually follow it
- To clearly distinguish it from the members themselves

Currently it is difficult to immediately spot where the members defined in the current file end and where the partials begin.

**Comment by wmjordan** [comment]
Oops, you are right. I'd noticed that before the release of 5.6 but forgotten to fix it.

**Comment by wmjordan** [comment]
@fitdev I'd just uploaded a new release to fix the problem you mentioned above.

**Comment by fitdev** [comment]
Thank you! Will check it out soon!

**Comment by wmjordan** [comment]
@fitdev I'd just updated Codist to support Chinese.
Could you please help test it on your computer and see whether your current working experience is OK?

**Comment by fitdev** [comment]
Seems to be working fine. Was something supposed to be different?

**Comment by wmjordan** [comment]
> Was something supposed to be different?

Nothing is supposed to be different non-Simplified-Chinese users.



> while publish operation was in progress there was an error

Thank you for reporting this. I will look into it.

**Comment by wmjordan** [comment]
@fitdev Please try the new beta.
