### ISSUE TITLE
Codist 5.8 RC version

### ISSUE THREAD

**Issue by wmjordan** [wmjordan/Codist#127]
# Download
[Codist 6031](https://github.com/wmjordan/Codist/files/5402037/Codist.zip)

[Codist 6018](https://github.com/wmjordan/Codist/files/5395053/Codist.zip)
[Codist 6005](https://github.com/wmjordan/Codist/files/5389034/Codist.zip)
[Codist 5995](https://github.com/wmjordan/Codist/files/5368719/Codist.zip)
[Codist 5987](https://github.com/wmjordan/Codist/files/5359179/Codist.zip)
[Codist 5979](https://github.com/wmjordan/Codist/files/5339549/Codist.zip)
[Codist 5940](https://github.com/wmjordan/Codist/files/5272910/Codist.zip)
[Codist 5938](https://github.com/wmjordan/Codist/files/5236722/Codist.zip)
[Codist 5927](https://github.com/wmjordan/Codist/files/5148255/Codist.zip)
[Codist 5924](https://github.com/wmjordan/Codist/files/5025806/Codist.zip)
[Codist 5921](https://github.com/wmjordan/Codist/files/5006239/Codist.zip)

# What's new

- [x] General
   - [x] Reduced download size by removing unused component dependencies (b5979)
   - [x] Upgraded referenced components (b5979)
   - [x] Small improvement of performance in some cases (b5979)
   - [x] Fixed some numeric values were not saved if modified by keyboard in the options page (b6018)
   - [x] Extracted web search options from Smart Bar to an individual page (b6031)
   - [x] Removed behavior of resetting comment tag labels and search engines if they were empty (b6031)
- [x] Symbol list
   - [x] Used syntax highlight color in symbol list (b5921, b5927)
   - [x] ➕ Added new analysis command _Find inherited interfaces_ (b5938)
   - [x] Allowed to restrict some code analysis commands by pressing _Ctrl_ key (b5979)
- [x] Smart bar
   - [x] Optimized behavior of Paste, Delete and some editorial commands (b5921)
   - [x] ➕ Added _Find all reference_ command for C++ symbols (b5938)
   - [x] ➕ Added command to edit all matching (b5979)
   - [x] ➕ Added more shortcuts to open files in the output window (b5979)
- [x] Syntax highlight
   - [x] Fixed incorrect classification of `sealed` members (b5921)
   - [x] ➕ Added auto detection of VS theme color and loading syntax highlight theme accordingly at the first run (b6031)
- [x] Navigation bar
   - [x] ➕ Added new option to display members defined in base classes (b5924)
   - [x] Allowed using space delimited search keywords (b5987, #128)
   - [x] Used incremental search for better performance when search symbols in project (b5987)
- [x] Super Quick Info
   - [x] Made better compatible with the recent versions of VS 2019 (b5940)
   - [x] Made `<seealso>` tag rendered inline within section elements (b5995, #132)
   - [x] Fixed `<seealso href/>` tag could cause error (b5995)
   - [x] Allowed multiple `<example/>` tags (b5995)
   - [x] Fixed `<example/>` option was not regardled (b5995)
   - [x] ➕ Added right click selected text in Quick Info to bring out web search menu (b6005)
   - [x] Fixed content could be clipped off in VS 2019 (b6018)
   - [x] ➕ Supported `<hr/>` tag in C# XML Doc (b6031)

**Comment by wmjordan** [comment]
A new beta version 5921 is released today.

**Comment by wmjordan** [comment]
A new beta version 5927 is released today.

**Comment by wmjordan** [comment]
A new beta version is released today.

**Comment by alekseyaz** [comment]
Bug 5.8, truncates the last line
![Screenshot_1](https://user-images.githubusercontent.com/54514236/96218589-b667e680-0f8d-11eb-99e3-f2cd848af687.png)
![Screenshot_2](https://user-images.githubusercontent.com/54514236/96218617-c7b0f300-0f8d-11eb-9e85-f0432e14b6e5.png)

**Comment by wmjordan** [comment]
Bug confirmed. Thanks!

**Comment by wmjordan** [comment]
@alekseyaz Please download the new beta which has fixed aforementioned problem.
