### ISSUE TITLE
Suggestion: better filtering with partial search text matching

### ISSUE THREAD

**Issue by fantasyz** [wmjordan/Codist#128]
In the original Go To Member, if I type "Get Unit" with a space in between words, the filtering will return items that match the pattern GetXXXUnit. e.g. GetFallenUnit, GetSummonUnit, GetNpcUnit, ... will all be in the drop down.

However , in Codist it seems that the matching use "Get Unit" as a whole word missing lots of potential results.

My suggestion is to tokenize the search text with space and try match all of them in sequence to make it more flexible like the original Go To Member.

Thanks

**Comment by wmjordan** [comment]
Are you referring to the filter in the leftmost drop down menu in the Navigation Bar?

**Comment by fantasyz** [comment]
Yes, the Search Declaration drop down.

**Comment by fantasyz** [comment]
While it could be slow when searching global, I often use it to find local declarations.

**Comment by wmjordan** [comment]
Alright, got it.

**Comment by wmjordan** [comment]
The search functionality and performance in the navigation bar has potential to be optimized but not been done yet.

**Comment by wmjordan** [comment]
Please download the recently released beta 5987 which addresses this issue.
