### ISSUE TITLE
possible to add more color to reference popup?

### ISSUE THREAD

**Issue by fantasyz** [wmjordan/Codist#129]
![reference popup](https://user-images.githubusercontent.com/3223242/93694673-35a9fc00-fb41-11ea-986c-5d87447457ad.jpg)

Just wondering, can the reference popup be improved to have more color on the text? Having every text in white color is hard to read. Below is one I test in photoshop. It emphasize the source file and darken the file path which is not that important for this popup. What do you think?

![refer_suggest](https://user-images.githubusercontent.com/3223242/93694735-08118280-fb42-11ea-829d-878102b5fa45.jpg)

**Comment by wmjordan** [comment]
I will check it.
But don't be in too much hope of it.
There's no API offering such kind of functionality.
