### ISSUE TITLE
Cannot locate resource navigationbar.xaml

### ISSUE THREAD

**Issue by edbo23** [wmjordan/Codist#130]
When I run the visual studio project I get an exception in the WpfHelper.cs file on line 414:
return (ResourceDictionary)Application.LoadComponent(new Uri("/" + nameof(Codist) + ";component/" + uri, UriKind.Relative));
Cannot locate resource 'codist;controls/navigationbar.xaml'
I am running VS 2019 16.7.4, How can I fix this?

**Comment by wmjordan** [comment]
> When I run the visual studio project

Did you mean that you had **compiled the project from its source code** and got an exception with the compiled extension?

**Comment by edbo23** [comment]
Yes

**Comment by wmjordan** [comment]
Could you rebuild the project and try a gain?
Please take a look at the warning messages and see whether the XAML file was missing.

**Comment by edbo23** [comment]
The project builds. I found the file in my directory ..Codist-master\Codist\Controls
When the debug instance loads the pluging I get the message:
System.IO.IOException
  HResult=0x80131620
  Message=Cannot locate resource 'codist;controls/navigationbar.xaml'.
  Source=PresentationFramework
  StackTrace:
   at MS.Internal.AppModel.ResourcePart.GetStreamCore(FileMode mode, FileAccess access)
   at System.IO.Packaging.PackagePart.GetStream(FileMode mode, FileAccess access)
   at System.IO.Packaging.PackagePart.GetStream()
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.LoadComponent(Uri resourceLocator)
   at Codist.WpfHelper.LoadComponent(String uri) in C:\Users\pappy\source\repos\__GITHUB\Codist-master\Codist\Helpers\WpfHelper.cs:line 414
   at Codist.SharedDictionaryManager.get_Menu() in C:\Users\pappy\source\repos\__GITHUB\Codist-master\Codist\CodistPackage.cs:line 221
   at Codist.NaviBar.NaviBar..ctor(IWpfTextView textView) in C:\Users\pappy\source\repos\__GITHUB\Codist-master\Codist\NaviBar\NaviBar.cs:line 18
   at Codist.NaviBar.CSharpBar..ctor(IWpfTextView textView) in C:\Users\pappy\source\repos\__GITHUB\Codist-master\Codist\NaviBar\CSharpBar.cs:line 36
   at Codist.NaviBar.NaviBarFactory.Overrider.FindNaviBar(Object sender, RoutedEventArgs e) in C:\Users\pappy\source\repos\__GITHUB\Codist-master\Codist\NaviBar\NaviBarFactory.cs:line 120
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at MS.Internal.LoadedOrUnloadedOperation.DoWork()
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

  This exception was originally thrown at this call stack:
    [External Code]
    Codist.WpfHelper.LoadComponent(string) in WpfHelper.cs
    Codist.SharedDictionaryManager.Menu.get() in CodistPackage.cs
    Codist.NaviBar.NaviBar.NaviBar(Microsoft.VisualStudio.Text.Editor.IWpfTextView) in NaviBar.cs
    Codist.NaviBar.CSharpBar.CSharpBar(Microsoft.VisualStudio.Text.Editor.IWpfTextView) in CSharpBar.cs
    Codist.NaviBar.NaviBarFactory.Overrider.FindNaviBar(object, System.Windows.RoutedEventArgs) in NaviBarFactory.cs
    [External Code]

**Comment by wmjordan** [comment]
A XAML file located at controls/navigationbar.xaml was missing.
Could you find that file in the source folder?

**Comment by edbo23** [comment]
It's in the folder when I unzipped the download file. Here is the file definition:
My local folder is C:\Users\pappy\source\repos\__GITHUB\Codist-master\Codist\Controls

<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
	xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
	xmlns:nb="clr-namespace:Codist.NaviBar;assembly=Codist"
	xmlns:c="clr-namespace:Codist.Controls;assembly=Codist"
	xmlns:vsp="clr-namespace:Microsoft.VisualStudio.PlatformUI;assembly=Microsoft.VisualStudio.Shell.15.0">
	<Style x:Key="{x:Type nb:CSharpBar}" TargetType="{x:Type nb:CSharpBar}">
		<Setter Property="OverridesDefaultStyle" Value="True"/>
		<Setter Property="SnapsToDevicePixels" Value="True"/>
		<Setter Property="Template">
			<Setter.Value>
				<ControlTemplate TargetType="{x:Type ToolBar}">
					<StackPanel CanHorizontallyScroll="True" MaxHeight="22" ClipToBounds="True" Orientation="Horizontal" Background="{DynamicResource VsBrush.CommandBarMenuBackgroundGradient}" IsItemsHost="True" />
				</ControlTemplate>
			</Setter.Value>
		</Setter>
	</Style>
	<Style x:Key="{x:Type nb:MarkdownBar}" TargetType="{x:Type nb:MarkdownBar}">
		<Setter Property="OverridesDefaultStyle" Value="True"/>
		<Setter Property="SnapsToDevicePixels" Value="True"/>
		<Setter Property="Template">
			<Setter.Value>
				<ControlTemplate TargetType="{x:Type ToolBar}">
					<StackPanel CanHorizontallyScroll="True" MaxHeight="22" ClipToBounds="True" Orientation="Horizontal" Background="{DynamicResource VsBrush.CommandBarMenuBackgroundGradient}" IsItemsHost="True" />
				</ControlTemplate>
			</Setter.Value>
		</Setter>
	</Style>
	<Style x:Key="{x:Type Separator}" TargetType="{x:Type Separator}">
		<Setter Property="OverridesDefaultStyle" Value="True"/>
		<Setter Property="Height" Value="16"/>
		<Setter Property="Margin" Value="0,4,0,3"/>
		<Setter Property="Template">
			<Setter.Value>
				<ControlTemplate TargetType="{x:Type Separator}">
					<Border BorderThickness="0,0,0,1" BorderBrush="{DynamicResource VsBrush.CommandBarMenuSeparator}">
						<ContentPresenter Name="Header" Content="{TemplateBinding Tag}" />
					</Border>
					<ControlTemplate.Triggers>
						<Trigger Property="Tag" Value="{x:Null}">
							<Setter TargetName="Header" Property="Visibility" Value="Collapsed"/>
							<Setter Property="Height" Value="1"/>
						</Trigger>
					</ControlTemplate.Triggers>
				</ControlTemplate>
			</Setter.Value>
		</Setter>
	</Style>
	<Style x:Key="{x:Static MenuItem.SeparatorStyleKey}" TargetType="{x:Type Separator}">
		<Setter Property="Template">
			<Setter.Value>
				<ControlTemplate TargetType="{x:Type Separator}">
					<Border Height="16" BorderThickness="0,0,0,1" BorderBrush="{DynamicResource VsBrush.CommandBarMenuSeparator}">
						<ContentPresenter Name="Header" Content="{TemplateBinding Tag}" />
					</Border>
					<ControlTemplate.Triggers>
						<Trigger Property="Tag" Value="{x:Null}">
							<Setter TargetName="Header" Property="Visibility" Value="Collapsed"/>
							<Setter Property="Height" Value="1"/>
						</Trigger>
					</ControlTemplate.Triggers>
				</ControlTemplate>
			</Setter.Value>
		</Setter>
	</Style>
	
	<Style x:Key="{x:Type c:ThemedMenuItem}" TargetType="{x:Type c:ThemedMenuItem}">
		<Setter Property="OverridesDefaultStyle" Value="True"/>
		<Setter Property="Background" Value="{DynamicResource VsBrush.CommandBarMenuBackgroundGradient}"/>
		<Setter Property="Foreground" Value="{DynamicResource VsBrush.CommandBarTextInactive}"/>
		<Style.Triggers>
			<Trigger Property="Role" Value="TopLevelHeader">
				<Setter Property="Template" Value="{StaticResource {x:Static MenuItem.TopLevelHeaderTemplateKey}}"/>
			</Trigger>
			<Trigger Property="Role" Value="TopLevelItem">
				<Setter Property="Template" Value="{StaticResource {x:Static MenuItem.TopLevelItemTemplateKey}}"/>
			</Trigger>
			<Trigger Property="Role" Value="SubmenuHeader">
				<Setter Property="Template" Value="{StaticResource {x:Static MenuItem.SubmenuHeaderTemplateKey}}"/>
			</Trigger>
			<Trigger Property="Role" Value="SubmenuItem">
				<Setter Property="Template" Value="{StaticResource {x:Static MenuItem.SubmenuItemTemplateKey}}"/>
			</Trigger>
		</Style.Triggers>
	</Style>
	
	<ControlTemplate x:Key="{x:Static MenuItem.TopLevelItemTemplateKey}" TargetType="{x:Type c:ThemedMenuItem}">
		<Border x:Name="Border" BorderThickness="1">
			<StackPanel Orientation="Horizontal" HorizontalAlignment="Left">
				<ContentPresenter Content="{TemplateBinding MenuItem.Icon}" ContentSource="Icon" Name="Icon" Width="16" Height="16" Margin="3,2,3,2" HorizontalAlignment="Center" VerticalAlignment="Center"/>
				<ContentPresenter RecognizesAccessKey="False" Content="{TemplateBinding HeaderedContentControl.Header}" ContentTemplate="{TemplateBinding HeaderedContentControl.HeaderTemplate}" ContentStringFormat="{TemplateBinding HeaderedItemsControl.HeaderStringFormat}" ContentSource="Header" Margin="0,0,3,0" VerticalAlignment="Center" Grid.Column="1"/>
			</StackPanel>
		</Border>
		<ControlTemplate.Triggers>
			<Trigger Property="IsChecked" Value="true">
				<Setter TargetName="Border" Property="Background" Value="{DynamicResource VsBrush.FileTabSelectedGradientTop}" />
				<Setter TargetName="Border" Property="BorderThickness" Value="1,0,1,1" />
				<Setter TargetName="Border" Property="Padding" Value="0,1,0,0" />
			</Trigger>
			<Trigger Property="Icon" Value="{x:Null}">
				<Setter TargetName="Icon" Property="Visibility" Value="Collapsed"/>
			</Trigger>
			<Trigger Property="IsHighlighted" Value="true">
				<Setter TargetName="Border" Property="Background" Value="{DynamicResource VsBrush.CommandBarMouseOverBackgroundGradient}"/>
				<Setter TargetName="Border" Property="BorderBrush" Value="{DynamicResource VsBrush.CommandBarHoverOverSelectedIconBorder}"/>
				<Setter TargetName="Border" Property="BorderThickness" Value="1" />
				<Setter TargetName="Border" Property="Padding" Value="0" />
			</Trigger>
			<Trigger Property="IsEnabled" Value="False">
				<Setter Property="Foreground" Value="Gray"/>
			</Trigger>
		</ControlTemplate.Triggers>
	</ControlTemplate>
	
	<ControlTemplate x:Key="{x:Static MenuItem.TopLevelHeaderTemplateKey}" TargetType="{x:Type c:ThemedMenuItem}">
		<Border x:Name="Border" BorderThickness="1">
			<StackPanel Orientation="Horizontal" HorizontalAlignment="Left">
				<ContentPresenter Content="{TemplateBinding MenuItem.Icon}" ContentSource="Icon" Name="Icon" Width="16" Height="16" Margin="3,2,3,2" HorizontalAlignment="Center" VerticalAlignment="Center"/>
				<ContentPresenter RecognizesAccessKey="False" Content="{TemplateBinding HeaderedContentControl.Header}" ContentTemplate="{TemplateBinding HeaderedContentControl.HeaderTemplate}" ContentStringFormat="{TemplateBinding HeaderedItemsControl.HeaderStringFormat}" ContentSource="Header" Margin="0,0,3,0" VerticalAlignment="Center" Grid.Column="1"/>
				<Popup x:Name="Popup" Placement="Bottom" HorizontalOffset="-1" IsOpen="{TemplateBinding IsSubmenuOpen}" AllowsTransparency="True" Focusable="False" PopupAnimation="{DynamicResource {x:Static SystemParameters.MenuPopupAnimationKey}}" StaysOpen="True">
					<Border x:Name="SubmenuBorder" SnapsToDevicePixels="True" BorderThickness="1" Background="{DynamicResource VsBrush.CommandBarMenuBackgroundGradient}" BorderBrush="{DynamicResource VsBrush.CommandBarMenuBorder}">
						<StackPanel Margin="3">
							<ContentPresenter x:Name="PopupHeader" Content="{TemplateBinding SubMenuHeader}" ContentSource="Tag" Margin="0,0,0,3"/>
							<ScrollViewer x:Name="SubMenuScrollViewer" MaxHeight="{TemplateBinding SubMenuMaxHeight}" VerticalScrollBarVisibility="Auto" HorizontalScrollBarVisibility="Auto">
								<ItemsPresenter KeyboardNavigation.DirectionalNavigation="Cycle"/>
							</ScrollViewer>
						</StackPanel>
					</Border>
				</Popup>
			</StackPanel>
		</Border>
		<ControlTemplate.Triggers>
			<Trigger Property="IsSuspendingPopupAnimation" Value="true">
				<Setter TargetName="Popup" Property="PopupAnimation" Value="None"/>
			</Trigger>
			<Trigger Property="Icon" Value="{x:Null}">
				<Setter TargetName="Icon" Property="Visibility" Value="Collapsed"/>
			</Trigger>
			<Trigger Property="IsHighlighted" Value="true">
				<Setter TargetName="Border" Property="BorderBrush" Value="{DynamicResource VsBrush.CommandBarHoverOverSelectedIconBorder}"/>
				<Setter TargetName="Border" Property="Background" Value="{DynamicResource VsBrush.CommandBarMouseOverBackgroundGradient}"/>
			</Trigger>
			<Trigger SourceName="Popup" Property="AllowsTransparency" Value="True">
				<Setter TargetName="SubmenuBorder" Property="CornerRadius" Value="0,0,4,4"/>
			</Trigger>
			<Trigger Property="IsEnabled" Value="False">
				<Setter Property="Foreground" Value="Gray"/>
			</Trigger>
		</ControlTemplate.Triggers>
	</ControlTemplate>
	
	<ControlTemplate x:Key="{x:Static MenuItem.SubmenuItemTemplateKey}" TargetType="{x:Type c:ThemedMenuItem}">
		<Border x:Name="Border" BorderThickness="1" Background="{TemplateBinding Background}" Opacity="{TemplateBinding Opacity}">
			<Grid>
				<Grid.ColumnDefinitions>
					<ColumnDefinition Width="Auto" SharedSizeGroup="Icon"/>
					<ColumnDefinition Width="*"/>
					<ColumnDefinition Width="Auto" SharedSizeGroup="Shortcut"/>
					<ColumnDefinition Width="13"/>
				</Grid.ColumnDefinitions>
				<ContentPresenter x:Name="Icon" Margin="3,0,6,0" VerticalAlignment="Center" ContentSource="Icon"/>
				<Border x:Name="Check" Width="13" Height="13" Visibility="Collapsed" Margin="6,0,6,0" BorderThickness="1">
					<Path x:Name="CheckMark" Width="7" Height="7" Visibility="Hidden" SnapsToDevicePixels="False" StrokeThickness="2" Data="M 0 0 L 7 7 M 0 7 L 7 0" Stroke="{DynamicResource VsBrush.CommandBarMenuSubmenuGlyph}"/>
				</Border>
				<ContentPresenter x:Name="HeaderHost" MaxWidth="500" Grid.Column="1" VerticalAlignment="Center" ContentSource="Header" RecognizesAccessKey="False"/>
				<TextBlock x:Name="InputGestureText" Grid.Column="2" Text="{TemplateBinding InputGestureText}" MaxWidth="200" Height="{Binding ElementName=HeaderHost,Path=ActualHeight}" TextTrimming="CharacterEllipsis" Margin="5,2,0,2" DockPanel.Dock="Right" VerticalAlignment="Center" Foreground="{DynamicResource VsBrush.GrayText}"/>
			</Grid>
		</Border>
		<ControlTemplate.Triggers>
			<Trigger Property="ButtonBase.Command" Value="{x:Null}"/>
			<Trigger Property="Icon" Value="{x:Null}">
				<Setter TargetName="Icon" Property="Visibility" Value="Hidden"/>
			</Trigger>
			<Trigger Property="IsChecked" Value="true">
				<Setter TargetName="Border" Property="Background" Value="{DynamicResource {x:Static vsp:EnvironmentColors.CommandBarMenuItemMouseOverBrushKey}}" />
			</Trigger>
			<Trigger Property="IsCheckable" Value="true">
				<Setter TargetName="Check" Property="Visibility" Value="Visible"/>
				<Setter TargetName="Icon" Property="Visibility" Value="Hidden"/>
			</Trigger>
			<Trigger Property="IsHighlighted" Value="true">
				<Setter TargetName="Border" Property="Background" Value="{DynamicResource {x:Static vsp:EnvironmentColors.CommandBarMenuItemMouseOverBrushKey}}" />
				<Setter TargetName="Border" Property="BorderBrush" Value="{DynamicResource VsBrush.CommandBarHoverOverSelectedIconBorder}"/>
			</Trigger>
			<Trigger Property="IsEnabled" Value="false">
				<Setter Property="Foreground" Value="Gray"/>
			</Trigger>
		</ControlTemplate.Triggers>
	</ControlTemplate>
	<ControlTemplate x:Key="{x:Static MenuItem.SubmenuHeaderTemplateKey}" TargetType="{x:Type c:ThemedMenuItem}">
		<Border x:Name="Border" BorderThickness="1">
			<Grid>
				<Grid.ColumnDefinitions>
					<ColumnDefinition Width="Auto" SharedSizeGroup="Icon"/>
					<ColumnDefinition Width="*"/>
					<ColumnDefinition Width="Auto" SharedSizeGroup="Shortcut"/>
					<ColumnDefinition Width="13"/>
				</Grid.ColumnDefinitions>
				<ContentPresenter x:Name="Icon" Margin="3,0,6,0" VerticalAlignment="Center" ContentSource="Icon"/>
				<ContentPresenter x:Name="HeaderHost" Grid.Column="1" VerticalAlignment="Center" ContentSource="Header" RecognizesAccessKey="False" MaxWidth="500"/>
				<TextBlock x:Name="InputGestureText" Grid.Column="2" Text="{TemplateBinding InputGestureText}" MaxWidth="200" Height="{Binding ElementName=HeaderHost,Path=ActualHeight}" TextTrimming="CharacterEllipsis" Margin="5,2,0,2" DockPanel.Dock="Right" VerticalAlignment="Center" Foreground="{DynamicResource VsBrush.GrayText}"/>
				<Path Grid.Column="3" HorizontalAlignment="Center" VerticalAlignment="Center" Data="M 0 0 L 0 7 L 4 3.5 Z" Fill="{DynamicResource VsBrush.CommandBarMenuSubmenuGlyph}" />
				<Popup x:Name="Popup" Placement="Right" HorizontalOffset="-1" IsOpen="{TemplateBinding IsSubmenuOpen}" AllowsTransparency="True" Focusable="False" PopupAnimation="{DynamicResource {x:Static SystemParameters.MenuPopupAnimationKey}}">
					<Border x:Name="SubmenuBorder" SnapsToDevicePixels="True" BorderThickness="1" Background="{DynamicResource VsBrush.CommandBarMenuBackgroundGradient}" BorderBrush="{DynamicResource VsBrush.CommandBarMenuBorder}">
						<StackPanel Margin="3">
							<ContentPresenter x:Name="PopupHeader" Content="{TemplateBinding SubMenuHeader}" ContentSource="Tag" Margin="0,0,0,3"/>
							<ScrollViewer Name="SubMenuScrollViewer" MaxHeight="{TemplateBinding SubMenuMaxHeight}" VerticalScrollBarVisibility="Auto" HorizontalScrollBarVisibility="Auto">
								<ItemsPresenter KeyboardNavigation.DirectionalNavigation="Cycle"/>
							</ScrollViewer>
						</StackPanel>
					</Border>
				</Popup>
			</Grid>
		</Border>
		<ControlTemplate.Triggers>
			<Trigger Property="Icon" Value="{x:Null}">
				<Setter TargetName="Icon" Property="Visibility" Value="Collapsed"/>
			</Trigger>
			<Trigger Property="IsHighlighted" Value="true">
				<Setter TargetName="Border" Property="Background" Value="{DynamicResource VsBrush.CommandBarMouseOverBackgroundGradient}" />
				<Setter TargetName="Border" Property="BorderBrush" Value="{DynamicResource VsBrush.CommandBarHoverOverSelectedIconBorder}"/>
			</Trigger>
			<Trigger SourceName="Popup" Property="AllowsTransparency" Value="True">
				<Setter TargetName="SubmenuBorder" Property="CornerRadius" Value="0,0,4,4"/>
			</Trigger>
			<Trigger Property="IsEnabled" Value="false">
				<Setter Property="Foreground" Value="Gray"/>
			</Trigger>
		</ControlTemplate.Triggers>
	</ControlTemplate>
</ResourceDictionary>

**Comment by edbo23** [comment]
Can the file be corrupt?

**Comment by wmjordan** [comment]
If you download the source code, the file should be good.

Could you check the build messages from the _Output_ window in VS?

**Comment by edbo23** [comment]
The project builds with no errors and I can't find the word navigation anywhere in the ErrorList or output window. And I see the file on my local drive at
C:\Users\pappy\source\repos\__GITHUB\Codist-master\Codist\Controls\NavigationBar.xaml

**Comment by edbo23** [comment]
I am a winforms programmer not a wpf guy but I'm trying...

**Comment by edbo23** [comment]
Can I be missing something on my PC like an sdk or can I be missing a target pack or something like that>?

**Comment by wmjordan** [comment]
> The project builds with no errors

There shall be some warnings. Please check to see whether there are some warnings related.



> Can I be missing something on my PC

Had you installed VS 2019 with the Windows Desktop Development and Visual Studio Extension Development payloads, you should have everything needed.

**Comment by edbo23** [comment]
I put a break point at the crash line and the uri parameter shows in the debugger as 
/Codist;component//Codist;controls/NavigationBar.xaml

**Comment by wmjordan** [comment]
The URI was wrong.
It should be "`/Codist;component/controls/NavigationBar.xaml`"
Had you modified the source code?

**Comment by edbo23** [comment]
No. in the code 
		public static ResourceDictionary LoadComponent(string uri) {
			return (ResourceDictionary)Application.LoadComponent(new Uri("/" + nameof(Codist) + ";component/" + uri, UriKind.Relative));
		}

The value of the LoadComponent parameter is
@"/Codist;component//Codist;controls/NavigationBar.xaml"

**Comment by edbo23** [comment]
are you talking about the string uri or the Uri object?

**Comment by wmjordan** [comment]
The string parameter `uri`.
The composed Uri object should be "`/Codist;component/controls/NavigationBar.xaml`"

**Comment by edbo23** [comment]
The uri string in the method comes in as this:

@"/Codist;controls/NavigationBar.xaml"

**Comment by edbo23** [comment]
this is the Uri object tostring I get:

@"/Codist;component//Codist;controls/NavigationBar.xaml"

**Comment by wmjordan** [comment]
> The uri string in the method comes in as this:
> 
> @"/Codist;controls/NavigationBar.xaml"

Wrong.
Please check the source code of CodistPackage.cs.

There should be this line:
````C#
internal static ResourceDictionary Menu => _Menu ?? (_Menu = WpfHelper.LoadComponent("controls/NavigationBar.xaml").MergeWith(ThemedControls));
````

**Comment by edbo23** [comment]
I am just looking at the input value in the debugger just at the crash line

line 414 in WpfHelper.cs

**Comment by edbo23** [comment]
Line 221 in the CodistPackage.cs	

	internal static ResourceDictionary Menu => _Menu ?? (_Menu = WpfHelper.LoadComponent("/Codist;controls/NavigationBar.xaml").MergeWith(ThemedControls));

**Comment by wmjordan** [comment]
Please check my code.

https://github.com/wmjordan/Codist/blob/v5.7/Codist/CodistPackage.cs#L221
