### ISSUE TITLE
The "seealso" section does not display correctly

### ISSUE THREAD

**Issue by alekseyaz** [wmjordan/Codist#132]
The "seealso" section does not display correctly, place it correctly inside the summary example. Try this and that option.

```cpp
/// text for class TestClass
public class TestClass
{
    /// <summary>DoWork is a method in the TestClass class.
    /// <para>Here's how you could make a second paragraph in a description. <see cref="System.Console.WriteLine(System.String)"/> for information about output statements.</para>
    /// <seealso cref="TestClass.Main"/>
    /// </summary>
    public static void DoWork(int Int1)
    {
    }
    /// text for Main
    static void Main()
    {
    }
}

------------

/// text for class TestClass
public class TestClass
{
    /// <summary>DoWork is a method in the TestClass class.
    /// <para>Here's how you could make a second paragraph in a description. <see cref="System.Console.WriteLine(System.String)"/> for information about output statements.</para>
    /// </summary>
    /// <seealso cref="TestClass.Main"/>
    public static void DoWork(int Int1)
    {
    }

    /// text for Main
    static void Main()
    {
    }
}
```

[https://docs.microsoft.com/ru-ru/dotnet/csharp/programming-guide/xmldoc/see](url)

**Comment by wmjordan** [comment]
Thank you for reporting this.
I'll fix it.

**Comment by wmjordan** [comment]
It seems that the bug is not in Codist but in docs.microsoft.com.

Let's take a look at the [implementation of DocFX](https://github.com/dotnet/docfx/blob/v2.56.3/src/Microsoft.DocAsCode.Metadata.ManagedReference.Common/Parsers/TripleSlashCommentModel.cs#L250), `seealso` elements are supposed to be children of `member` elements rather than `summary`.

**Comment by wmjordan** [comment]
Please download the latest beta which has addressed this problem.
