### ISSUE TITLE
Doesn't work correctly <br/> in summary, does not wrap lines.

### ISSUE THREAD

**Issue by alekseyaz** [wmjordan/Codist#133]
Doesn't work correctly <br/> in summary, does not wrap lines.

Why not reuse the generic roslyn implementation
Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.QuickInfo.IntellisenseQuickInfoBuilder.cs
and the helpers Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Helpers.cs

**Comment by alekseyaz** [comment]
it might be useful to have a look
https://github.com/dotnet/roslyn/blob/master/src/Features/Core/Portable/DocumentationComments/AbstractDocumentationCommentFormattingService.cs

**Comment by wmjordan** [comment]
Thank you for the link and information.
The logic in _the generic roslyn implementation_ is internal and lots of classes are involved. Thus I programmed my own.
`<br>` will be added to the next beta version in Super Quick Info.

**Comment by alekseyaz** [comment]
Can use QuickInfoService Roslyn it outputs formatted information with processed tags at the output, then all that remains is to resolve the links. An example of implementation can be found at:
https://github.com/OmniSharp/omnisharp-roslyn

**Comment by alekseyaz** [comment]
[https://github.com/OmniSharp/omnisharp-roslyn/blob/0a1f77405ce536bbb56fd6fe0c11d254dc029006/src/OmniSharp.Roslyn.CSharp/Services/QuickInfoProvider.cs](url)

**Comment by alekseyaz** [comment]
https://github.com/aelij/RoslynPad/blob/master/src/RoslynPad.Roslyn/QuickInfo/QuickInfoProvider.cs

**Comment by wmjordan** [comment]
Thank you very much for the information. I will check them out and reply you later.

**Comment by wmjordan** [comment]
Thank you very much for your information.
I installed the QuickInfoService related Roslyn package from Nuget and found that `GetQuickInfoAsync` only provided limited information (no `remarks` for example) and some formats in the XML Documentation were dropped out. Newer version may be better. But Codist are still supporting VS 2017 which still uses Roslyn 2.* whereas VS 2019 uses Roslyn 3.*.

Codist still has to get on and on with the hard mode.
