### ISSUE TITLE
Suggestion: Super Quick Info add translation

### ISSUE THREAD

**Issue by RC1844** [wmjordan/Codist#134]
Can you try to add web translation to QuickInfo's summary?

Just add translation and keep the original summary.

![Snipaste_2020-10-15_12-37-47](https://user-images.githubusercontent.com/14369275/96078255-62ed8e00-0ee4-11eb-9287-4409344df6f6.png)

**Comment by wmjordan** [comment]
I'd thought of that years ago.
Unfortunately there's no way to obtain the translated XML documentation via the existing API of VS or roslyn.

**Comment by RC1844** [comment]
> Unfortunately there's no way to obtain the translated XML documentation via the existing API of VS or roslyn.
Get summary in xml → Translate summary → Add Translated summary to Super Quick Info
 
Is it okay?

**Comment by wmjordan** [comment]
Where's the translation?

**Comment by RC1844** [comment]
google translation 
We don’t translate xml, just translate the summary part, don’t write xml, and don’t make any changes
Can I speak Chinese?

**Comment by wmjordan** [comment]
How can you access the Google translation API in China?

Nowadays, you can select contents in the Quick Info, right click the selection to bring out a menu to `Copy` the selection and switch to online translation services.

**Comment by RC1844** [comment]
> How can you access the Google translation API in China?

This is not the point. There are many alternatives in China, such as Baidu and Youdao.

> Nowadays, you can select contents in the Quick Info, right click the selection to bring out a menu to `Copy` the selection and switch to online translation services.

too troublesome

**Comment by RC1844** [comment]
@wmjordan 
Perhaps, I should create an extension for this. But I have not been able to find the API to get Comments. Maybe my direction is wrong, can you guide me? Thank you!

**Comment by wmjordan** [comment]
OK.
I understood your request.

However, integrating the content into Quick Info is not so viable, since online service will usually not yet returns the translation to Codist when Quick Info is displayed. The result may be presented in another floating window asynchronously.

**Comment by wmjordan** [comment]
> I have not been able to find the API to get Comments

It is not an easy job. A lot of things have to be done.
You can take a look at this file, which has covered most of the stuff, but not yet fully implemented (for instance, `Deconstruct` in C# 7 has not yet supported in Codist):
https://github.com/wmjordan/Codist/blob/master/Codist/QuickInfo/CSharpQuickInfo.cs

**Comment by RC1844** [comment]
It's really not an easy job. I may need a long time to study. Thanks for your guidance.

**Comment by wmjordan** [comment]
You may take a look at #133 .
The author of that issue had given quite a few links about the `QuickInfoService` in Roslyn. It shall be much easier to get you started from that class.

**Comment by RC1844** [comment]
nice.  I will study it carefully, thank you.

**Comment by alekseyaz** [comment]
Implementation of a translation service
https://github.com/Kerwin1202/VsTranslator

**Comment by RC1844** [comment]
@alekseyaz Thank you. This can ease part of my work.

**Comment by alekseyaz** [comment]
I just added a primitive google translate option, as an example can be found in the feature-translate branch
https://github.com/alekseyaz/Codist/tree/feature-translate

![Screenshot_3](https://user-images.githubusercontent.com/54514236/96346534-ee158200-10a4-11eb-9d00-3efd60496f8c.png)
![Screenshot_4](https://user-images.githubusercontent.com/54514236/96346537-f077dc00-10a4-11eb-8cde-cd85d8f6e1b0.png)
![Screenshot_5](https://user-images.githubusercontent.com/54514236/96346540-f40b6300-10a4-11eb-85ae-9c4541a1bced.png)

**Comment by RC1844** [comment]
> I just added a primitive google translate option, as an example can be found in the feature-translate branch

cool. 


@alekseyaz Maybe it doesn't need me to do anything. Add xx seconds to display the translation or translation cache, add the translation to the asynchronous thread, even if the work is completed

**Comment by alekseyaz** [comment]
Converted to async and HttpClient

**Comment by wmjordan** [comment]
@RC1844 
Do you know about any high quality **free** Chinese translation service API?

**Comment by RC1844** [comment]
> @RC1844 
> Do you know about any high quality **free** Chinese translation service API?

Alibaba Cloud Machine Translation API
Tencent Cloud Translation API
Baidu Translate API
Both have word limits.

libretranslate Self hosted, unlimited.
