### ISSUE TITLE
Wrong indentation on attributes when the sizes of its name and notation are small

### ISSUE THREAD

**Issue by laicasaane** [wmjordan/Codist#140]
The sizes of both `C#: Attribute name` and `C#: Attribute notation` are set to -4

![2020-12-29_13-25-22](https://user-images.githubusercontent.com/1594982/103263051-5358ee00-49d9-11eb-8acc-fb6b31ed7444.png)

**Comment by wmjordan** [comment]
Oh, currently there's no way in my mind to fix this.
I will keep this open and try to find out a way.

**Comment by wmjordan** [comment]
Please try the new beta.

**Comment by wmjordan** [comment]
@fitdev, I don't know whether you have met with this issue as well before.
Please help test the new beta and see whether your code files are probably highlighted.

**Comment by laicasaane** [comment]
The beta works well. Thank you!

**Comment by fitdev** [comment]
@wmjordan No I have not seen this before. My attributes are appropriately aligned, even though I too use a smaller font size for them.

**Comment by wmjordan** [comment]
@fitdev, thank you for verifying this.
This issue occurred when spaces, instead of tabs, are used to indent the code.
