### ISSUE TITLE
An option to differentiate class and struct constructor methods

### ISSUE THREAD

**Issue by laicasaane** [wmjordan/Codist#141]
As mentioned in https://github.com/wmjordan/Codist/issues/108#issuecomment-559044747 there is still no option to do this. The constructor methods of both class and struct are still treated the same.

**Comment by wmjordan** [comment]
Please download the recent beta which has addressed this issue.

**Comment by wmjordan** [comment]
Have you tried this option yet?

**Comment by laicasaane** [comment]
Oh I forgot to give a feedback: it works well. Thank you!

**Comment by wmjordan** [comment]
Thanks! Good to hear that.
