### ISSUE TITLE
Super Quick Info: inconsistent display of namespace

### ISSUE THREAD

**Issue by laicasaane** [wmjordan/Codist#144]
The namespace of a type and its members should be displayed consistently: in a separated Namespace line, before the Assembly line.

![2021-01-31_18-53-34](https://user-images.githubusercontent.com/1594982/106382996-b03f2e00-63f5-11eb-8ac7-a94c2d2c289c.png)

![2021-01-31_18-53-49](https://user-images.githubusercontent.com/1594982/106382998-b1705b00-63f5-11eb-835f-9e5dd6b82891.png)

I'm using the build 6100.

**Comment by laicasaane** [comment]
Or the namespace line could appear right after the member or type name line?

**Comment by laicasaane** [comment]
I prefer namespace to be in a line of its own, because sometimes namespace could be pretty as long as the type name, together they make the quick info wider than necessary.

**Comment by wmjordan** [comment]
Oh, this is some part of the oldest bits in Codist. I have abandon it in my daily usage for years.

Usually I use the tool tip on the first line of the Quick Info, i.e. the member signature which will display more comprehensive info for the member.
