### ISSUE TITLE
Visual Studio crashes when trying to view markdown file

### ISSUE THREAD

**Issue by MrClyfar** [wmjordan/Codist#145]
I'm using Codist v5.9 with

> Microsoft Visual Studio Enterprise 2019
> Version 16.8.4
> VisualStudio.16.Release/16.8.4+30907.101
> Microsoft .NET Framework
> Version 4.8.03752
> 

I had Visual Studio open, but without any solutions or projects loaded.

When browsing the Source Control Explorer window, I wanted to view a ReadMe.md markdown format file from one of our projects. When I right-clicked on that file and chose `View`, Visual Studio churned for a bit and then crashed.

Looking in the `Event Viewer` in Windows, I spotted this error...

> Application: devenv.exe
> Framework Version: v4.0.30319
> Description: The process was terminated due to an unhandled exception.
> Exception Info: System.Collections.Generic.KeyNotFoundException
>    at Microsoft.VisualStudio.Utilities.PropertyCollection.GetProperty(System.Object)
>    at Codist.NaviBar.MarkdownBar..ctor(Microsoft.VisualStudio.Text.Editor.IWpfTextView, Microsoft.VisualStudio.Text.Operations.ITextSearchService2)
>    at Codist.NaviBar.NaviBarFactory+Overrider.FindNaviBar(System.Object, System.Windows.RoutedEventArgs)
>    at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
>    at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
>    at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
>    at System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs)
>    at System.Windows.BroadcastEventHelper.BroadcastEvent(System.Windows.DependencyObject, System.Windows.RoutedEvent)
>    at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(System.Object)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
>    at System.Windows.Threading.DispatcherOperation.InvokeImpl()
>    at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
>    at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
>    at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
>    at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
>    at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
>    at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
>    at System.Windows.Threading.DispatcherOperation.Invoke()
>    at System.Windows.Threading.Dispatcher.ProcessQueue()
>    at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
>    at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
>    at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
>    at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
>    at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)

It seems that Codist experienced a problem in its `Codist.NaviBar.MarkdownBar` type constructor.

**Comment by wmjordan** [comment]
Oh, I reused the tagged result from syntax highlighting.

If you have disabled syntax highlighting, but have the Navi Bar turned on, it definitely crashes VS.
I will look into it.

**Comment by MrClyfar** [comment]
Thank you for dealing with this so quickly. Much appreciated.

**Comment by wmjordan** [comment]
Good! Thank you for confirming this.
