### ISSUE TITLE
Keyboard shortcut to bring out definition search window with various scope in Navi Bar

### ISSUE THREAD

**Issue by wmjordan** [wmjordan/Codist#149]
As @fantasyz's suggestion in #67 

> I mean in the current build, I need to press the shortcut and use the mouse to click the buttons to toggle between Local and Project scope. I would like to eliminate the "mouse click". For example, this is what I would like to setup:
[Ctrl+M] to directly open the search declaration with local scope.
[Ctrl+Shift+M] to directly open the search declaration with project scope.

**Comment by wmjordan** [comment]
@fantasyz
Please try the new beta which has implemented this request.
Since VS 2019 has used [Ctrl+\`], the new version has changed the shortcut keys to [Ctrl+1,Ctrl+2] and [Ctrl+1,Ctrl+3]. You can customize them to suite your needs.
Furthermore, you can press the [-] or [=] key when your caret is placed in the member filtering text box to change the search scope. The tool tip for that text box has description about this too.

**Comment by fantasyz** [comment]
Works great.

**Comment by wmjordan** [comment]
Good.
