### ISSUE TITLE
Syntax style mismatch with text editor

### ISSUE THREAD

**Issue by T0uchM3** [wmjordan/Codist#152]
Some syntaxes are showing a gradient as a background effect but in their settings the background effect is set to Solid, is this normal? 
Example: C#: Volatile field, C#: Extern method...

**Comment by wmjordan** [comment]
![image](https://user-images.githubusercontent.com/12182730/109084247-63275100-7742-11eb-8733-9ea92f675f7c.png)

Typically the C#: Volatile field's setting should look like above.

**Comment by T0uchM3** [comment]
The problem was when I change the background effect to solid from gradient the syntax in the text editor doesn't change, been using a workaround by setting the background color the same as the editor's background.
I just went and checked on it now and it seems like it's working fine? probably I missed an update or something.
Ty for your time.

**Comment by wmjordan** [comment]
> when I change the background effect to solid from gradient the syntax in the text editor doesn't change

Perhaps there is another syntax style which has higher priority than the current one.


> a workaround by setting the background color the same as the editor's background

Please try to click the _Reset color_ command in the pop up menu of the _Background_ button. It shall remove the background color.
