### ISSUE TITLE
How to disable SyntaxHighlight from source code?

### ISSUE THREAD

**Issue by IneedHelp** [wmjordan/Codist#157]
Hello, I very much like your extension, but Syntax Highlighting is conflicting with other extensions I am using (such as Supercharger's magic comments) and I just want to remove it from the source code before compiling the extension.

Can you recommend what would be the best way of removing it?
Thank you in advance.

**Comment by wmjordan** [comment]
The syntax highlight results are reused in other part of Codist, for instance, the Scrollbar Marker, the content in Super Quick Info, the Symbol Marker in Smart Bar and, of course, the configuration dialog for the highlight feature. I suggest you leave it along and disable it in the Options dialog.

**Comment by IneedHelp** [comment]
_I suggest you leave it along and disable it in the Options dialog._
 
 Unfortunately just disabling it in the Options dialog doesn't prevent it from conflicting with other extensions (i.e. Supercharger), it's the first thing I've tried. Is there something that can be changed in the source of the extension to make Syntax Highlighting disabled or not to take effect on the VS text editor?

**Comment by wmjordan** [comment]
SuperCharge  is a closed-source thing and it is the thing which is not working.
I think you'd better ask the author of SuperCharger why its magic comments fail.
Or if you can provide an open-sourced project which also conflicts with Codist, I will love to take a look at it.

**Comment by wmjordan** [comment]
You can try excluding `CodeViewCreationListener.cs` which creates the Codist Syntax Highlight stuff from compilation and see whether it works for you.

**Comment by IneedHelp** [comment]
> You can try excluding CodeViewCreationListener.cs which creates the Codist Syntax Highlight stuff from compilation and see whether it works for you.

Unfortunately excluding `CodeViewCreationListener.cs` didn't help, the issue persists. Thank you for trying to assist me with this.
I really wanted to use Codist, but I can't compromise because Supercharger has some features I need more.

**Comment by wmjordan** [comment]
Try excluding classes with the attribute `[Export(typeof(EditorFormatDefinition))]`, if it does not work, try excluding members with attribute `[Export(typeof(ClassificationTypeDefinition))]`.

**Comment by IneedHelp** [comment]
I've removed all occurrences of both attributes and excluded CodeViewCreationListener.cs and it seems it's not conflicting with Supercharger anymore, thank you very much for the suggestions!

**Comment by wmjordan** [comment]
Could you take the trouble try adding those attributes back and see which one conflicts with SuperCharger?

**Comment by IneedHelp** [comment]
> Could you take the trouble adding those attributes back and see which one conflicts with SuperCharger?

`[Export(typeof(ClassificationTypeDefinition))]` is attribute that causes conflicts with Supercharger, the other one seems not to cause problems if it's enabled.

**Comment by wmjordan** [comment]
Thanks.
There are quite a few files which contains the above attribute.
Could you try which one contains the attribute that has conflict? You may first try excluding `CommentClassificationDefinitions.cs` first and including others. If it works, the conflict maybe in the comment definitions.

**Comment by wmjordan** [comment]
It seems that we have already tried this before!

I don't know what logic inside the SuperCharger which is so fragile against other extensions. I could not do anything about it.

**Comment by IneedHelp** [comment]
Yes, I have contacted you a long while ago with a similar issue when i was using VS 2017, now I am using VS 2019 and I was reinstalling all the extensions that I normally use, and the conflict between Codist and Supercharger showed up again. I personally do not mind because all I want from Codist is the Super Quick Info feature and the Scrollbar Markers are also nice, which still work fine after removing those attributes.

**Comment by wmjordan** [comment]
It is actually the same problem. :)
