### ISSUE TITLE
Codist conflicts with brace matching in VS

### ISSUE THREAD

**Issue by wmjordan** [wmjordan/Codist#161]
If Codist is enabled, the brace matching color would be reverted to the default one even if we have specify one in the Options dialog box.

**Comment by fitdev** [comment]
Glad you fixed braces matching issue in your latest build! This was driving me crazy sometimes... did not realize it was Codist's issue.

**Comment by wmjordan** [comment]
I noticed that the brace matching was not working, but had not realized that it was caused by Codist, until last night Stuart Fairful posted a question in the marketplace. We got to thank him.
