### ISSUE TITLE
Super Quick Info: wrong string color when it is parameter of an attribute

### ISSUE THREAD

**Issue by laicasaane** [wmjordan/Codist#166]
The strings should be blue, but they are dark red.

![image](https://user-images.githubusercontent.com/1594982/121698646-64656980-caf8-11eb-9068-98f29fe8a12f.png)

This is how they are supposed to be

![image](https://user-images.githubusercontent.com/1594982/121699124-dd64c100-caf8-11eb-814d-292942293cc2.png)

**Comment by wmjordan** [comment]
Please download the new beta.
