### ISSUE TITLE
Apply attribute style to the whole attribute not just its type name

### ISSUE THREAD

**Issue by fitdev** [wmjordan/Codist#17]
Great extension! Just one small issue though...

I have set attribute styles to use smaller font than the rest of the code (font = -4). It works fine for simple attributes like `[DebuggerStepThrough]`. 

However for attributes with options it does not work and looks something like this:
`[MethodImpl`**`(MethodImplOptions.AggressiveInlining),`**` DebuggerStepThrough]`
where the bolded text is rendered using normal (and not reduced font).

**Comment by wmjordan** [comment]
Can the following be the expected result?
![shot](https://user-images.githubusercontent.com/12182730/40755457-23260390-64b1-11e8-9262-c306be37b4ef.PNG)

**Comment by fitdev** [comment]
Yes! That looks great! I really appreciate the flexibility you are offering!

Also, although a separate issue, it is similar enough so I will mention it here as well... Currently, XML Doc comments also behave similar to attributes: 

`/// <param name="`**arg**`">description</param>`

Where the actual parameter and type / member names are styled differently than the rest of the XML Doc comment. I think that at least font size should be adjusted, maybe also the opacity level as well. Other differences like font style and color could be kept, so that they can stand out from the rest of the comment text.

**Comment by wmjordan** [comment]
Thank you for the appreciation.
The XML Doc issue is somewhat tougher than the attribute annotations, which may require reconstructing some code logic. I will try fix it as well.

**Comment by wmjordan** [comment]
After some attempts, it appeared to be working.

![shot](https://user-images.githubusercontent.com/12182730/40779118-4c2fa214-6506-11e8-9edc-75c026eac5df.PNG)
