### ISSUE TITLE
VB projects sharing symbol with C# projects in the same solution could crash VS

### ISSUE THREAD

**Issue by wmjordan** [wmjordan/Codist#171]
Reproduction:

1. A solution contains both VB and C# projects
2. Execute the Find Referrers command in Codist
3. If the symbol is referenced in any VB project, VS crashes.

**Comment by fitdev** [comment]
I confirm. This issue is exactly what happened to me, as I explained in #169

**Comment by wmjordan** [comment]
Thank you very much for the confirmation!
Then the new beta should have fix your problem.

**Comment by fitdev** [comment]
Yes, the latest beta seems to have fixed it. I now just get the list of referrers, which is empty in my case (but I know that VB is not supported, so that's ok :) Thank you for your great work!
