### ISSUE TITLE
C# 10 Support

### ISSUE THREAD

**Issue by fitdev** [wmjordan/Codist#172]
C# 10 introduces a new syntax for file-scoped namespace declarations like this:

```cs
namespace A;
class B { }
```

instead of the usual:

```cs
namespace A {
  class B { }
}
```

This does not work in NaviBar at the moment: Codist shows the containing type as being in the global scope (without any containing namespace(s)).

Perhaps you can just slightly modify code so that it gets namespace information directly from the type (class, struct, interface, enum, delegate) within which the cursor is positioned?

**Comment by wmjordan** [comment]
This is a little bit complicated.
Previously accessing the parent node of the type is sufficient to get the containing types and namespaces. Fast and neat.
Now we have to walk through the nodes at the top level.

**Comment by fitdev** [comment]
Oh. I thought that once you have the containing type symbol, you can simply access its Namespace property and get Namespace info that way without actually parsing the whole file/document.

**Comment by wmjordan** [comment]
I will take a look at this and see whether it is possible to implement it when fixing #173.

**Comment by fitdev** [comment]
I should also add another request for C# 10 feature: record structs. Currently these are colorized as classes. Please add support for colorizing record structs as other structs (along with their `{ }` braces).

**Comment by wmjordan** [comment]
Please test the new beta and post your feedbacks.
