### ISSUE TITLE
Suggestion: Colored underlines in syntax highlighting

### ISSUE THREAD

**Issue by Decimation** [wmjordan/Codist#175]
Currently, underlines follow the same color as the foreground color. It would be very nice if underlines could have separate colors.

For example, ReSharper Heap Allocations Viewer adds underlines that indicate where memory allocations occur:
![image](https://user-images.githubusercontent.com/4624891/135702967-5ecabdcd-0ac8-4f70-927e-ffa599e30d6e.png)

Here is an example of how the settings could appear:
![mockup](https://user-images.githubusercontent.com/4624891/135703565-c4a17d5d-897f-438d-95d7-ad435db6d38b.png)

**Comment by wmjordan** [comment]
Thank you for suggesting this feature.
I thought of that before. But it seemed to me that WPF underline text decoration did not allow specifying the color of it.
Maybe there's some other way to achieve this.
I like it.
Please keep an eye on the upcoming release in #169, if I manage to find a way.

**Comment by Decimation** [comment]
> 
> 
> Thank you for suggesting this feature. I thought of that before. But it seemed to me that WPF underline text decoration did not allow specifying the color of it. Maybe there's some other way to achieve this. I like it. Please keep an eye on the upcoming release in #169, if I manage to find a way.

If it's any help, you can view the source of ReSharper Heap Allocations Viewer [here](https://github.com/controlflow/resharper-heapview) and the ReSharper SDK [here](https://github.com/JetBrains/resharper-rider-plugin).

**Comment by wmjordan** [comment]
Thank you for taking time providing the links.
I checked the WPF API. My previous reply was incorrect.
There is no problem technically. Its underline decoration does support colors, and much more!

The only problem was that I didn't have time when I thought of that.
And my time will still be scarce recently.

**Comment by Decimation** [comment]
Any updates to this, @wmjordan? Thank you for the great extension!

**Comment by wmjordan** [comment]
Hi, nice to hear from you.
I am quite in favor of your suggestion. I've just fixed quite a few bugs in Codist and released a new version. Now I am going to work on your request.

**Comment by Decimation** [comment]
> Hi, nice to hear from you. I am quite in favor of your suggestion. I've just fixed quite a few bugs in Codist and released a new version. Now I am going to work on your request.

Thank you very much, and happy new year! I look forward to beta testing this feature.

**Comment by wmjordan** [comment]
Hey, there is a new beta version which has implemented your requested feature. Please help test it.

**Comment by Decimation** [comment]
> Hey, there is a new beta version which has implemented your requested feature. Please help test it.

I just tried it out, and it's working great!

![image](https://user-images.githubusercontent.com/4624891/149873552-0980ae56-5248-47f7-832e-7fdd7e0b050b.png)

![image](https://user-images.githubusercontent.com/4624891/149873566-2423012c-df78-496f-884d-587116635b44.png)

If it's not too much to ask, would it also be possible to further customize the underline? JetBrains Rider allows the following underline types:

![image](https://user-images.githubusercontent.com/4624891/149873314-232b119c-bae3-4f3b-89e7-c9e46f6bd647.png)

Examples:

*Underwaved*

![image](https://user-images.githubusercontent.com/4624891/149873351-4c8b62f9-834f-494a-87ba-cc8cc90c12a8.png)

*Dotted Line*

![image](https://user-images.githubusercontent.com/4624891/149873397-97dadd51-fae7-4835-8a4e-965481949c57.png)

Changing the width of the underline could also be a nice feature.

**Comment by wmjordan** [comment]
Yes, I thought about lines styles.
Dotted or dashed lines are easy.

However, I am not good at WPF.
I don't know how to draw a wavy line.

**Comment by Decimation** [comment]
> Yes, I thought about lines styles. Dotted or dashed lines are easy.
> 
> However, I am not good at WPF. I don't know how to draw a wavy line.

That's fine. Line width should be easy too, right?

**Comment by wmjordan** [comment]
Yep. It is easy too. :)

**Comment by wmjordan** [comment]
After hours' attempt, I still could not find a good way to draw wavy line.
I will work on the customization of line thickness and dashes later.

**Comment by Decimation** [comment]
That's fine; I appreciate your effort trying. How are the underlines implemented? Is it a font customization control?

**Comment by wmjordan** [comment]
No extra control is needed.
If it does, I will decline you since it hurts performance a lot.
The underlines are drawn via WPF `Brush`es.
Thus, technically it is even possible to have animations in the editor!

**Comment by Decimation** [comment]
> No extra control is needed.
> If it does, I will decline you since it hurts performance a lot.
> The underlines are drawn via WPF `Brush`es.
> Thus, technically it is even possible to have animations in the editor!

So it's also easy to add width/height configuration? I just skimmed through this [documentation](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/graphics-multimedia/wpf-brushes-overview?view=netframeworkdesktop-4.8#common-brush-features).

**Comment by wmjordan** [comment]
There's a new beta which adds line thickness, line offset, line style configurations.

**Comment by Decimation** [comment]
It's working perfectly. Thank you very much for implementing this feature!
