### ISSUE TITLE
Suggestion: add option to show return type of all members on NaviBar

### ISSUE THREAD

**Issue by laicasaane** [wmjordan/Codist#177]
It would be more useful (at least to me) to quickly know the return type of all members (fields, properties, methods) instead of having to rely on the tooltip when hover over a member entry. Ideally, the return type should be displayed on the right side of the NaviBar, where the initial value is shown atm.

**Comment by wmjordan** [comment]
The implementation may look like the following. Is it what you want to have?

![image](https://user-images.githubusercontent.com/12182730/137862665-9e81ead6-6cab-490d-9bac-4b4057f439e6.png)

**Comment by wmjordan** [comment]
Hi, there's a new version which shows type names in the NaviBar drop-downs even when implicit object creation syntax is used.
Please help test it.

**Comment by wmjordan** [comment]
Here's a screenshot:

**Comment by wmjordan** [comment]
Here's a screenshot:
![image](https://user-images.githubusercontent.com/12182730/146727501-c4d8d7a8-fef3-4241-ad8f-70e5af7cb22f.png)

**Comment by laicasaane** [comment]
Thank you!
