### ISSUE TITLE
version 2.9.2.1101 has a problem with super quick info

### ISSUE THREAD

**Issue by ricardomarquesme** [wmjordan/Codist#18]
the stack:

    <record>1090</record>
    <time>2018/05/30 13:58:26.724</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.AggregateException: One or more errors occurred. ---&gt; System.NullReferenceException: Object reference not set to an instance of an object.&#x000D;&#x000A;   at Codist.QuickInfo.CSharpQuickInfoSourceProvider.CSharpQuickInfo.AugmentQuickInfoSession(IQuickInfoSession session, IList`1 qiContent, ITrackingSpan&amp; applicableToSpan) in E:\Codes\Open Source Projects\Codist\Codist\QuickInfo\CSharpQuickInfoSourceProvider.cs:line 181&#x000D;&#x000A;   at Microsoft.VisualStudio.Language.Intellisense.Implementation.LegacyQuickInfoSource.AugmentQuickInfoSession(IAsyncQuickInfoSession session, IList`1 content, ITrackingSpan&amp; applicableToSpan)&#x000D;&#x000A;   at Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoSession.&lt;TryComputeContentFromLegacySourceAsync&gt;d__45.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoSession.&lt;ComputeSourceContentAsync&gt;d__44.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)&#x000D;&#x000A;   --- End of inner exception stack trace ---&#x000D;&#x000A;---&gt; (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.&#x000D;&#x000A;   at Codist.QuickInfo.CSharpQuickInfoSourceProvider.CSharpQuickInfo.AugmentQuickInfoSession(IQuickInfoSession session, IList`1 qiContent, ITrackingSpan&amp; applicableToSpan) in E:\Codes\Open Source Projects\Codist\Codist\QuickInfo\CSharpQuickInfoSourceProvider.cs:line 181&#x000D;&#x000A;   at Microsoft.VisualStudio.Language.Intellisense.Implementation.LegacyQuickInfoSource.AugmentQuickInfoSession(IAsyncQuickInfoSession session, IList`1 content, ITrackingSpan&amp; applicableToSpan)&#x000D;&#x000A;   at Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoSession.&lt;TryComputeContentFromLegacySourceAsync&gt;d__45.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoSession.&lt;ComputeSourceContentAsync&gt;d__44.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)&lt;---&#x000D;&#x000A;</description>

**Comment by wmjordan** [comment]
Thank you very much for reporting this issue!
I'll fix it in the upcoming version 3.0, which has already been alpha tested for a couple of days and will be released soon.
At this time, please try selecting the following options to prevent the error from occurring.

![shot](https://user-images.githubusercontent.com/12182730/40754322-550bde9e-64ab-11e8-8cd3-31ed34f87b70.PNG)
