### ISSUE TITLE
[bug] lost color when close a multi-opened code file.

### ISSUE THREAD

**Issue by fantasyz** [wmjordan/Codist#180]
Hi, I guess the logic incorrectly assumed that there is always only one tab for a source file opened. In reality, it is not uncommon that people may open two tabs for the same code file to observe different sections at the same time.

Here is how to reproduce the issue. 

1. Open any source file.
2. On VS top menu, choose [Window] [New Window]. This will open another tab for the current source file.
3. Close anyone of them.

Observe that the remaining one will lose the Codist syntax color scheme and reverted back to VS default color scheme.

Regards

**Comment by wmjordan** [comment]
BUG verified. Thanks.

**Comment by fantasyz** [comment]
wow
You are so responsive.

**Comment by wmjordan** [comment]
Just happened to see your issue :)

**Comment by wmjordan** [comment]
Please test the new beta.
