### ISSUE TITLE
Codist 6.0 Beta Version (C# 10 support, Auto Version Numbers)

### ISSUE THREAD

**Issue by wmjordan** [wmjordan/Codist#181]
## Download
[Codist 7090](https://github.com/wmjordan/Codist/files/7869177/Codist.zip)

[Codist 7082](https://github.com/wmjordan/Codist/files/7832993/Codist.zip)
[Codist 7052](https://github.com/wmjordan/Codist/files/7784016/Codist.zip)
[Codist 7050](https://github.com/wmjordan/Codist/files/7782666/Codist.zip)
[Codist 7045](https://github.com/wmjordan/Codist/files/7775850/Codist.zip)
[Codist 7042](https://github.com/wmjordan/Codist/files/7743582/Codist.zip)
[Codist 7038](https://github.com/wmjordan/Codist/files/7743202/Codist.zip)
[Codist 7032](https://github.com/wmjordan/Codist/files/7710111/Codist.zip)
[Codist 7012](https://github.com/wmjordan/Codist/files/7666377/Codist.zip)
[Codist 6995](https://github.com/wmjordan/Codist/files/7647195/Codist.zip)
[Codist 6967](https://github.com/wmjordan/Codist/files/7632153/Codist.zip)
[Codist 6964](https://github.com/wmjordan/Codist/files/7630651/Codist.zip)
[Codist 6949](https://github.com/wmjordan/Codist/files/7611410/Codist.zip)
[Codist 6943](https://github.com/wmjordan/Codist/files/7608605/Codist.zip)

## Please Help Do A Good Deed
My mother permanently left me last week on Nov, 19th. I felt very sad.
I am trying my best to recover from it and will do as much good deeds as possible.

I am asking you, my friends, **once you've downloaded this beta version, please do a good deed to people around you**.

   - You can share your money or goods with someone who is in need--don't donate to me, however.
   - You can have a good time with your parents, if you haven't done that for a long time. At least make a phone call or ask about their health.
   - You can share your knowledge with someone who is less skilled than you to help him/her live an easier life.
   - Or any other things that make someone else better.

Every good deeds you make will benefit my mothers' spirit and help her to reach the Nirvana. The more good deeds you do, the better you help.

## What's New
The new function introduced in this version is the ability to automatically change assembly version numbers before each build. To customize the version numbers, right click a Project node in the Solution Explorer and select the _Auto Build Version Settings..._ command.

<img width="265" alt="image" src="https://user-images.githubusercontent.com/12182730/144691934-27360deb-c896-473b-89ab-8d0dd61a3ed4.png">

Change the settings and press _Save_ button in the dialog.

<img width="440" alt="image" src="https://user-images.githubusercontent.com/12182730/144691988-94647e2a-c885-49b0-9402-063223a0068a.png">

- [x] General
   - [x] Added #172  (6943, 6964)
   - [x] Some crashes were fixed (6943)
   - [x] Added event trigger filter to C# Symbol List
   - [x] Made symbol on C# symbol list clickable
   - [x] #183 (7042)
- [x] Auto Build Version
   - [x] Automatically change assembly version numbers before each build (6995, 7004, 7082)
- [x] Highlight
   - [x] #180 (6949)
   - [x] #182 (6967)
   - [x] Fixed wrong syntax highlight color for the Number classification type
   - [x] Updated Dark Pale syntax style (7045)
- [x] NaviBar
   - [x] Root namespace menu were empty after items being clicked (6943)
   - [x] #177 (7038)
   - [x] #187 (7082)
- [x] Smart Bar
   - [x] Added Wrap Text function to surround selected text (6943)
- [x] Quick Info
   - [x] Fixed a crash in C# Quick Info context menu
   - [x] #185 (~7045~, 7090)
   - [x] #186 (7050, 7052)
   - [x] Alias declaration did not have proper Quick Info (7090)

**Comment by fitdev** [comment]
So sorry to hear about your mother's passing. Please accept my sincere condolences. And what a wonderful thing you wrote about doing good things and spending time with the people close to you while you can! I wish you to encounter many people in your life who will do good deeds to you as well!

The new beta version works great! The namespaces on the NaviBar work well, which is awesome as not having this feature prevented me from moving to the C# 10 new namespace declaration style. The colorization of record structs has improved - now both `{ }` are properly colorized, however the struct's name is still colorized the same way as a class.

**Comment by wmjordan** [comment]
@fitdev Thank you for your kind condolences. I've just fixed the color of `record struct`.
@fantasyz Please try the new beta which has addressed the issue of broken highlight after closing a duplicated document window.

**Comment by fitdev** [comment]
Wow! You are so fast! Yes, the latest beta fixed the record struct colorization, thank you!

However, I thought I would mention another small issue, which has been with Codist for a while... Interface colorization:

![2021-11-26 16_56_35-DotNet - LicenseProvider svcs cs_](https://user-images.githubusercontent.com/8166847/143674413-2ce5fea9-4785-45fa-b75f-8bb12c566981.jpg)

On the screenshot above `ILicenseProvider` should be highlighted the same as `IAppService`, but instead it is being highlighted as an _abstract member_, even though it is not a member, but a type.

**Comment by wmjordan** [comment]
It is a mystery in VS 2022 that the highlights have different precedence than prior versions.
I tried a few ways to fix that, however, none of them worked.

**Comment by fitdev** [comment]
It's ok. It's not too important. There are actually a few other minor issues with highlights, but they are low priority, but perhaps I should mention them anyways:

- I noticed that after I upgrade VS to a newer preview or install a new extension or a new extension version, VS would switch to VS 2019 color scheme (the Options > Text Editor > C# > Advanced > Editor Color Scheme) from my preferred VS 2017 color scheme. This also screws up Codist highlights. So the way I fix this is I switch the option to VS 2019 color scheme (which was still on VS 2017), click OK. Then I switch back to VS 2017 color scheme, click OK. Then I restart VS and the everything is back to normal.
- Another minor issue is after initial solution loading, when VS restores document tabs, on those open (visible) tabs syntax highlighting maybe somewhat wrong. For example, it would not correctly determine that a given symbol is a user symbol and so should be highlighted differently. I guess it's some kind of loading / caching issue. The easy fix is to close and reopen the tab, then everything works.

Again, these are minor issues, so don't worry too much about them. These are just for your information, in case you are not aware of these.

**Comment by wmjordan** [comment]
Thank you for reporting these two issues.
1. I have not used VS 2017 scheme, thus I have no idea about that.
2. You don't need to close the document when it is restored. Type something and the highlight will be corrected. I have noticed this since I addressed the issue about the performance of highlighting (#165), and tried my best. At least 30 builds had been attempted simply to fix this issue, but none of them worked. I gave up then.

**Comment by wmjordan** [comment]
Thank you for reporting these two issues.
1. I have not used VS 2017 scheme, thus I have no idea about that.
2. You don't need to close the document when it is restored. Type something and the highlight will be corrected. I have noticed this since I addressed the issue about the performance of highlighting (#165), and tried my best. At least 30 builds had been attempted simply to fix this issue, but none of them worked. I gave up then.

**Comment by fitdev** [comment]
I noticed that the latest beta would sometimes get confused on the NaviBar and display namespace hierarchy multiple times:
`{} A   {} B   {} C   {} A   {} B   {} C   {} A   {} B   {} C` instead of just `{} A   {} B   {} C`. Sometimes it would repeat once, sometimes many times (so that it does not fit). I have not yet determined the exact conditions when it happens, but it does go away if you change the code a bit, or move the cursor into a different scope. However it happens even with the perfectly valid C# files.

**Comment by wmjordan** [comment]
> I noticed that the latest beta would sometimes get confused on the NaviBar and display namespace hierarchy multiple times:
> `{} A {} B {} C {} A {} B {} C {} A {} B {} C`

That's weird. I never experienced this.
Please help make reproduction steps when ever you can, so I can address it.

**Comment by fitdev** [comment]
I will try to take notice when it happens. But it's not a big deal. It is rare and quickly goes away, once I change the scope, or add some code.

**Comment by fitdev** [comment]
I am pretty sure the duplicate / repeating namespace issue happens only in C# files that have been converted to use C# 10's file-scoped namespaces, as I have never seen it in classic `namespace A { ... }` files, only in `namespace A;` new-style files.

**Comment by wmjordan** [comment]
> I am pretty sure the duplicate / repeating namespace issue happens only in C# files that have been converted to use C# 10's file-scoped namespaces, as I have never seen it in classic `namespace A { ... }` files, only in `namespace A;` new-style files.

Bug comfirmed.

**Comment by wmjordan** [comment]
@fitdev Please test the new beta which should have fixed the redundant namespace nodes.

**Comment by fitdev** [comment]
Thank you for the new beta! I will test it and let you know if I encounter this issue again.

**Comment by wmjordan** [comment]
Hi friends, previously I used [Automatic Versions](https://marketplace.visualstudio.com/items?itemName=PrecisionInfinity.AutomaticVersions) to update assembly version numbers.

However, it has not yet support VS 2022. Thus I spent a day to add the similar feature into Codist.
Could you help test it?

**Comment by fitdev** [comment]
- Unfortunately I will not be able to help here, as I control assembly version number explicitly through MSBuild. Also, just a thought - DotNetCore/SDK-based projects need not have `AssemblyInfo.cs`, so does your extension support still work in this scenario too?
- As for file-scoped namespaces and NaviBar - everything seems to be working well now since your last fix. Thank you!

**Comment by wmjordan** [comment]
> * DotNetCore/SDK-based projects need not have `AssemblyInfo.cs`, so does your extension support still work in this scenario too?

Yes, it does update the `Version` and `FileVersion` elements automatically in the csproj files.

**Comment by fitdev** [comment]
> Could you share how the numbers are updated via MSBuild?

Sorry did not see that. In my case it's kind of complex, and so is unlikely to be usable with this feature. Basically the versions would be dynamically determined from several MSBuild variables that come from different .targets files, and then combined together to produce a concrete version element. Given such a use case, I don't think this feature would apply.

**Comment by wmjordan** [comment]
Thanks for your explanation. Your situations are really complicated.

**Comment by wmjordan** [comment]
My friends, happy new year!
Hope you and your family members are doing great and always away from the terrible COVID-19.

I am going to release this version as version 6 in the recent future and I will work on some features requested by you previously. Please help by downloading the latest test version and see whether it works good on your computer.

**Comment by fitdev** [comment]
Thank you for all your hard work! Likewise I hope 2022 will be a much better year for you!
I have been using build 7052 for some time and it works great, even with the latest VS 2022 17.1 Preview 2.
Looking forward to using new versions of Codist! You've made a truly awesome extension!

**Comment by wmjordan** [comment]
> * Another minor issue is after initial solution loading, when VS restores document tabs, on those open (visible) tabs syntax highlighting maybe somewhat wrong. For example, it would not correctly determine that a given symbol is a user symbol and so should be highlighted differently. I guess it's some kind of loading / caching issue. The easy fix is to close and reopen the tab, then everything works.

I opened an issue (#188) for this problem. I will take a look into it again when I have time.
