### ISSUE TITLE
Font size "0" does not work correctly on some syntax elements

### ISSUE THREAD

**Issue by Phloog** [wmjordan/Codist#182]
When setting font size to 0 for "C# Member declaration", the font size seems to be inherited from some element not visible in the list. See first screenshot: The font size is pretty big with font size "0". 

![2021-12-01 07_51_13-Window](https://user-images.githubusercontent.com/2299409/144186419-7a5c0ab0-f64f-4c54-a451-24c7bcc3d1ab.png)

When setting to "1" (second screenshot), the size appears as expected (one step bigger than the default font):

![2021-12-01 07_52_08-Window](https://user-images.githubusercontent.com/2299409/144186448-12b900ec-5d91-4e28-b991-74f13b129759.png)

Other relative sizes (-1, 2, ...) also work as expected. Only the default setting "0" enlarges the font as shown above.

edit: VS 2022, newest codist version

**Comment by Phloog** [comment]
Okay, I'll try that, thanks. And sorry for touching a sore spot  ;-)

**Comment by wmjordan** [comment]
It is really confusing, not fully related to #14.
Please try the new beta which has disabled the behavior of font-size inheritance.

**Comment by Phloog** [comment]
I'll do that, but fyi the VS restart really did help 👍

**Comment by wmjordan** [comment]
This issue should have been perfectly fixed in version 7.2 (#248).

**Comment by Phloog** [comment]
Thanks for your tenacity in this! I'll check it and give you more info IF the problem persists.
