### ISSUE TITLE
Add option to change the background color of Super Quick Info panel

### ISSUE THREAD

**Issue by laicasaane** [wmjordan/Codist#186]
Some of my highlighting colors become a bit hard to read on the current background (in dark mode), so I really need it to be darker. A customizable option for this would be better than an arbitrary color.

**Comment by wmjordan** [comment]
There's no open API to support this. Thus another WPF hack is required. I also thought of this several days ago.

**Comment by wmjordan** [comment]
![image](https://user-images.githubusercontent.com/12182730/147517106-f597f661-7540-4dc7-96b6-50e01c04c0fe.png)

**Comment by wmjordan** [comment]
There's a new version which adds that option you mentioned.

**Comment by laicasaane** [comment]
Thank you, I'll test it soon.

**Comment by laicasaane** [comment]
It works well. 👍🏽

**Comment by wmjordan** [comment]
I just found that it did not correctly load the option value after restarting VS.
Please download the last beta which was just released and fixed this problem.

**Comment by laicasaane** [comment]
Yeah, I see it doesn't show up on the options window, but it does apply correct color to the panel.
