### ISSUE TITLE
Advanced Syntax Highlight was not applied to the document after solution restoration

### ISSUE THREAD

**Issue by wmjordan** [wmjordan/Codist#188]
Workaround:
Make an edit (optionally undo your operation) then the highlight will be applied.

**Comment by wmjordan** [comment]
OMG, this issue gets more critical in VS 17.2 preview.

**Comment by wmjordan** [comment]
@fitdev
There's a new version that addresses this problem.

It seems to working fine on my computer.
Please help test it on your side and see whether it works as well.

**Comment by fitdev** [comment]
Thank you for letting me know. I will test it soon. Though I have not noticed this myself. The only time highlights were not applied was after solution has just loaded, but switching to other document tabs, or editing document in the first tab makes highlights work correctly, and then I no longer see the issue. So in my case, as far as I remember, it only did not work the first time - after initial solution load.
