### ISSUE TITLE
Suggestion: the automatic build version lacks one useful format option

### ISSUE THREAD

**Issue by FabienF-Alten** [wmjordan/Codist#189]
Hello, the automatic build version feature is a great addition.
There's one format that's missing though: the "seconds from midnight"/2 that's used in the righ-most wildcard in Microsoft's `1.0.*.*` automatic versionning.
As it's become flaky to use wildcards in .csproj files over the last years, using your feature to enforce it looks like a better solution, but requires to have it available in the dropdowns.

Here's a copy-paste of how Microsoft handles it:
_In the real world, version numbers mean different things to different people. However, I tend to use Microsoft’s definition for Major and Minor when using Visual Studio and MSBuild. On the contrary, Visual Studio’s automatic assignment for Build and Revision defines Build as the number of days since January 1, 2000, and Revision as the number seconds **(divided by two)** into the day on which the compilation was performed. The number of seconds must be divided by two since there are 86,400 seconds in a day, and the maximum value of the Revision number is 65534 (yes, not 65535, which causes an error)._

**Comment by wmjordan** [comment]
The `*` automatic version format does not seem to be the recommended form. VS warns about that.

The setting "DaySinceY2K" = "number of days since January 1, 2000".
And the new test version has added a `MidNightSecond` which denotes "the number seconds (divided by two) into the day on which the compilation was performed"

**Comment by FabienF-Alten** [comment]
> The `*` automatic version format does not seem to be the recommended form. VS warns about that.

Indeed, I was aware of it, but this format has been for company-wide version management at my work, and using one that makes more sense would break too much stuff :/
Thank you for the warning anyways. I do find the other formats you already implemented more reliable and human-readable, and will definitely use them in my future projects.

> The setting "DaySinceY2K" = "number of days since January 1, 2000". And the new test version has added a `MidNightSecond` which denotes "the number seconds (divided by two) into the day on which the compilation was performed"

Thank you for that. Now I can remove the dirty hacks I had to do to work around MS's recent mess :)

**Comment by wmjordan** [comment]
Thank you for the explanation of your situation.

If you are to coordinate version numbers across your company. Please be aware that Codist saves the version format configuration file named _PROJECT_NAME.autoversion.json_ within the _obj_ folder, which is usually out of version control.
