### ISSUE TITLE
Suggestion: Advanced syntax highlighting - qualified types

### ISSUE THREAD

**Issue by Decimation** [wmjordan/Codist#191]
A useful addition to syntax highlighting would be the option to customize highlighting for qualified types to distinguish them from non-qualified types; i.e., 

- `ref struct`
- `readonly struct`
- `ref readonly struct`
- `static class`
- `sealed class`
- `...`

---

Current settings:

![devenv_PjgIseIVqO](https://user-images.githubusercontent.com/4624891/154150257-83d4a321-77e9-44bf-afad-45e8dc483e91.png)

Result:

![devenv_riHiDHzB9Q](https://user-images.githubusercontent.com/4624891/154147634-dd46286a-72e7-4114-b03a-18b35500ccee.png)

---

Here is an example of how the settings could look:

![devenv_PjgIseIVqO](https://user-images.githubusercontent.com/4624891/154150042-defb3f3f-c305-4306-82b6-09d01d9f853c.png)

Result:

![devenv_LWuxinjdZQ](https://user-images.githubusercontent.com/4624891/154149998-8292df2f-c2c2-4eb4-bf45-377490f78458.png)

**Comment by wmjordan** [comment]
Hi, please try the new beta which has added style for readonly struct.

**Comment by wmjordan** [comment]
Any comment?
I am going to close this issue and release the new version.

**Comment by Decimation** [comment]
> Any comment? I am going to close this issue and release the new version.

Apologies for not responding! It doesn't seem to be cooperating with ReSharper's syntax highlighting (Codist syntax highlighting has always worked alongside ReSharper for me).

![devenv_Mlkfv2rJ4J](https://user-images.githubusercontent.com/4624891/161791056-185b0d2d-283e-4961-8993-858ad43cf1ed.png)

**Comment by wmjordan** [comment]
> The syntax color highlighting doesn't seem to be cooperating with ReSharper's syntax highlighting

I am sorry that I can not guarantee that.

> is it possible to add syntax highlighting for other types

Hmm, it is reasonable to add support to `ref` structs too.
The `static` and `sealed` symbol support has already been implemented for very long time.
I have no plan to specialize them to class names.

**Comment by wmjordan** [comment]
I am going to implement the `ref` support like the following (By default no style is defined for `ref struct`, you've got to set the style yourself).

<img width="654" alt="image" src="https://user-images.githubusercontent.com/12182730/161885454-645b6ff4-7bc0-49df-b429-1a4ecf62383c.png">

**Comment by Decimation** [comment]
ReSharper and Codist syntax highlighting/customization cooperate with each other in nearly every case except for a few I've seen: `C#: Sealed class or member`, `C#: Read-only struct`. The only thing that doesn't work in those cases is foreground color; everything else works fine, though.

This isn't a huge issue for me, though.

![devenv_Yd8eyBB3Sh](https://user-images.githubusercontent.com/4624891/161950027-768264f6-92bf-4bd3-b91a-2664b7c73aaf.png)

> I am going to implement the `ref` support like the following (By default no style is defined for `ref struct`, you've got to set the style yourself).

Great, I'll check it out when you have a build ready.

**Comment by wmjordan** [comment]
Please test the new beta.

**Comment by Decimation** [comment]
Everything is working perfectly. Thank you!

**Comment by wmjordan** [comment]
Thank you for your feedback.
I will release the new version soon.
