### ISSUE TITLE
Usage Super Quick Info disables documented code tooltips in typescript modules

### ISSUE THREAD

**Issue by aes2000** [wmjordan/Codist#193]
Hello!

I have a solution that consist of two types of projects: c# and typescript.

When I use Super Quick Info documented code tooltips in typescript modules, typed as `/** Class description */`, are disabled.

Can you add an option to disable Super Quick Info for the .ts/.tsx or .js/.jsx files?

**Comment by wmjordan** [comment]
That's weird. Super Quick Info are supposed to work with C# documentations and not affecting ts or js files.
Could you provide me some screenshots about how they are affected and what it should look (pressing Ctrl key will temporarily disable the Super Quick Info)?

**Comment by aes2000** [comment]
Without Super Quick Info:
![изображение](https://user-images.githubusercontent.com/4943424/156321961-cf97e5d4-45d8-4d78-af21-6663004d0417.png)

With Super Quick Info:
![изображение](https://user-images.githubusercontent.com/4943424/156322058-8f10257d-a04d-4914-897e-d41cb8cc7848.png)

As you can see the method summary is absent in the second screenshot

**Comment by aes2000** [comment]
I tested, it works as expected now. Thanks!
