### ISSUE TITLE
[Suggestion] Add support for additional font customization: Specifying font variations

### ISSUE THREAD

**Issue by Decimation** [wmjordan/Codist#195]
Regarding font customization:

- Right now the following font properties can be used:
  - _Bold_
  - _Italic_
  - _Strikethrough_
  - _Underline_
- Addditionally, _size_ and _stretch_ can be configured

---

However, the fonts usually have additional variations as seen below for *Roboto Mono*:

![explorer_7RDpudsdQx](https://user-images.githubusercontent.com/4624891/163139513-7f0b0c74-968e-41e5-acd5-4137c6af705d.png)

I suggest adding a feature to support specifying a style/variation of the font rather than just the font family itself:

![devenv_W5iklpUyMR](https://user-images.githubusercontent.com/4624891/163140119-172e2253-63a3-42b3-b2f8-f3563b2667dc.png)

For example, a dropdown menu can be added to select the variation of the font.

**Comment by wmjordan** [comment]
Actually I had the same idea as yours while I was adding the font-stretch support. However, I could not figure out how to get and set font style variations via WPF.

If you have any idea, please show me some information, or even better, source code :)

**Comment by Decimation** [comment]
Are you able to use the font file directly? e.g.,
`C:\...\robotomono_light`

I haven't looked into possible solutions yet, but that is my immediate thought. Thanks for the quick response!

**Comment by wmjordan** [comment]
No. I could not access the font file directory.
In WPF, the game does not play like that.

**Comment by Decimation** [comment]
> No. I could not access the font file directory.
> In WPF, the game does not play like that.

Is that because of insufficient permissions or a limitation of WPF? Can you prompt the user for the font file?

Either way, I'll do some research of my own.

**Comment by wmjordan** [comment]
Perhaps, it is the limitation of WPF. I am not a master of WPF thus I can not comment too much.

**Comment by wmjordan** [comment]
Please download the new beta.
<img width="413" alt="image" src="https://user-images.githubusercontent.com/12182730/217836928-8e21cce7-b225-4b00-ad97-d9f9b8d717db.png">
