### ISSUE TITLE
Suggestion: Display #Regions in the NaviBar

### ISSUE THREAD

**Issue by fitdev** [wmjordan/Codist#196]
It would be useful to display `#region`s in the horizontal (non-dropped-down), main part of the NaviBar too.
- Perhaps only regions within namespace or type should be shown (i.e. regions within members should not, or they should respect the existing option about the drop-downs).
- Because their names/titles may potentially be long, they may be trimmed to say 1 or 2 words or 20 characters or something like this.

**Comment by wmjordan** [comment]
They are already there. What are you expecting?

<img width="488" alt="image" src="https://user-images.githubusercontent.com/12182730/163766894-af30b3fd-b021-4bd8-96d9-753d81a7c255.png">

**Comment by fitdev** [comment]
Wow! That was a very quick response! Yes, that's exactly what I would like to see but for some reason they do not work for me in the latest version.

![regions1](https://user-images.githubusercontent.com/8166847/163767550-038af32a-c749-49cf-8667-e62a1ee0503d.jpg)
![2022-04-18 09_46_28-Options](https://user-images.githubusercontent.com/8166847/163767566-79e561d7-1aa8-46f5-8bb9-3e41164000cf.jpg)
[Config.json.zip](https://github.com/wmjordan/Codist/files/8504073/Config.json.zip)

**Comment by wmjordan** [comment]
Could it because you are using C# 10?
Could you take the trouble to change the namespace declaration to the old-scroll one which uses curvy braces and see whether it works?

**Comment by wmjordan** [comment]
> That was a very quick response!

I am in China and it is 3pm now. When's your time?

**Comment by fitdev** [comment]
> Could it because you are using C# 10?

Perhaps. In fact I am using VS 2022 17.2 Preview 3, and langversion = preview (so it's more like C# 10+).

Reverting namespace to the old `{...}` style did _not_ help.

> I am in China and it is 3pm now. When's your time?

Oh I see. I am in Europe, so its morning here.

**Comment by wmjordan** [comment]
Well, I found the reason.

I saw that there was no outline boxes next to the line numbers on your screenshot.
The NaviBar reuses the document outline results. If you turn the outline off, `#region`s won't show up on the NaviBar.

**Comment by fitdev** [comment]
But it _does show_ in the _drop-down_!

I have these outlining settings:

![2022-04-18 10_44_17-Options](https://user-images.githubusercontent.com/8166847/163774987-bd45d0d5-6af5-491f-b3ff-02d62617a82d.jpg)

**Comment by wmjordan** [comment]
Here's mine. You may select the first checkbox and see whether the outline appears.

<img width="251" alt="image" src="https://user-images.githubusercontent.com/12182730/163776635-e60a01ce-770f-4dc7-8d82-9b7b184d84f6.png">

**Comment by fitdev** [comment]
Yes, it seems to have fixed this. Perhaps you should make a note of this VS option in Codists's options next to the Regions checkbox.

BTW I turned off outlining mode in VS for performance reasons. I also noticed that _in the dropdowns_ all `#region`s _are displayed_ correctly regardless the VS's outlining option. So you are suing a different code to show regions in different parts of the NaviBar (dropdown vs the bar itself)?

Lastly, as an aside, it would be really nice if you can support dropdowns for the namespace-scoped and type-scoped regions, so they can show a list of types / members they contain. Of course it would not make sense for in-member regions.

**Comment by wmjordan** [comment]
> I turned off outlining mode in VS for performance reasons. I also noticed that _in the dropdowns_ all `#region`s _are displayed_ correctly regardless the VS's outlining option. So you are suing a different code to show regions in different parts of the NaviBar (dropdown vs the bar itself)?

Yes, I used a different way to reuse the outline result on the NaviBar also for performance reasons.
On the bar, Codist queries the existing outline results and looks for `region`s that wrapping around the caret.
In the drop-down, Codist walks through the Roslyn document nodes for declarations then the directives, then inserts the directives among the declarations. This is much slower than what's happening on the bar.

**Comment by wmjordan** [comment]
> it would be really nice if you can support dropdowns for the namespace-scoped and type-scoped regions, so they can show a list of types / members they contain. Of course it would not make sense for in-member regions.

I also thought of that previously. But I did not manage to put some time on it. It is a nice idea.

**Comment by fitdev** [comment]
> Yes, I used a different way to reuse the outline result on the NaviBar, for performance reasons as well.
On the bar, Codist queries the existing outline results and looks for regions that wrapping around the caret.
In the drop-down, Codist walks through the Roslyn document nodes for declarations then the directives, then inserts the directives among the declarations. This is much slower than what's happening on the bar.

Oh I see. Thank you for the explanation. It makes complete sense. I will leave the Outlining mode on then and see how it goes.

Thank you for your help. I guess this issue can be closed now, unless you want to use it for region dropdown suggestion.

**Comment by wmjordan** [comment]
Hi, there's a new beta which displays the aforementioned region dropdown.

**Comment by fitdev** [comment]
Just tried the new version! It works great! Thank you for so quickly implementing this suggestion!
