### ISSUE TITLE
设置断点，整行变成白色的，和背景一样

### ISSUE THREAD

**Issue by mzy666888** [wmjordan/Codist#199]
无论是哪个主题，当前行在选中状态并且设置了断点，字体颜色变成白色

![devenv_QJHnhXU1p4](https://user-images.githubusercontent.com/2587129/168405211-fed71b2e-0093-461c-bdfc-503d8eaa4e41.gif)

**Comment by wmjordan** [comment]
可能和这个古老的问题有关：#14 
请重新启动 VS 看看还是不是这样。

**Comment by wmjordan** [comment]
看来是另外一个问题。
VS 不知道怎么用了另外一个背景色作为断点的背景色，导致文本看不清楚。

**Comment by wmjordan** [comment]
请下载新的测试版看看

**Comment by mzy666888** [comment]
下载了新版本的，还不如6.2呢？自己设置不起作用了

**Comment by wmjordan** [comment]
发布错误，请回退到之前的版本。
VS 的语法突出显示就像个黑盒子。这个问题比较麻烦。

**Comment by wmjordan** [comment]
刚刚发布了一个新的版本。

在这个版本中，如果我们不更改断点的颜色配置，Codist 应该不会再把断点颜色搞乱了。

**Comment by mzy666888** [comment]
去下载试一下

**Comment by wmjordan** [comment]
请下载新的 7260 版

**Comment by wmjordan** [comment]
一直都没有找到办法来定制断点的样式。
6.5.3 版只好将其屏蔽了。

**Comment by wmjordan** [comment]
最新的 Beta 版 #248 似乎可以很完美地解决这个问题，欢迎下载测试。
