### ISSUE TITLE
Feature Request: CS Document Outline

### ISSUE THREAD

**Issue by fitdev** [wmjordan/Codist#20]
Thank you for the excellent extension! Great new features lately!

I think another very useful feature would be a simple dockable window that shows the outline of the currently opened .cs file: classes/structs/enums/delegates, regions, methods/properties, etc. You can grow this feature over time, adding support for sorting, reordering, etc.

Perhaps you can start with just a read-only mode, click-navigation, and automatic sync with the active document. Also, it would be great if you can emphasize speed, because while there are other extensions with this feature, they are all very slow, so not practical to use. So, if you can implement this feature, at least on the basic level that is also fast, it would be awesome!

PS: Love your modular approach where you can toggle each individual feature!

**Comment by wmjordan** [comment]
Thank you for posting the request.

I guess parsing the code file and create the outlines does not take too much time, for the _Scroll Bar Marker_ feature in _Codist_ has already done this and I have not yet encountered severe performance hit from it, but creating the code outlines pane can take some considerable CPU power.

As you have mentioned, there are already quite a few extensions offering code outlines in the Market Place.
Could you share your experience of similar extensions with code outlines you have ever tried before?

**Comment by fitdev** [comment]
Thank you for your quick reply!

Glad to know that file parsing is not problematic and you could reuse the functionality you developed for the Scroll Bar Marker.

The existing extensions that have this feature work very slowly. That is usually there is a multiple-second delay between what's happening in the editor, and the outline being synchronized, or they tend to crash VS. CodeNav for instance is crashing VS for me from time to time. These are really the main reasons why I don't use them.

Also, with some of the extensions I just don't like the format / design. Ideally it should be simple, sharp (not too small and blurry), plain (reuse VS icons and colors where possible) and fast.

Some extensions might have advanced features which probably slow them down.

For me, the main reasons for an outline would be:

- Provide an overview of the file structure at a glance, especially regions and methods.
- Let me reorder members (methods, properties, regions) quickly. For example move members to/from regions. To do this in code is kind of tedious. I suppose you could create a code fix / refactoring to move method to region, but I don;t know if one exists, and it is not as elegant as just drag-dropping in an outline.

I am not so interested in ability to sort/group members in an outline. Far more important for me is to see the file structure at a glance (which members/regions are at the top, and which ones are at the bottom for example).

Hope it helps.

**Comment by wmjordan** [comment]
Thank you for your reply.
Have you ever tried _CodeMaid_, _Super Charger_, _Codinion_, etc.?

Those extensions also have member outline pane or similar functionality.

**Comment by fitdev** [comment]
CodeMaid was very slow to synchronize. SuperCharger was in general sluggish, and had too small of an interface (font size was small and looked blurry). Have not tried Codinion because it's not free. Hope it helps.

**Comment by wmjordan** [comment]
While I was digging into the issue and studying the source code of _CodeMaid_, I discovered that why those extensions were slow when updating the code structure pane might because that they have difficulty in accessing the _Roslyn_ parsed model in the active document from the external pane, consequently they have to parse the document on their own, and that makes things slow.

The _Scroll Bar Marker_ in _Codist_ could access the document for it was in the code editor control. For Tool Windows which are **outside** of the code editor, **it can be a tough task**...at least I have not yet seen an extension which can do that, and I have not yet managed to make it either.

## Help wanted: How to access the document model of the active document outside of the editor?

**Comment by wmjordan** [comment]
I just downloaded the latest version of _SuperCharger_. It placed the _CodeMap_ inside the editor and hence it could access the document model from Roslyn and therefore it was much faster. Please give it a try.

**Comment by fitdev** [comment]
Wow! You are really fast! Thank you for looking into this! Great research!

I didn't know about the big difference between the control being inside the code editor vs. outside of it. Personally I don't mind at all if it is part of the code editor, as long as it is clear and fast.

Maybe I will give _SuperCharger_ another try. For one thing I do like the way they add colorful icons in the cod editor (perhaps you ca incorporate similar feature into your extension as well - will make the code even more pleasing to the eye and easier to read). But I did have some other issues with it, like it not being free, the small font size of the _CodeMap_, issues with migrating options between upgrades, etc.

I really like your extension in that it is fast, customizable, and not bloated - almost all features are really useful!

**Comment by wmjordan** [comment]
Thank you for commenting.

Regarding the _SuperCharger_, it has revolved a lot.

1. _SuperCharger_ is still free for using on VS Community Edition at this moment.
2. The font size in its _CodeMap_ is configurable now.
3. Options migration sometimes is an issue that we can not avoid. _Codist_ has broken some options during upgrading for quite a couple of times as well.

Well. Back to the document outline feature.

I have been pondering something different from the _CodeMap_ provided by _SuperCharger_, for a long time.
Is there anything that takes much less space, but still helpful for programmers to spot the code members they are looking for, overview the structure of a code file and fast to access and efficiently synchronizing with the code?
The _Scroll Bar Marker_ is one attempt.
What shall be the next?

**Comment by fitdev** [comment]
Thank you for letting me know about _SuperCharger_ improvements. I guess I will give it a second try.

I really like what you have done with _Scroll Bar Marker_, especially the line numbers! Great work there!

I think, that there are basically 2 major use cases that developers want with code outline feature:

- Be able to see file structure at a glance (in document order): In particular regions, types, members. Not so sure about "smaller" members like constants, fields, properties, enum fields (perhaps display of those should be configurable and off by default).

- Be able to reorganize file structure using drag-drop by rearranging members / types into regions. Perhaps even, for multi-window setup support drag-dropping members _between_ files: say from File1.RegionA to File2.RegionB. But that is a more advanced scenario. At least the single file use case should be done.

Now, with those 2 primary use cases in mind, I am not sure what the best way to present it should be. Given, what you said about having access to code editor's document model, maybe you can attempt to have something similar to _CodeMap_ by making it part of the code editor? I will try to update this thread as I get new ideas.

**Comment by wmjordan** [comment]
Thank you for sharing your thoughts.

The "smaller" members, I think, shall be displayed on the pane, grouped together into "fields", "properties", etc.
The ability of rearranging members is an essential feature for the pane. But dragging across windows can be a tough task, I guess.

I personally don't like that the outline pane inside the editor. I will try to implement it as an external tool window.

**Comment by fitdev** [comment]
I agree with you that I would much prefer the outline be in a separate window, and not as part of the code editor. I just hope you find a way to make it fast.

As for rearranging members / types and grouping / ungrouping them into regions, moving between regions, etc. - within the same file, I think it can also be done differently, without the outline feature (although of course it can be duplicated in the outline pane as well).

Roughly the idea is to enable new shortcuts / refactorings perhaps together with your new edit bar feature, so that, for example, if you are anywhere within a member (like a method) you can "activate" the rearrange feature by either a keyboard shortcut, refactorings menu, and / or your new edit toolbar. Upon "activating" the fature, it will present you with a UI of some sort (maybe a submenu of existing refactorings menu), or a dialog of sorts where you can:

- If there are already defined regions, suggest to move the member into one of those regions (excluding the region the member is currently in).
- In addition ability to move member to a new region.
- When the action is completed, the cursor should remain in the same position (within the member) as when it did before the move,

The same functionality should apply to types as well. Sometimes a file may have more than one type (small enum for example co-existing with a class). So, then within perhaps if you access the feature from within the member, you should get options for both the member and the type, but if you access the feature "outside" the member, then you only get options for the type.

As far as just rearranging members (and possibly types), regardless of the regions. It could work similarly: a button on your floating toolbar and/or a shortcut, similar to how you can duplicate / move a line up/down (with some extensions), it should be possibly to move up/down the whole member (relative to other members).

Maybe this will give you some more ideas.

**Comment by wmjordan** [comment]
Recently I found a way to get access to the active document window.
Thus, it is possible to program an external window pane to reflect the changes of the active document.

**Comment by fitdev** [comment]
That's awesome! Congratulations! Can't see wait to see the fruits of your work!

BTW: Not sure if I mentioned it before. _CodeNav_ extension is very close to what I was looking for. However, it is slow to synchronize at times, and even more importantly, VS suggests that it might be the cause of crashes. So while, it has the features, it is not really usable.

**Comment by wmjordan** [comment]
Thank you for replying.
Unfortunately I am tight on my schedule. You may have to wait quite some time for this feature. I saw that _CodeNav_ was updating quite frequently too. Why not post your issues there and see whether the author can fix it?
