### ISSUE TITLE
Question - Navigation Bar - shows nothing at all (VS 2022) - reinstall not works

### ISSUE THREAD

**Issue by dslavik29** [wmjordan/Codist#201]
![image](https://user-images.githubusercontent.com/67827453/170820719-1070f00e-e41d-4713-8f80-acb32b25d4c3.png)
![image](https://user-images.githubusercontent.com/67827453/170820806-1f99d5a6-7100-4074-b735-fc9f4243fb64.png)

**Comment by wmjordan** [comment]
That's weird.
Codist has mistakenly treated your .cs file as a Markdown file.
Could you post a project that can reproduce this problem here?

**Comment by wmjordan** [comment]
Please try build 7289 in #197 and take a screenshot of your .cs file document window.

**Comment by dslavik29** [comment]
It also seemed strange to me, as I observed in VS 2019, there were no problems with this.
This is just an empty project in WPF App (.NET Framework) with one property.

I tried the recommended build and it's now disappear completely:
![image](https://user-images.githubusercontent.com/67827453/170863155-950557c5-ffa8-47b8-95b5-e8e295afc1e8.png)

**Comment by wmjordan** [comment]
Why your VS does not have the original navigation bar like the following?
<img width="394" alt="image" src="https://user-images.githubusercontent.com/12182730/170900296-9b47acad-df38-41ea-be65-56db691f0ae1.png">

**Comment by wmjordan** [comment]
You should enable the Navigation Bar for Codist to work.

<img width="455" alt="image" src="https://user-images.githubusercontent.com/12182730/170901957-480af195-8171-45f2-820c-a41fc6ee14bf.png">

**Comment by dslavik29** [comment]
Great perfect, so that was the reason... 🤔
You're right, thank you so much @wmjordan for your help 😇
