### ISSUE TITLE
Question - Web Search is not available (VS 2022)

### ISSUE THREAD

**Issue by dslavik29** [wmjordan/Codist#202]
Hello there 🙂,

right click hasn't have any web search as is there on image:
![image](https://user-images.githubusercontent.com/67827453/170821955-cc445579-7584-4585-8b35-76b21dc0a5bc.png)

Please let me to know why it's happen and not show up to me.

**Comment by wmjordan** [comment]
Please check out the options page and see whether search engine items are listed there.
<img width="565" alt="image" src="https://user-images.githubusercontent.com/12182730/170849587-11f2acc1-e25a-4f73-81c9-1ca2fda17a6f.png">

If nothing is listed, click the _Reset_ button to restore items to default.

**Comment by dslavik29** [comment]
I chosen only the ones needed for my use:
![image](https://user-images.githubusercontent.com/67827453/170863570-16349eae-af23-4728-a8dc-68d55b42f1dc.png)
If I click on the reset, it will still not change in my case.

It's should work only on the "Smart Bar" or it's prepare for right click mouse on any item?
(Smart Bar I have disabled so it's should be maybe reason why it's not show to me "Web Search")
Is it necessary to activate and deactivate it this "Web Search"?
Thank you 🙂

**Comment by wmjordan** [comment]
The Web Search appears when you right click the Find button on Smart Bar, or right click the selection on Quick Info.
Thus it won't be disabled when you disable the Smart Bar.

**Comment by dslavik29** [comment]
This is when I have enable "Smart Bar", it's look great:
![image](https://user-images.githubusercontent.com/67827453/170994553-69fc60c3-1f72-474f-9bb1-dbe749b83f33.png)

After disable and then I right click on the "Super Quick Info":
![image](https://user-images.githubusercontent.com/67827453/170996351-1970afd2-cc57-49b4-ac5c-d68f76fb6906.png)

I don't see this possibility anywhere, am I doing something wrong?

Thank you so much. 🙂

**Comment by wmjordan** [comment]
Hi,
I've just updated the beta version to enable you web search symbols in Quick Info.
Please give it a try.

**Comment by dslavik29** [comment]
Hello there,

I'm sorry for late reply.
I tried and it **seems works perfectly**, great work.

_Minor idea to add_: 
I use the shortcut to display intellisense: 
>  Ctrl + K, Ctrl + I

=> it's not show me your extended (powerful) intellisense like as on mouse hover, but just default.

_Btw: How I'm able to select some text in the Quick Info (with Codist) without "Smart Bar" ?_
(I try to find something like that or figure it out, but in vain honestly.)

**Thanks a lot for your helpfulness** :))

**Comment by wmjordan** [comment]
> it's not show me your extended (powerful) intellisense like as on mouse hover, but just default.

Codist disables the Super Quick Info if you holds down the Ctrl key when opening the Quick Info.
It seems that I shall provide an option to toggle this feature.



> How I'm able to select some text in the Quick Info

You have to use your mouse. Hover the mouse cursor onto the text in the Quick Info and you know how to do.

**Comment by wmjordan** [comment]
> **Thanks a lot for your helpfulness** :))

If it does not bring you great trouble, please vote it 5 stars in the VS Marketplace :)
