### ISSUE TITLE
Support C# 11 static abstract interfaces in Super Quick Info tooltips

### ISSUE THREAD

**Issue by fitdev** [wmjordan/Codist#203]
There's upcoming feature in C# 11 (already available in Preview) which allows to define _static abstract_ members in interfaces:

```cs
interface IFoo {

  static abstract int SomeFooValue { get; }

  void DoFoo();
}

class FooClass : IFoo {

  //It would be nice when hovering over this that Codist's super quick info tooltip would show "Implements" section as it does for DoFoo below.
  public static abstract int SomeFooValue => 23;

  public void DoFoo() { }

}
```

So it would be nice if super quick info supported explicitly showing Implements section for such members in implementing types.

**Comment by wmjordan** [comment]
Thank you for the suggestion.
I will add support for C# 11 later when it is officially published.

**Comment by fitdev** [comment]
Hope you are doing well and CoViD situation has not seriously affected you.

Just wanted to elaborate on this issue a bit and suggest that:
- static abstract member implementations be supported in super quick info tooltips as well, i.e. not just operators
- ideally, if possible a different icon should be displayed for operators (currently it is the same icon as for method)

**Comment by wmjordan** [comment]
Well,
please try the new beta.

**Comment by fitdev** [comment]
Wow! You are so fast!
Thank you for the new beta. That was an unexpected surprise :)

A couple of points:
- Implicit and Explicit casting operators still show with method-like icons. Is it by design?
- Implementations of static abstract interface members do not show information in the tooltip about the interface and interface member that they implement (this is true of both operators and regular static members)
- Not sure about this, just a thought: perhaps it would be better to show a symbol for operator in addition to or instead of its name, i.e. `>>` vs `op_RightShift` `+` vs `op_Plus`

**Comment by wmjordan** [comment]
> * Implicit and Explicit casting operators still show with method-like icons. Is it by design?
> * Implementations of static abstract interface members do not show information in the tooltip about the interface and interface member that they implement (this is true of both operators and regular static members)

I will check them.

> * Not sure about this, just a thought: perhaps it would be better to show a symbol for operator in addition to or instead of its name, i.e. `>>` vs `op_RightShift` `+` vs `op_Plus`

I think the names are better, since they are easier to be clicked. The `-` is so tiny which is too hard to be spotted, compared with its name.

**Comment by wmjordan** [comment]
Please try the new beta.
Individual icons are used for explicit and implicit conversions in the new version.

**Comment by fitdev** [comment]
> I think the names are better, since they are easier to be clicked. The - is so tiny which is too hard to be spotted, compared with its name.

I agree. I was thinking that perhaps it is possible to display symbols _in addition to_ the names, in a bigger, **bold** font perhaps?

**Comment by fitdev** [comment]
> Please try the new beta.

Thank you for the new beta! Everything works great! Now all static members show information about implemented interfaces. Thank you!
