### ISSUE TITLE
Broken images from the Visual Studio Marketplace

### ISSUE THREAD

**Issue by doggy8088** [wmjordan/Codist#204]
I think the image link might be wrong.
![image](https://user-images.githubusercontent.com/88981/172420299-be468b03-a3e2-46c5-9f48-6e0cc94525b8.png)

**Comment by wmjordan** [comment]
Thank you for reporting the issue.

The images in the Marketplace page link to Github here.
Maybe Github has activated something to protect its images from being linked from outside or it has changed the image location. I have difficulty to verify that at this moment and will check it later if possible.

**Comment by wmjordan** [comment]
I've updated the Marketplace and released a new version.
Please help check the images there and see whether they appear.

**Comment by doggy8088** [comment]
@wmjordan It looks perfectly.
