### ISSUE TITLE
ArgumentException adding to PropertyBag when handling an event

### ISSUE THREAD

**Issue by AmadeusW** [wmjordan/Codist#205]
Hi, this is Amadeus from the Visual Studio Editor team.
We've received reports of 20 hits of `ArgumentException` in the Codist extension affecting VS 2022.

We're unable to peek into the call stack from Codist code, but from what we can see, it seems that 
- when you're handling an event
- you're attempting to add to a property bag which already contains that key.

```
mscorlib.ni!System.Collections.Hashtable.Insert
Microsoft.VisualStudio.CoreUtility.ni!Microsoft.VisualStudio.Utilities.PropertyCollection.AddProperty
Codist!Unknown
Codist!Unknown
Codist!Unknown
PresentationCore.ni!System.Windows.EventRoute.InvokeHandlersImpl
PresentationCore.ni!System.Windows.UIElement.RaiseEventImpl
```

**Comment by wmjordan** [comment]
Thank you for notifying me that.

Although I have never experienced this issue but I have some idea about it and will release a new version to address it.

**Comment by wmjordan** [comment]
A new version 6.3.1 was released yesterday.
Please help check whether this issue is resolved in the new version.

**Comment by wmjordan** [comment]
Hi,

Could you please help verify whether the new version helps solving this issue--no longer receiving `ArgumentException` reports recently?
