### ISSUE TITLE
For Visual Studio Code?

### ISSUE THREAD

**Issue by davidlehub** [wmjordan/Codist#209]
Hi, not sure if is a good place to ask, but i'm looking for the same tool in VS **Code**.

This Extension is amazing. Make me kind of addict to it :) 

Thanks you.

**Comment by wmjordan** [comment]
Thank you for your comments.

VS Code is a completely different architecture. That is, I have to learn and program from zero.
Though I use VS Code occasionally, however I can not afford the time to do so in the considerably long future.
