### ISSUE TITLE
Smart Bar上的图标模糊

### ISSUE THREAD

**Issue by WertherHu** [wmjordan/Codist#213]
![toolbar](https://user-images.githubusercontent.com/15544528/188578570-453407ee-d7e6-4469-8bb9-89d96c0c8219.png)
如图，Smart Bar上的图标模糊，显示器分辨率1080p

**Comment by wmjordan** [comment]
> 显示器分辨率1080p

为什么这个分辨率下，编辑器的文本字体还会这么大的呢？
是不是更改了编辑器窗口的显示比例？

**Comment by WertherHu** [comment]
是vs中代码编辑器部分吗？我设置到了150%

**Comment by wmjordan** [comment]
暂时没办法解决。VS 自己拉伸了图标，把图标搞模糊了。

**Comment by wmjordan** [comment]
下个版本可以解决
