### ISSUE TITLE
VS 17.3.4  Hangs when starting SurroundWith  

### ISSUE THREAD

**Issue by devtrix** [wmjordan/Codist#218]
When I press Ctrl+k, Ctrl+s  key combo a popup box that says "Please wait for an editor command to finish" and never goes away freezing the screen.

**Comment by wmjordan** [comment]
Hi, it seems that it is a duplicate of #217 
Please try the recent beta version and see whether it fixes your problem.

**Comment by devtrix** [comment]
#217 is for VS 16.11.19 and its a crash, but if you say its a duplicate, ok.  However,  where is this beta version?  I couldn't find it on the release page.

**Comment by wmjordan** [comment]
The [beta 6.6 (click here)](#214) was pinned in the issues, just above your post.

**Comment by devtrix** [comment]
> The [beta 6.6 (click here)](#214) was pinned in the issues, just above your post.
> 
> Anyway, since this bug was horrible, I [released a new version](https://github.com/wmjordan/Codist/releases/tag/v6.5.2) today. You might be able to update to a new version in the VS's Extensions dialog later as well.

How humiliating? LMAO.  Sorry man.  And thanks for the update and your super quick responses.  Have a great day.
