### ISSUE TITLE
More detailed list of interfaces in C# Quick Info

### ISSUE THREAD

**Issue by wmjordan** [wmjordan/Codist#222]
It would be really great if you could implement a more detailed list of interfaces in the Super Quick Info tooltips, where it shows the whole interface inheritance chain for each interface. I am now working on types with like 30+ interfaces with complex hierarchies and generic parameters and it would help a lot to know exactly through which higher level interface a lower level interface like `IEnumerable<T>` for example has been inherited.

Here's an example screenshot:

![2022-09-15 20_32_38-DotNet - FsDir cs](https://user-images.githubusercontent.com/8166847/190472263-1ed89691-f8f8-4ff9-aa41-a2e1c6add28d.jpg)

_Originally posted by @fitdev in https://github.com/wmjordan/Codist/issues/214#issuecomment-1248393125_

**Comment by wmjordan** [comment]
I am trying to merge interfaces into base types today.
<img width="303" alt="image" src="https://user-images.githubusercontent.com/12182730/198863929-ac0ab887-972a-4531-a0c0-af365c451719.png">

It does not seem good to me.
Although now we can see which base class has implemented what interfaces for us, the interfaces are now interlaced with the base types. In most of the time, we just care what interfaces are implemented by the current class, not where they are implemented.

It looks much less readable compared to the current implementation, which serves the purpose well--what interfaces are implemented by the current class.
<img width="367" alt="image" src="https://user-images.githubusercontent.com/12182730/198863988-de88cf7c-6e71-4180-8e83-cda1879a33ea.png">

Thus, I think merging interfaces into base types of a class is not a good way to go.

I will try to show hierarchical interfaces later and see how it works.

**Comment by wmjordan** [comment]
After some contemplation, I think the hierarchical interface list can be either redundant or misleading, since an interface can be implemented by current class or base classes, and/or inherited from multiple base interfaces at the same time:
If duplicated interfaces are displayed, it is redundant.
If those duplicated interfaces are not displayed, the information is incomplete and misleading.

And hereby I desired to keep existing design and additionally display where the interface is firstly implemented or inherited from.

<img width="368" alt="image" src="https://user-images.githubusercontent.com/12182730/198877438-0f836a57-7c88-4992-b71b-a3daa7b54ea1.png">

<img width="502" alt="image" src="https://user-images.githubusercontent.com/12182730/198877576-75dfad21-2307-4adf-b645-2b5dada8ba09.png">

**Comment by wmjordan** [comment]
@fitdev, there's a new beta version for you to test.

**Comment by fitdev** [comment]
Sorry for the late reply and thank you for your work. I will try the new beta ASAP and let you know my thoughts.

**Comment by fitdev** [comment]
I like the new design. It is certainly a very big improvement and quite helpful. Though I still think that displaying full information about inheritance of interfaces would be helpful, but you are right a simple hierarchy approach does not look too good to me either.

**Comment by wmjordan** [comment]
Well, let's settle down here at this moment. Feel free to open a new issue if something comes to your mind.
