### ISSUE TITLE
Bug? 隐藏账户和反馈按钮每次重启都失效

### ISSUE THREAD

**Issue by yyangdid** [wmjordan/Codist#224]
系统版本: `Win10 x64`
VS 版本: `2022 17.3.6`
Codist 版本: `6.6.0.7700`

`隐藏账户图标` 和 `隐藏反馈按钮` 每次重新启动 VS2022 之后都会失效, 去设置里面查看, 选择框是被勾选的状态, 需要取消勾选然后再次勾选才能重新生效.

**Comment by wmjordan** [comment]
有时候，Codist插件启动了之后，VS还没有完成初始化，那几个控件还会在界面上。
这时候，等加载完解决方案了，就会隐藏上述控件。

**Comment by yyangdid** [comment]
啊, 可能不知哪里我搞的不合适, 我这里经常失效, 刚开始用 VS, 我慢慢摸索摸索
