### ISSUE TITLE
Some syntax styles were not applied after installing a new version

### ISSUE THREAD

**Issue by wmjordan** [wmjordan/Codist#227]
Reproduction:

1. Install a new version of Codist
2. Restart VS
3. Some syntax styles were not applied

Workaround:

1. Restart VS
2. Things will get back to normal after the restart

or...

1. Open the Customize Codist Syntax Highlight window
2. Change a style
3. Press the Cancel button to close the dialog and reset the settings

**Comment by marcLeb** [comment]
I have the problem that some syntax highlighting settings (especially Constructor-method and Breakpoints) disappeared completely .
Compare these two screenshots that shows the exact same object and cursorposition:

Codist 6.4:

![codist_6 4](https://user-images.githubusercontent.com/84007877/203065550-3a9d6e90-1491-44d3-a9be-4a2395ffc302.PNG)


Codist 6.6:

![codist_6 6](https://user-images.githubusercontent.com/84007877/203065595-a0c49a09-316c-4063-a077-2bcc1f5386a2.PNG)

**Comment by wmjordan** [comment]
> Constructor-method

Please make sure you have not check the following option, which will make the construct highlighted as the containing type (`class` or `struct`).

<img width="407" alt="image" src="https://user-images.githubusercontent.com/12182730/203186619-ae41197e-71b4-4fcb-b6b9-376115527b0d.png">

**Comment by marcLeb** [comment]
Nice, that works, thank you very much for this hint. It is a little embarrassing that I did not see this option, though.

**Comment by wmjordan** [comment]
Weird. [It has been there](https://github.com/wmjordan/Codist/issues/141) for a long time.

**Comment by marcLeb** [comment]
Actually i am not sure how this happened.
Several times I reinstalled different versions for testing and sometimes this option seems to have been enabled and other times not. I honestly have no idea why though

**Comment by wmjordan** [comment]
Just verified this issue was not fully fixed.
