### ISSUE TITLE
Navigation bar dropdown menu open at old tab location when moved tab with keybaord shortcut

### ISSUE THREAD

**Issue by homanology** [wmjordan/Codist#228]
I use split view in VS to read multiple source file at the same time. 
I noticed that after I used keyboard shortcut to move a tab from the left side to right side and issue a command to bring out the navigation bar drop down menu, the menu will be opening from the old tab location (the left side) as if I didn't move the tab.
It doesn't happen if I use the mouse to drag the tab instead of using keyboard shortcut to move the tab.

Thanks

**Comment by wmjordan** [comment]
I am sorry that I seldom use keyboard shortcuts.
Could you please tell me what shortcuts are used?

**Comment by homanology** [comment]
Window.MovetoNextTabGroup
Window.MovetoPreviousTabGroup

**Comment by wmjordan** [comment]
So, you mean:

You have two window groups: group 1 and group 2.
And a document is originally in group 1.
Move it to group 2.
Press a shortcut key to bring out NaviBar menu.
The menu is appearing in a remaining document in group 1, instead of the document just moved into group 2?

**Comment by wmjordan** [comment]
Please download and test the new beta.
