### ISSUE TITLE
代码样式不显示

### ISSUE THREAD

**Issue by GhostDevil** [wmjordan/Codist#229]
安装后显示正常，当打开设置页面，未进行更改，关闭设置 窗口后 ，代码样式无法使用，重启vs依然无效。

**Comment by wmjordan** [comment]
请上传各步骤的截图来看看

**Comment by GhostDevil** [comment]
![image](https://user-images.githubusercontent.com/19898700/204437075-58ee3db3-8f99-445b-944b-fec93c32e232.png)
![image](https://user-images.githubusercontent.com/19898700/204437135-a8b3733a-79ff-4f2c-9c78-40fdd245c558.png)
打开过一次设置窗口后，仅仅是查看选项，关闭后代码样式失效，无法应用效果，重新安装插件，发现依然处于无效状态

**Comment by wmjordan** [comment]
你配置了语法突出显示方案吗？配置了哪些样式？

请点击上面截图的“打开配置文件夹”按钮，把配置文件夹里面的json文件上传上来看看。

**Comment by GhostDevil** [comment]
{
  "Version": "6.6.0",
  "Labels": [
    {
      "Label": "!",
      "StyleID": "Emphasis"
    },
    {
      "Label": "#",
      "StyleID": "Emphasis"
    },
    {
      "Label": "?",
      "StyleID": "Question"
    },
    {
      "Label": "!?",
      "StyleID": "Exclaimation"
    },
    {
      "Label": "x",
      "IgnoreCase": true,
      "StyleID": "Deletion"
    },
    {
      "Label": "+++",
      "StyleID": "Heading1"
    },
    {
      "Label": "!!",
      "StyleID": "Heading1"
    },
    {
      "Label": "++",
      "StyleID": "Heading2"
    },
    {
      "Label": "+",
      "StyleID": "Heading3"
    },
    {
      "Label": "-",
      "StyleID": "Heading4"
    },
    {
      "Label": "--",
      "StyleID": "Heading5"
    },
    {
      "Label": "---",
      "StyleID": "Heading6"
    },
    {
      "AllowPunctuationDelimiter": true,
      "Label": "TODO",
      "IgnoreCase": true,
      "StyleID": "ToDo"
    },
    {
      "AllowPunctuationDelimiter": true,
      "Label": "TO-DO",
      "IgnoreCase": true,
      "StyleID": "ToDo"
    },
    {
      "AllowPunctuationDelimiter": true,
      "Label": "undone",
      "IgnoreCase": true,
      "StyleID": "Undone"
    },
    {
      "AllowPunctuationDelimiter": true,
      "Label": "NOTE",
      "IgnoreCase": true,
      "StyleID": "Note"
    },
    {
      "AllowPunctuationDelimiter": true,
      "Label": "HACK",
      "IgnoreCase": true,
      "StyleID": "Hack"
    }
  ],
  "QuickInfo": {},
  "Styles": [
    {
      "Key": "Codist: Emphasis",
      "Bold": true,
      "FontSize": 10.0,
      "ForegroundColor": "#008000"
    },
    {
      "Key": "Codist: Question",
      "ForegroundColor": "#9370DB"
    },
    {
      "Key": "Codist: Exclaimation",
      "ForegroundColor": "#CD5C5C"
    },
    {
      "Key": "Codist: Deletion",
      "Strikethrough": true,
      "ForegroundColor": "#808080"
    },
    {
      "Key": "Codist: Task - ToDo",
      "ForegroundColor": "#FFFFFF",
      "BackgroundColor": "#00008B"
    },
    {
      "Key": "Codist: Task - Note",
      "ForegroundColor": "#FFFFFF",
      "BackgroundColor": "#FFA500"
    },
    {
      "Key": "Codist: Task - Hack",
      "ForegroundColor": "#90EE90",
      "BackgroundColor": "#000000"
    },
    {
      "Key": "Codist: Task - Undone",
      "ForegroundColor": "#A4AFD1",
      "BackgroundColor": "#714136"
    },
    {
      "Key": "Codist: Heading 1",
      "FontSize": 12.0
    },
    {
      "Key": "Codist: Heading 2",
      "FontSize": 8.0
    },
    {
      "Key": "Codist: Heading 3",
      "FontSize": 4.0
    }
  ],
  "MarkerSettings": [
    {
      "Id": 1,
      "ForegroundColor": "#00FFFF"
    }
  ],
  "SearchEngines": [
    {
      "Name": "Bing",
      "Pattern": "https://www.bing.com/search?q=%s"
    },
    {
      "Name": "StackOverflow",
      "Pattern": "https://stackoverflow.com/search?q=%s"
    },
    {
      "Name": "GitHub",
      "Pattern": "https://github.com/search?q=%s"
    },
    {
      "Name": "CodeProject",
      "Pattern": "https://www.codeproject.com/search.aspx?q=%s&x=0&y=0&sbo=kw"
    },
    {
      "Name": ".NET Core Source",
      "Pattern": "https://source.dot.net/#q=%s"
    },
    {
      "Name": ".NET Framework Source",
      "Pattern": "https://referencesource.microsoft.com/#q=%s"
    }
  ],
  "WrapTexts": [
    {
      "Name": "\"\"",
      "Pattern": "\"$\"",
      "Indicator": "$"
    },
    {
      "Name": "()",
      "Pattern": "($)",
      "Indicator": "$"
    },
    {
      "Name": "''",
      "Pattern": "'$'",
      "Indicator": "$"
    },
    {
      "Name": "[]",
      "Pattern": "[$]",
      "Indicator": "$"
    },
    {
      "Name": "{}",
      "Pattern": "{$}",
      "Indicator": "$"
    },
    {
      "Name": "<>",
      "Pattern": "<$>",
      "Indicator": "$"
    },
    {
      "Name": "%%",
      "Pattern": "%$%",
      "Indicator": "$"
    }
  ],
  "SymbolReferenceMarkerSettings": {
    "ReferenceMarkerColor": "#00FFFF",
    "WriteMarkerColor": "#F0E68C"
  }
}

我没有更改任何默认选项... 原有的配置 如上

**Comment by wmjordan** [comment]
Codist 不会在安装好之后自动应用语法突出显示样式，你要自己配置样式才行。
执行“工具”菜单下的“配置Codist高级语法样式”命令，在弹出的对话框中，可以点击对话框左下角的预定义主题快速配置样式。

<img width="406" alt="image" src="https://user-images.githubusercontent.com/12182730/204468940-ec7a0ed4-9ebd-4794-8b65-7d5576e95405.png">

**Comment by GhostDevil** [comment]
ok,重新配置此项切换后可以起效。
产生疑问的原因是：首次安装好之后，直接有起效的样式出来，随之进入到设置窗口查看配置项后返回（直接x按钮关闭），样式才发生了失效或者改变，不知道是不是某个配置加载逻辑问题......

**Comment by wmjordan** [comment]
是 BUG。
谢谢告知！

**Comment by wmjordan** [comment]
这个问题只有在刚刚安装 Codist 之后才会出现。
新的 Beta版可修复这个问题。

**Comment by GhostDevil** [comment]
ok，整体非常不错，感谢技术奉献！
