### ISSUE TITLE
[Suggesstion] Support source file(path) info in Super Quick Info

### ISSUE THREAD

**Issue by LuohuaRain** [wmjordan/Codist#230]
- Source file (full path of Assembly) can be shown in Super Quick Info
- Clickable, after clicking, Solution Explorer can navigate to this file if it's here. The specific effect is like 
Visual Studio Menu> _Tools> Options> Projects and Solutions> General> Track Active Item in Solution Explorer_
- It would be better if there is a hotkey to implement navigate to source file

**Comment by wmjordan** [comment]
> * Source file (full path of Assembly) can be shown in Super Quick Info

It is possible. Maybe there will be an option to show this.

> * Clickable, after clicking, Solution Explorer can navigate to this file if it's here. The specific effect is like
>   Visual Studio Menu> _Tools> Options> Projects and Solutions> General> Track Active Item in Solution Explorer_

I don't know how to do that at this moment.
Do you know any existing extension which implements this feature?

> * It would be better if there is a hotkey to implement navigate to source file

VS has it. Press F12.

**Comment by wmjordan** [comment]
> * Source file (full path of Assembly) can be shown in Super Quick Info

I misread your post in the former reply.

It is impossible to display the full path of an assembly due to the limitation of Roslyn.

**Comment by LuohuaRain** [comment]
Actually, it's possible. Resharper has these functions. Please view, 

[locate in explorer](https://www.jetbrains.com/help/resharper/Navigation_and_Search__Context_Dependent_Navigation.html#locating-current-document-in-explorer) 

[Source file location](https://www.jetbrains.com/help/resharper/Reference__Process_Explorer.html#context-menu-commands)

**Comment by wmjordan** [comment]
Resharper seems to have its own logic.
Codist relies on Roslyn.
But since we can see the path in the result of the decompiled meta source code,
I will try to find a way to implement this.

**Comment by O-n-y** [comment]
I agree, this would be very useful to have Solution Explorer to be 'syncronized' with current file you are editing at the moment

**Comment by wmjordan** [comment]
> have Solution Explorer to be 'syncronized' with current file

VS already has such an option.
<img width="488" alt="image" src="https://user-images.githubusercontent.com/12182730/206984233-42d6ca88-75ad-4eea-a2a0-5c210499b135.png">

**Comment by O-n-y** [comment]
Is it possible to add an option to auto-close folders when moved to another file (active file changed), so we do not end up with lots of opened directories? As in this case, Solution View becomes very messy!

to clear out, I want to have functionality:
1) when I change the active file (switched to edit some other) - in solution explorer it will track active item, so open subfolders, etc.
2) after I change it again - it will clear the state of solution explorer (i.e. collapse all opened folders), the easiest way I think would be to save the state of solution explorer before "track active item" is executed and restore it  when next item proceed

**Comment by O-n-y** [comment]
Why? at once I need only 1 have only 1 file open, so I do not need multiple locations opened.
This is essential when you have a big solution with multiple projects and many folders.
1. I activate one item (edit), and it moves me there
2) I activate 2nd, and it closes all up - move me to second.
repeat - for me it would be the best option,

Currently, I had to disable 'track active' as it clusters me in open directories and it makes it hard to navigate in general

**Comment by wmjordan** [comment]
> * Source file (full path of Assembly) can be shown in Super Quick Info

@LuohuaRain 
I've figured out the way to display the assembly file path.
The path is somewhat long, usually.

<img width="545" alt="image" src="https://user-images.githubusercontent.com/12182730/216746811-48cea95e-2cb1-46d8-ad29-74f036bc8ac2.png">
<img width="469" alt="image" src="https://user-images.githubusercontent.com/12182730/216746841-ee74ee81-cd96-4d2a-9274-5978e514b62e.png">

**Comment by wmjordan** [comment]
@LuohuaRain 
Please download and test the new beta.
