### ISSUE TITLE
Disable all visuals - leave only tooltips -  how ?

### ISSUE THREAD

**Issue by O-n-y** [wmjordan/Codist#232]
I want to have only tooltips (for enums for example), but do not want the plugin to change any of my code visuals,
I haven't found how to disable the visual styles which the plugin applies.

Is there a way to do so?

**Comment by O-n-y** [comment]
![image](https://user-images.githubusercontent.com/3432745/206366322-e9b24f96-31f4-4dcf-846e-60155583afcf.png)
![image](https://user-images.githubusercontent.com/3432745/206366956-629d2f75-17fb-472f-887e-20c0cf436930.png)

**Comment by O-n-y** [comment]
![image](https://user-images.githubusercontent.com/3432745/206367284-2e30f7f6-48ec-4c0a-bbc9-68da9bf9e0e0.png)

**Comment by LuohuaRain** [comment]
Tools> syntax highlight configuration> Reset

**Comment by O-n-y** [comment]
Thank you!  this menu is located in a very bad place, I could not find it without this tip.

Maybe consider making it a button? For better visual representation. Also having a reset button inside options without the need to go to this additional window would help a lot too!

**Comment by O-n-y** [comment]
Is there a way to decrease timeout before the tooltip would appear?

**Comment by wmjordan** [comment]
> Thank you! this menu is located in a very bad place, I could not find it without this tip.
> 
> Maybe consider making it a button? For better visual representation. Also having a reset button inside options without the need to go to this additional window would help a lot too!

If you don't want the syntax highlight, just disable it in the options box.
<img width="523" alt="image" src="https://user-images.githubusercontent.com/12182730/206617438-d3fa99db-a111-4d30-93bb-22ed25128413.png">

> Is there a way to decrease the timeout before the tooltip would appear?

What tool tip?

**Comment by O-n-y** [comment]
![image](https://user-images.githubusercontent.com/3432745/206632053-009b0422-aaa5-47cc-a361-db4141ff7ce3.png)
this one (i would like it to appear quicker), so it would be good to have such a config option! 

as for syntax - I tried this before creating this issue, and it was not working - but the suggestion about 'reset' - worked!

**Comment by wmjordan** [comment]
> i would like it to appear quicker

There's no API to change the timeout of the Quick Info, as far as I know.

> it was not working

It has a blue notice below the checkbox when you change the selection, which tells you to re-open the documents.

**Comment by alishahb** [comment]
> It has a blue notice below the checkbox when you change the selection, which tells you to re-open the documents.
i did re-open those, this wasn't helping. anyway - this issue solved as i found a solution

**Comment by O-n-y** [comment]
> It has a blue notice below the checkbox when you change the selection, which tells you to re-open the documents.
i did re-opened document, this was not helping.
anyway the issue solved, as i found the solution! :)
