### ISSUE TITLE
[Feature Request] Add ability to have Key binding for quick move to Definition from nav-bar

### ISSUE THREAD

**Issue by O-n-y** [wmjordan/Codist#233]
![image](https://user-images.githubusercontent.com/3432745/206642928-f131267a-d421-4765-a568-903974bc1bed.png)

Add ability to **Ctrl+Click** (could be changed by user?) on elemet from Nav-bar and jump to definition.

This would be very helpful for quick navigation.

**Comment by wmjordan** [comment]
In the options box, it has already give you the hint.
<img width="299" alt="image" src="https://user-images.githubusercontent.com/12182730/206666513-148f2b33-327f-4f4f-84bc-f4de383bbc17.png">

Jump to the Keyboard section in the Options dialog and change the shortcut at your wish.
<img width="521" alt="image" src="https://user-images.githubusercontent.com/12182730/206666725-4a62090d-044b-44fe-b6e2-ceb59e0df8f9.png">

**Comment by O-n-y** [comment]
there is no ability to activate it as Ctrl+Click (left mouse) from this menu
so this won't work.

I want to be able to click on the nav bar element (with some modifier like Ctrl)  to jump to the element definition

**Comment by O-n-y** [comment]
Currently you can do - right click and click go to definition, but it is not convenient at all as require to many actions for functionality which would be used often
![image](https://user-images.githubusercontent.com/3432745/206857602-81496c23-c99d-4c59-97e5-624accc7e8bb.png)

**Comment by wmjordan** [comment]
Okay, I understood.
It is possible for types, but for namespaces, it is meaningless.
Please download the new beta.

**Comment by O-n-y** [comment]
sure, only for types :)

**Comment by wmjordan** [comment]
The beta in the above link has implemented that behavior.

**Comment by O-n-y** [comment]
awesome, thank you!

**Comment by wmjordan** [comment]
@O-n-y 
Due to the report from #238.
I've added an option for this behavior, which by default is disabled.
If you update Codist, please turn it on.
<img width="523" alt="image" src="https://user-images.githubusercontent.com/12182730/208221074-708f9b42-1ff6-4266-84b6-0b695822e804.png">

**Comment by O-n-y** [comment]
thank you
