### ISSUE TITLE
[Feature Request] Add tooltip Options

### ISSUE THREAD

**Issue by O-n-y** [wmjordan/Codist#234]
1. Add option to modify (decrease) timeout after which tooltip would appear on hover

![image](https://user-images.githubusercontent.com/3432745/206632053-009b0422-aaa5-47cc-a361-db4141ff7ce3.png)

2. Add ability to modify position of tooltip (in my case i need to move it a bit down, as i have other plugins, which it overlaps.

**Comment by wmjordan** [comment]
1. I don't know how to do so. No way at this moment.
2. It is impossible. When you move your mouse outside of the symbol, the tip will disappear. You won't be able to reach it.

**Comment by O-n-y** [comment]
> 2. It is impossible. When you move your mouse outside of the symbol, the tip will disappear. You won't be able to reach it.
You might misunderstand me, i mean tooltip location (currently it is too hight for me, i want it to me a bit lower (so edit the offset where tooltip would appear)
` When you move your mouse outside of the symbol, the tip will disappear. You won't be able to reach it.` this is totally fine, i do not want to click on tooltip or something, i want tooltip do not cover some other stuff which appears from other plugins

**Comment by wmjordan** [comment]
Please read the readme.

Set the "Item Size" to values like the following screenshot. The Quick Info items will take less space.

<img width="540" alt="super-quick-info-options" src="https://user-images.githubusercontent.com/12182730/206903349-788dda1a-8e5c-4ce1-ae1b-70a8ef632367.png">

**Comment by O-n-y** [comment]
i do not need it to take less space, but rather the position of top left corner to be a bit down, as i explained previously

**Comment by O-n-y** [comment]
so i am talking about offset from the top

**Comment by wmjordan** [comment]
I am sorry that I don't understand your requirement.
Please demonstrate it.

**Comment by O-n-y** [comment]
![image](https://user-images.githubusercontent.com/3432745/206976926-85ff65c3-42fb-4739-a6d8-a5ca3d81a0b0.png)
ability to adjust the position of the top left corner of the tooltip (maybe in config.json file)

**Comment by wmjordan** [comment]
It may be possible to move it a bit to the left or up, but not viable to right or down.

**Comment by O-n-y** [comment]
maybe it could be accomplished by adding margins \ padding and having those transparent? so the real bg starts after transparent part?

**Comment by wmjordan** [comment]
> 2\. as i have other plugins, which it overlaps

Give me a screenshot showing how it overlaps, ok?

**Comment by O-n-y** [comment]
When the tooltip is UP (visible) is there a way to cycle through function overloads?

**Comment by wmjordan** [comment]
There's an option to display function overloads in the Super Quick Info.

**Comment by O-n-y** [comment]
but to cycle though them via the Keyboard shortcut when the tooltip is present?

**Comment by wmjordan** [comment]
No. I can't afford the time implementing that.
Use you mouse please.

**Comment by wmjordan** [comment]
I seemed to find out the way to implement a delay of Quick Info appearance.
Please download the new beta from #267.
