### ISSUE TITLE
[Feauture Request] Add option to have separate window with class information

### ISSUE THREAD

**Issue by O-n-y** [wmjordan/Codist#235]
We have class information with members in tooltip from nav-bar:
![image](https://user-images.githubusercontent.com/3432745/206647966-3622bfd8-91e8-48a7-89f1-f5d90b11e88e.png)

Please add ability to have this as a separate dockable windows, so we would have option to navigate to members quickly without need to hover tooltip etc

This is how it could be at the end (with docked window);
![image](https://user-images.githubusercontent.com/3432745/206648780-38f76428-7f3e-471f-928c-987ae23b65c8.png)

So we could click member and easy navigate (jump) to it

**Comment by O-n-y** [comment]
Addition to this request - ability to make items from this view to be set as **favorite**

1. Favoritre item could have some decoration - like to be **bold** or special **color** (user could choose)
2. The **star** icon would appear when you hover over item in that list - so you can click it - after this action, item would be in favorite.

**Comment by wmjordan** [comment]
I am inching toward this.
Recently I've resolved the namespace issue, which has something to do with this request internally.
But for type members, it can take me some heavier thoughts to get on with, in order to avoid memory leaks.

**Comment by wmjordan** [comment]
Maybe I shall merge this with #231
