### ISSUE TITLE
NOTICE: Development of Codist Is Suspended

### ISSUE THREAD

**Issue by wmjordan** [wmjordan/Codist#236]
Dear Users of Codist,

My country is being invaded by the SARS-CoV-2 virus, which spreads in the community exponentially.

I am suspending the development of Codist from now on and get on fighting against the virus.
Bugs of Codist may be fixed, if reported.
But new features won't be added.

I will be back when the battle is over.

**Comment by laicasaane** [comment]
@wmjordan Stay safe! Wish you good luck!

**Comment by fitdev** [comment]
My best wishes to you! Please stay safe!

**Comment by wmjordan** [comment]
Thank you my friends.

Several coworkers in my company have just got sick yesterday and fortunately their COVID symptoms are all minor at this moment. It was said that the variant in our province is a minor one and the variant in our capital Beijing is more severe.

**Comment by wmjordan** [comment]
Hi, we survived from the first national wave of COVID.
I and my family are recovering from the disease. My relatives and friends are all doing well after the wave.
I will continue the development of Codist. But at the same time, I will put some time on studying the Traditional Chinese Medicine and prepare for the second wave, which is believed to be striking our country several months in the future. Some people, I know, had gotten fever and got fine the next day after taken the medicine.

**Comment by wmjordan** [comment]
Hi, we survived from the first national wave of COVID.
I and my family are recovering from the disease. My relatives and friends are all doing well after the wave.
I will continue the development of Codist. But at the same time, I will put some time on studying the Traditional Chinese Medicine and prepare for the second wave, which is believed to be striking our country several months in the future. Some people, I know, had gotten fever and got fine the next day after taken the medicine.
