### ISSUE TITLE
[Issue] Performance issue & VS Freeze on compile when plugin enabled

### ISSUE THREAD

**Issue by O-n-y** [wmjordan/Codist#237]
For some reason, when I enable your plugin on a quite large project when I try to _**re-build**_ and run it do it VERY slowly (i re-checked when I do not have it enabled, and there is no such issue), and VS (i use 2022 17.4.2) actually **freezes** when this happens for a while (around few minutes).

Is there some reason the plugin would mess up when the project is building? 
And if there is a way to fix this? 

As I would like to continue using your plugin  - it is the only one I found, which could show the enum value on hover in hex :)

**Comment by O-n-y** [comment]
have to disable it sadly for now :(

**Comment by wmjordan** [comment]
Sorry to see that.
I and other users have not experience this.
Please re-enable Codist, go to the Options dialog, press the "Open Config Folder" button and upload the config file here.

<img width="523" alt="general-options" src="https://user-images.githubusercontent.com/12182730/206903274-5cf6188b-7ae4-42db-a975-eb25fd6d6383.png">

**Comment by O-n-y** [comment]
I currently running beta, i think it is running smoother, i will report back in a few days!
(before i was running version from vs studio marketplace)

**Comment by O-n-y** [comment]
looks like do not exist on last beta
