### ISSUE TITLE
[bug] Just updated to v7, the navigation bar shortcut is broken.

### ISSUE THREAD

**Issue by homanology** [wmjordan/Codist#238]
Hi,

After updated to version 7, the shortcut Edit.SearchClassMember (Ctrl+1, Ctrl+1) no longer bring out the drop down. I tried restart VS but the issue still remain. I have no choice but to revert back to v6.6 in the mean time.

Thanks

**Comment by wmjordan** [comment]
BUG confirmed. It is because a recent suggestion from #233 .
I will see how to fix this.

**Comment by wmjordan** [comment]
I've just uploaded a new release which solves this issue.
Please update Codist from the Visual Studio Marketplace.
