### ISSUE TITLE
Display struct field offset on C# Quick Info

### ISSUE THREAD

**Issue by O-n-y** [wmjordan/Codist#239]
```Csharp
	[StructLayout(LayoutKind.Sequential, Pack = 1)]
	public struct SomeStructRecord
	{
		[MarshalAs(UnmanagedType.ByValArray, SizeConst = 2)]
		private ulong[] Pad;
		public IntPtr PrevPtr;
		public IntPtr NextPtr;
		public uint Id;
		private uint _unk1;
      }
```

Can you please add to the tooltip information about struct member offset?

for example, when I put the cursor under `NextPtr` it should show me in the tooltip the offset `0x10`

**Comment by Decimation** [comment]
This information can be retrieved from symbol files. See my comment [here](https://github.com/wmjordan/Codist/issues/231#issuecomment-1415650781). Maybe merge with #231 and the class explorer?

**Comment by wmjordan** [comment]
> This information can be retrieved from symbol files

Usually it might not be the way to go.
When we work with source code files, there's no pdb, dll or any kind of symbol files.
We have to calculate the layout by the given literal code lines.

Unfortunately the layout may be various according to CLRs.

That is why we usually [calculate field offsets at runtime](https://devblogs.microsoft.com/premier-developer/managed-object-internals-part-4-fields-layout/).
The typical algorithm is can be read in the [TypeInspector of the ObjectLayoutInspector project](https://github.com/SergeyTeplyakov/ObjectLayoutInspector/blob/b66ddcb741fbfe685312dbbf3ad8b4f75f830ba3/src/ObjectLayoutInspector/TypeInspector.cs#L145).
