### ISSUE TITLE
Suggestion: syntax highlight configuration UI improvements

### ISSUE THREAD

**Issue by Decimation** [wmjordan/Codist#243]
The UI for the Syntax Highlight Configuration could be enhanced with a few QoL improvements:

### Search for syntax types
Here is a mockup:
![devenv_2023-02-06_(10h31m38s)_WilwTLOqdt](https://user-images.githubusercontent.com/4624891/217030218-20fa4673-9039-49ff-be3a-757ed994fc0f.png)

### Subcategories in the syntax categories tree

Syntax is already categorized, but can be further categorized. Perhaps a collapsible dropdown control to replace the existing dialog?

Example: 
 - Common 
 - - General
 - - Preprocessor
 - - Comment
 - - ...

**Comment by wmjordan** [comment]
Hmm, the Search function is planned. I want that too.

> Perhaps a collapsible dropdown control to replace the existing dialog?

This adds complexity to the dialog. I have decided not to do so when I designed the dialog and I will avoid that at this moment.

**Comment by wmjordan** [comment]
Please download the new beta, which has added a filter box into the customization window.
