### ISSUE TITLE
Query: How to change color of Super Quick Info members without Syntax Highlight

### ISSUE THREAD

**Issue by IneedHelp** [wmjordan/Codist#246]
Assuming the following case:
![image](https://user-images.githubusercontent.com/1366970/222471305-69ef04b8-73fe-423c-9222-529c0c514ee4.png)

is there a way to change the colors of the members presented in the Super Quick Info without using the Codist Syntax Highlight?

The situation is that I am using Codist mostly for the Super Quick Info feature, as I am using the granularity of ReSharper and Supercharger for syntax highlight, but I would like to make the color of the content in the Super Quick Info to match the colors I'm using for different kinds of members (for example the golden yellow for namespaces, the orange for methods, etc.).

Could you guide me if it's possible to achieve what I want? Thank you in advance!

**Comment by wmjordan** [comment]
Please try to open the _Customize Codist Syntax Highlight_ window (from the _Tools_ menu) and press the "_Reset_" button there, then press the _OK_ button to close the window.

Restart VS and see whether the highlight matches the color.

**Comment by IneedHelp** [comment]
What I meant is that I'm not using Syntax Highlight because I let other tools do the coloring
![image](https://user-images.githubusercontent.com/1366970/222679892-464c95a2-9c1a-426f-9838-e89230a9be9d.png)

so I was wondering if there's a way to change the colors used by Codist in Super Quick Info without applying that to the text editor.

**Comment by wmjordan** [comment]
Codist should be compatible with the syntax color defined in VS, and Super Quick Info should use your VS theme colors to render syntax elements when the Advanced Syntax Highlight is disabled.
<img width="440" alt="image" src="https://user-images.githubusercontent.com/12182730/222682207-4a7b2420-44cc-46f2-86b2-c0dcac14ace0.png">

It seems that your highlight tool is defining its only set of classifications for syntax elements.
Codist can't predict what they will use and will just use the VS color.
You might define your VS theme colors to match the colors defined in your tools.

**Comment by IneedHelp** [comment]
Perfect, I just wasn't sure if Codist uses some internal default color scheme, I should've thought it might use the Visual Studio generic settings. Thank you!
