### ISSUE TITLE
Crash in the Git compare file changed

### ISSUE THREAD

**Issue by phuocle** [wmjordan/Codist#247]
My VS 2019 vesion: 16.11.24
Codist version: 7.1.0.8164

When open OOB Git compare, after some seconds it crash and re-start VS
If I disable codist, try again to Git comare and there are no crash, all working.

Thank.

**Comment by wmjordan** [comment]
I did not encounter any crash in the Git Diff window.
Could you please take a look at the Windows Events Logs and see whether there is any related crash event log entry (typically there should be one)?
If there is, please post the track trace here.

**Comment by wmjordan** [comment]
Hi,
I am sorry that I have forgotten that issue that I have fixed previously.
Please download the new beta from #248 and test whether it works.

**Comment by phuocle** [comment]
not working, still crash, I already tested.

**Comment by wmjordan** [comment]
If so, please post the related stack trace in the Windows Events Logs.

**Comment by phuocle** [comment]
@wmjordan I updated to version 7.2.0.8385 and now it working, not crash when I used GIT compare windows.

Thank.

**Comment by wmjordan** [comment]
Oh, good to hear that!
Thanks for your feedback.
