### ISSUE TITLE
是否可以增强 注释高亮的功能 兼容vscode 插件 colorful comments 的特点。

### ISSUE THREAD

**Issue by heartacker** [wmjordan/Codist#249]
https://marketplace.visualstudio.com/items?itemName=ParthR2031.colorful-comments 插件地址

Red (!)
Blue (?)
Green (*)
Yellow (^)
Pink (&)
Purple (~)
Mustard (todo)
Grey (//)
Commented out Code can also be Styled to make it Clear the Code shouldn't be There.
Any Other Comment Styles you'd like can be Specified in the Settings.

![image](https://user-images.githubusercontent.com/1876302/225837371-3d63fe03-ef84-4e0b-8f0d-04ec98a2ac65.png)

**Comment by wmjordan** [comment]
阁下还是写中文吧

**Comment by wmjordan** [comment]
执行“_工具_”菜单的“_配置Codist高级语法样式_”命令，在弹出的对话框中可以配置注释标签和样式，如下图所示。
目前，多行注释被视为一个整体。如果要用不同的样式，你需要将多行注释转换为单行注释。
<img width="521" alt="image" src="https://user-images.githubusercontent.com/12182730/225840326-8641f64d-4140-4ede-a127-23a964442501.png">

**Comment by heartacker** [comment]
是需要我自己去转换，还是说有设置

**Comment by wmjordan** [comment]
你需要自己去设置，以使之看起来和Colorful comments的样式差不多。

**Comment by heartacker** [comment]
你好，我配置好了，但是这个有办法支持  vs2022 工作区吗？
我希望可以把这个配置放在我的工程的工作区，这样就方便 大家使用了， 类似 VSCode的工作区文件

**Comment by heartacker** [comment]
另外就是这个样式 有 task header 和 general header， 可以自己在添加吗？

**Comment by wmjordan** [comment]
> 把这个配置放在我的工程的工作区，这样就方便 大家使用了， 类似 VSCode的工作区文件

你是指类似和解决方案放在一起的 .editorconfig 文件？

> task header 和 general header

现在已经有十几种标签样式可以供你定制了哦，还不够用吗？
task header 和 general header 有什么特别的么？

**Comment by heartacker** [comment]
>你是指类似和解决方案放在一起的 .editorconfig 文件？

是的

>现在已经有十几种标签样式可以供你定制了哦，还不够用吗？
task header 和 general header 有什么特别的么？

现在我就是自己改了这些 task ，然后再去定义标签的，
只是这里写的这些task/header， 我们认为这个是预设的，我们想加一些自己的，
思路问题

**Comment by wmjordan** [comment]
目前我也没想到什么很好的办法可以允许在运行时增加样式。
VS 公开的接口不是很够用。虽然可以增加样式，但是无法有效地指定样式的优先级。

有一种简单的办法，就是让样式的名称看起来是被改成你想要的名称。
但怎样也好，都需要调整程序的配置结构，还是有些工作量的。

目前看起来是有点不爽，但这需求还是先放一放吧。有空再弄。

**Comment by heartacker** [comment]
好的，那工作区 配置这个可以搞不，我看有些插件是有这个功能的
