### ISSUE TITLE
Can't seem to get "Super Quick Info" to work

### ISSUE THREAD

**Issue by ChristopherHaws** [wmjordan/Codist#250]
After installing Codist, I no longer can see hover tooltips in Visual Studio. I have looked through all the settings, but cannot find anything that would be causing this. It only started happening after installing Codist. 

![image](https://user-images.githubusercontent.com/5934505/226499874-eb0e6466-42a2-437b-920e-316408e6b3ca.png)

![image](https://user-images.githubusercontent.com/5934505/226499855-d03d685a-9e30-479e-b88b-68584cb0adf4.png)

![image](https://user-images.githubusercontent.com/5934505/226499891-ab11799e-d522-44eb-9f38-748af863d1a2.png)

I really like this extension so it would be a shame if I had to uninstall it because of this =(

**Comment by wmjordan** [comment]
That's weird.
Have you installed any other extension which may have something to do with the Quick Info?

**Comment by wmjordan** [comment]
If no other extension might causing trouble, could you please post the config.json file (click the "Open Config Folder" button in the Options page) here?

**Comment by ChristopherHaws** [comment]
I finally got a chance to go through and figure out what was causing this issue today. I totally forgot that I had installed [Mads Kristensen's ToggleQuickInfo](https://github.com/madskristensen/ToggleQuickInfo). Sorry for creating this issue! Thanks for the great extension!

**Comment by wmjordan** [comment]
Thank you for your feedback.

You may consider removing the ToggleQuickInfo.
Codist has a similar function.
There's an option in Super Quick Info to _Hide the Quick Info_ until that you are pressing the Shift key before hovering your mouse on to the text element.

**Comment by ChristopherHaws** [comment]
Yeah, I had ToggleQuickInfo installed from before I had Codist installed. I will say that I like how you made it work with shift instead of being a toggle, however I do have one minor issue with it. If your mouse cursor is over the symbol before you hold down shift, the tooltip never appears. It only appears if you hold shift prior to moving your mouse over the code symbol. Is this something that could be changed? Would you like me to create a separate issue for that?

**Comment by wmjordan** [comment]
To hide the Quick Info after its appearance, press the Esc key.

**Comment by ChristopherHaws** [comment]
I'm not sure what you mean. I am talking about the quick info not opening at all if my mouse is over the code symbol before I press the shift key.

**Comment by wmjordan** [comment]
Oops, I misread your comment.
Currently there's no way to trigger the Quick Info if you don't move your mouse but press Shift down only.
I will update you if I find a way to do so.

**Comment by wmjordan** [comment]
However, if you don't check the _Hide the Quick Info_ option, the behavior of the Quick Info will be the opposite: it shows up as usual if no key is pressed, and it won't show up if you keep pressing the Shift key.
