### ISSUE TITLE
能否增加显示类型所在的命名空间的选项

### ISSUE THREAD

**Issue by never-for-ever** [wmjordan/Codist#252]
我现在遇到一个项目，在两个不同的命名空间下，有很多一样名称的类型，希望Super Quick Info上能显示其所在的完整的命名空间。

**Comment by wmjordan** [comment]
那类名看起来岂不是很冗长？

不确定类型名称空间时，将移动鼠标到类型名称上，在弹出的提示信息里面有类型所属的名称空间的。

**Comment by never-for-ever** [comment]
我现在是7.2版本，默认的设置，弹出的信息里没有看到哎。
我看7.3beta那个截图上有类似的，是否是新版本内容，还是说需要其他的设置？

**Comment by wmjordan** [comment]
请上传一张截图，说明要在哪些地方显示类型的名称空间

**Comment by never-for-ever** [comment]
主要是返回值部分。
![Snipaste_2023-04-06_10-32-07](https://user-images.githubusercontent.com/120788433/230257797-5accccb8-9603-4e34-a975-8252256526f1.png)

然后我看声明部分，好像也没有显示。
![声明](https://user-images.githubusercontent.com/120788433/230258349-8e0945c7-3ac4-4029-9192-31c1f6a84ec1.png)

我看到7.3beta 上有人是这样的，能看到命名空间。
https://github.com/wmjordan/Codist/issues/251#issuecomment-1493379472

**Comment by wmjordan** [comment]
“选项”对话框里有配置项
<img width="423" alt="image" src="https://user-images.githubusercontent.com/12182730/230261094-f53cdc3e-5509-42ff-a514-fe4a51bc037a.png">

你将鼠标移到快速提示的符号上，弹出的提示信息里也有名称空间。
![image](https://user-images.githubusercontent.com/12182730/230261675-a5623daa-728f-4eab-94c3-1c4be71dc76b.png)

**Comment by never-for-ever** [comment]
感谢！除了设置名称难以理解以外，功能上已经基本满足我的需求了。

**Comment by wmjordan** [comment]
刚刚发布了一个新版本，不选中显示名称空间和程序集的选项，也能在提示中显示类所在的名称空间。

<img width="273" alt="image" src="https://user-images.githubusercontent.com/12182730/232784644-ae13ca95-fd9a-4f7a-bb77-cf3ce13bfc61.png">
