### ISSUE TITLE
Does the line have a support plan?

### ISSUE THREAD

**Issue by lijianxin520** [wmjordan/Codist#253]
Does the line have a support plan?
![image](https://user-images.githubusercontent.com/47262889/231089977-e376f958-ff04-4313-b678-d2902313a7e5.png)

**Comment by wmjordan** [comment]
Do you mean the orange and purple lines at the left side of types and methods?
What's the benefit of that lines?

**Comment by lijianxin520** [comment]
visualstudio lines are not particularly friendly, and I wish I had better lines for folding blocks of code

**Comment by wmjordan** [comment]
You can just install SuperCharger for that.

**Comment by wmjordan** [comment]
I tried SuperCharger and felt those lines just distracted me from coding.

I have no motivation to implement it at this moment.
