### ISSUE TITLE
Links in Super Quick Info tooltips are not clickable or copyable

### ISSUE THREAD

**Issue by ChristopherHaws** [wmjordan/Codist#255]
Hi there!

I am not able to click or copy the links in the Super Quick Info tooltips. I couldn't find any options to enable this ability, so I am not sure if it's a bug or if it's just not a feature yet, but I would love to be able to click the link to open it in the browser.

![image](https://user-images.githubusercontent.com/5934505/234676683-9fd27175-9746-4d05-bcf6-6a790b2fe063.png)

Thanks for the great extension!

**Comment by wmjordan** [comment]
It could be a bug.
Are you working with a TypeScript project?

Please try to disable Codist and see whether the link can be clicked.

**Comment by wmjordan** [comment]
I installed the TypeScript workload and reproduced this issue.

1. Open a TypeScript project, the text on the Quick Info will not be selectable, but the link can be clicked.
2. Close the project and open a C# project.
3. Close the C# project.
4. Open the TypeScript project again.
5. The text on the Quick Info becomes selectable, but the link can not be clicked any more.

Weird.

**Comment by ChristopherHaws** [comment]
This also happens in a C# project (csproj) which contains a `package.json` file.

**Comment by wmjordan** [comment]
Please download the new beta.
The bug should have been fixed.

**Comment by ChristopherHaws** [comment]
Thanks! :)

**Comment by wmjordan** [comment]
Hi, I am optimizing the implementation of the Super Quick Info, changing its layout and behavior.

Could you please take the trouble to help test the new version in #267 (discussions are also made there)?
