### ISSUE TITLE
每次vs 打开特定的一个代码文件，VS 就会卡死，只能kill  VS, 禁用当前插件就好了。

### ISSUE THREAD

**Issue by heartacker** [wmjordan/Codist#256]
不知道为啥。

![image](https://github.com/wmjordan/Codist/assets/1876302/54f93d50-499d-4f70-85d0-cde7c16ad1b5)

**Comment by wmjordan** [comment]
这种问题比较讨厌。

请先用一般诊断方法试试：

1. 请下载新的 Beta 版本，看看是否会导致死锁。
2. 另外，请尝试禁用其它扩展，看看本扩展是否与它们有冲突。

高级诊断技术：

1. 使用 Process Explorer 或 Windows Informer 程序，查看 Visual Studio 进程 devenv.exe 的线程堆栈，从线程堆栈中一般会看到死锁线程会占用大量CPU，看看它的堆栈是怎样的，是否与 Codist 有关。
2. 使用进程管理器或上述两款进程分析工具，做线程转储，然后用 WinDbg 分析死锁线程。

**Comment by wmjordan** [comment]
这种问题比较讨厌，请帮忙诊断一下。

请先用一般诊断方法试试：

1. 请下载新的 Codist Beta 版本 (#254 )，看看是否会导致死锁。
2. 另外，请尝试禁用其它扩展，看看本扩展是否与它们有冲突。

高级诊断技术：

1. 使用 Process Explorer 或 Windows Informer 程序，查看 Visual Studio 进程 devenv.exe 的线程堆栈，从线程堆栈中一般会看到死锁线程会占用大量CPU，看看它的堆栈是怎样的，是否与 Codist 有关。
2. 使用进程管理器或上述两款进程分析工具，做线程转储，然后用 WinDbg 分析死锁线程。

**Comment by wmjordan** [comment]
在我这边无法重现出你提到的问题。请提供更多的信息。

**Comment by wmjordan** [comment]
请尝试下载新的Beta版(#267)，看看是否还能重现故障

**Comment by heartacker** [comment]
好像是ok了
