### ISSUE TITLE
Suggestion: Super Quick Info ability to navigate to source of displayed namespaces

### ISSUE THREAD

**Issue by IneedHelp** [wmjordan/Codist#257]
Hello, would it be possible to click on namespaces displayed in Super Quick Info which would allow navigating to files which contain those namespaces ?

**Comment by wmjordan** [comment]
Good to hear this request.

Years ago, when I was developing the Click and Go feature, it was possible to list all files that reference a namespace. However, for instance, my solution had a root namespace named `Codist`, the result list would contain all code files. I felt that was not so useful. Thus I removed that behavior.

@fitdev

Would you mind commenting on this request?

**Comment by fitdev** [comment]
I can certainly see how something like this could be useful. The only thing is that I am not sure whether _files_ would make sense as opposed to _types_.

For my needs I would rather prefer all namespaces displayed (i.e. all namespace names between `.`s) to be clickable, such that when clicked they would display the same kind of popup as is displayed when a namespace is clicked on the NaviBar - i.e. it produces a floating window with a list of members.

Files on the other hand could me more tricky - what if a namespace is spread across several projects / assemblies, for some of which there is no source code file (i.e. it is a framework or 3rd party assembly).

**Comment by wmjordan** [comment]
@IneedHelp 
The following is how it looks to list locations of namespaces, before I removing the link from Super Quick Info.

<img width="496" alt="image" src="https://github.com/wmjordan/Codist/assets/12182730/b58b04a6-6feb-44dc-8fc8-87481bddc260">

@fitdev 
Nowadays it is possible to right click the big button on Super Quick Info to find members of a namespace.
<img width="278" alt="image" src="https://github.com/wmjordan/Codist/assets/12182730/1d28de86-d222-4253-a0bf-6361fbcf6709">

**Comment by IneedHelp** [comment]
@wmjordan 

I was hoping something more in the likes of ReSharper Usages:

![image](https://github.com/wmjordan/Codist/assets/1366970/4d038051-d071-4640-bfb3-e82657e20f8f)

where if you query the usage of a namespace it displays a list of file names, followed by a code snippet of the usage and the line number and then finally followed by the fully qualified type. Regardless, whichever kind of navigational functionality you see fit adding to namespaces in Super Quick Info is still better than just the ability to select it as text.

**Comment by wmjordan** [comment]
@IneedHelp 
How about the screenshot in my last comment?

**Comment by IneedHelp** [comment]
I mean, that's fantastic, sure!

If thousands of files could be listed in a large solution, that's really the responsibility of the user, the extension is just doing its job. But in real-case scenarios, most people will probably not query the root of a namespace. Either-way, as I mentioned before, better to have any navigational functionality than none.

**Comment by wmjordan** [comment]
Good.

But I am more in favor for @fitdev's suggestion.
Instead of listing code file names, list namespaces and types within the clicked namespace, which may be more useful and straightforward.

**Comment by IneedHelp** [comment]
Absolutely, looking forward to it.

**Comment by wmjordan** [comment]
This feature is done.
Please download the new beta.

**Comment by IneedHelp** [comment]
I just installed it, good stuff !

**Comment by fitdev** [comment]
> Nowadays it is possible to right click the big button on Super Quick Info to find members of a namespace.

I know, it's great! But I was talking about the namespace displayed at the footer when hovering over any type or member. It would be nice to make all such namespaces (between the `.`s) clickable as well. But it's not terribly important. Just a suggestion.

**Comment by wmjordan** [comment]
> I was talking about the namespace displayed at the footer when hovering over any type or member

@fitdev The last beta should have this implemented.

**Comment by fitdev** [comment]
> The last beta should have this implemented.

Thank you so much! Amazing work! Love this improvement!

**Comment by wmjordan** [comment]
Good.
Thank you all for your suggestions and ideas.
