### ISSUE TITLE
Suggestion: Super Quick Info ability to better display ReSharper code inspection messages

### ISSUE THREAD

**Issue by IneedHelp** [wmjordan/Codist#259]
With ReSharper being such a popular tool and Codist on the to fame, it would be great if it were possible to parse ReSharper code inspection messages which are currently shunned to the bottom of the Super Quick Info, without any descriptive icon of their own.

To give a little bit more context, ReSharper code inspection allows for different levels of inspection severity
![image](https://github.com/wmjordan/Codist/assets/1366970/77162453-881a-4fbb-ad48-4d1d2374e6a7)

and these messages are being displayed at the bottom of the Super Quick Info
![image](https://github.com/wmjordan/Codist/assets/1366970/ab995628-1f3e-4a85-9f0b-4f12be380478)

Now, being displayed at the bottom might not be the worst, but it would be cool to display a ReSharper icon next to the message, or an icon that represents the severity (hint, warning, error, etc.). If this is be possible to achieve, it would feel very satisfying to look at.

**Comment by wmjordan** [comment]
Unfortunately, there is no way to let Codist know that info comes from ReSharper.

**Comment by IneedHelp** [comment]
I understand. May I ask, does it make any difference if this information is also shown in the scrollbar ? Like, could it be snatched from there and reprocessed in Super Quick Info ?

**Comment by wmjordan** [comment]
To recognize the content, Codist relies on two factors:
1. The analysis warnings can be gathered from `IErrorTag`s.
2. The Quick Info item has a `TextBlock` with a `Run` inline with text which matches the content of `IErrorTag`.

If ReSharper implements the warning like other code analyzers, for instance, Roslynator, VS Spell Checker, Codist will use the above pattern to insert an icon for them. Unfortunately, ReSharper may not be doing so.

**Comment by IneedHelp** [comment]
I see. It seems that verifying this assumption may pose a challenge unless one is personally using ReSharper. If you think sometime in the future you might want to try something in regard to this, I'll be happy to run tests.

**Comment by wmjordan** [comment]
Maybe you can post a feedback request to ReSharper developers to draw an icon before their inspection messages.
Hmm, they are paid to develop new features. And you are their customer.

**Comment by IneedHelp** [comment]
`Maybe you can post a feedback request to ReSharper developers to draw an icon before their inspection messages.`

They do show icons in the scrollbar messages and when hovering over symbols if this is enabled

![image](https://github.com/wmjordan/Codist/assets/1366970/0de64139-bbe5-49e6-95ce-dfc4a4ec717c)

and with a slew of enhancements provided by Enhanced Tooltip which they directly maintain and update

![image](https://github.com/wmjordan/Codist/assets/1366970/fc42369b-c0b2-460d-ac4e-8d8de17dbc9c)

![image](https://github.com/wmjordan/Codist/assets/1366970/d41668e1-c4ec-4f36-b5a3-be9ec288d8b1)

The only setback is that using ReSharper decorated tooltips directly conflicts with Codist, and for the most part of the past 5-6 years, I've been using both Codist and ReSharper's tooltips mixed, which resulted in a hybrid which looked pleasing, but would disable Codists functionality inside the tooltips.
