### ISSUE TITLE
Click and Go, Size Limit, Override Description features for Quick Info was not working on VS 15.8

### ISSUE THREAD

**Issue by wmjordan** [wmjordan/Codist#26]
After upgrading VS to 15.8, the _Click and Go_ and other Quick Info overrides no longer worked for the _Quick Info_ has changed its underlying controls.

**Comment by fitdev** [comment]
Not sure if this is related, as I am using VS 15.8 Preview 5, and I did notice that the Quick Info tooltips were not displaying:
- Type information for variables:
![2018-08-15 10_05_35-workspace net - microsoft visual studio preview](https://user-images.githubusercontent.com/8166847/44135690-d2ed9f66-a072-11e8-8e63-e916d2d67fd9.jpg)
- Currently used method overload (in particular its signature and return type):
![2018-08-15 10_07_01-workspace net - microsoft visual studio preview](https://user-images.githubusercontent.com/8166847/44135723-008751a6-a073-11e8-885d-fd20f732d030.jpg)

**Comment by wmjordan** [comment]
Version 15.8 had been released, please update to the final version.
A new version of Codist compatible with VS 15.8 is coming very soon. Please check around later.
