### ISSUE TITLE
Make Super Quick Info not close when clicking on an empty part of it after opening a context menu?

### ISSUE THREAD

**Issue by wmjordan** [wmjordan/Codist#263]
As the title said.

_Originally posted by @IneedHelp in https://github.com/wmjordan/Codist/issues/262#issuecomment-1546864310_

**Comment by wmjordan** [comment]
@IneedHelp
Currently the context menu will release all its references and dismiss the Quick Info in order to prevent potential resource leak, when it is closed.
At the early stage of its development, it did not closes the Quick Info, which resulted in the Quick Info being left there after executing a command in the menu.
I will see whether this can be improved.

**Comment by IneedHelp** [comment]
Yeah, it would be a nice touch having Super Quick Info persist after the user closes a context menu in it either by clicking on an empty space in Quick Info or by pressing Escape, and concurrently it will also make life easier for those like me which use Super Quick Info in conjunction with ReSharper's Enhanced Tooltips.

**Comment by wmjordan** [comment]
@IneedHelp 
This problem should have been fixed in the new beta.
