### ISSUE TITLE
Show ordinary comments in symbol declaration on Super Quick Info

### ISSUE THREAD

**Issue by IneedHelp** [wmjordan/Codist#264]
I'm loving the text only XML Doc feature and I was wondering if it's possible to make end-of-the-line the comments work as XML documentation

![image](https://github.com/wmjordan/Codist/assets/1366970/1f96eb0a-2065-4780-bd72-cc625677f998)

The main benefit of this is having a tidy display of members stacked on top of each other without being interrupted by simple comments sitting on top of them such as:

![image](https://github.com/wmjordan/Codist/assets/1366970/4bb29dce-7ccb-4d29-a1cb-5d2a9f0e0e1b)

**Comment by wmjordan** [comment]
Roslyn does not provide facility to do this.

Perhaps this can be implemented, but limited to fields and properties.

**Comment by wmjordan** [comment]
The implementation has almost covered any kinds of symbols, fields, properties, methods, enum fields, and even local variables and local functions.
