### ISSUE TITLE
Some suggestions on C# syntax highlighting

### ISSUE THREAD

**Issue by hypeartist** [wmjordan/Codist#265]
Would really nice to have:

1. Separate classifications for static symbols: static field, static method, static class
2. Attributes dimming

Thanx in advance.

**Comment by wmjordan** [comment]
1. The combined inheritance of _C#: Field_ style + _C#: Static member_ style does the trick. Do you still want a specific _Static Field_ style which does not inherit from _C#: Field_ and _C#: Static member_?
2. Attributes dimming is already implemented. Change the style for _C#: Attribute annotation_.

**Comment by hypeartist** [comment]
1. I'd want, say, to have: static field - "bold underlined + black", static class as "bold italic + deep blue", static method as "bold italic + deep magenta". But I can't find a way to achieve that using existing set of classifiers.
2. The existing implementation of attribute dimming is being applied to attribute name, leaving the rest (parameters, brackets) not dimmed. It looks kinda weird. I was proposing to make it possible to dim the whole attribute statement (starting from opening bracket and ending with closing one)

**Comment by wmjordan** [comment]
1. It is impossible to set various styles for static members/types. If C#: Static member is Bold+Underline, then static class, static field and static method will all have Bold+Underline. If it is possible, how the configuration user interface should look like? I don't want to list an array of "static..." settings in the list.
2. It will be possible in the next beta.
   <img width="391" alt="image" src="https://github.com/wmjordan/Codist/assets/12182730/cb434ef1-7d68-4515-b172-4c148ad5eecf">

**Comment by wmjordan** [comment]
Request 2:

It is already implemented.
Decrease the _Opacity_ value of the foreground of **_C#: Attribute annotation_**. Let it be as dim as you like.
<img width="635" alt="image" src="https://github.com/wmjordan/Codist/assets/12182730/5cb958df-7583-4f4a-9ab8-cd2ec9c0ac7d">

**Comment by hypeartist** [comment]
> It is impossible to set various styles for static members/types nowadays.
Won't something like this work nowadays?
![image](https://github.com/wmjordan/Codist/assets/3519388/d1f92c89-37ca-4e5c-b6e5-947d72f5fca5)

**Comment by wmjordan** [comment]
> > It is impossible to set various styles for static members/types nowadays.
> 
> Won't something like this work nowadays?
> 
> ![image](https://user-images.githubusercontent.com/3519388/239168263-d1f92c89-37ca-4e5c-b6e5-947d72f5fca5.png)

I couldn't infer anything from the screenshot you posted.
What's supposed to be achieved?

**Comment by hypeartist** [comment]
> Decrease the Opacity value of the foreground of C#: Attribute annotation. Let it be as dim as you like

Doesn't work for me

![image](https://github.com/wmjordan/Codist/assets/3519388/9eeb0848-d891-4f75-825a-aaa83f403038)

**Comment by hypeartist** [comment]
> I couldn't infer anything from the screenshot you posted.

https://github.com/hypeartist/Synthexer/blob/69a70e08752f7b3847fbee8142be2a85d10fcae1/Synthexer/Core/SynthexerTagger.cs#L322

**Comment by wmjordan** [comment]
> Doesn't work for me

Post the config.json file here.

The config.json file can be found by pressing the button as the following screenshot shows.
<img width="524" alt="image" src="https://github.com/wmjordan/Codist/assets/12182730/95595cc7-910a-437b-a4cb-f766e988d973">

**Comment by hypeartist** [comment]
> Post your config.json file here.

<details>
<summary>Details</summary>

```json
{
  "Version": "7.4.0",
  "Features": "SyntaxHighlight, SuperQuickInfo, WebSearch, WrapText",
  "SpecialHighlightOptions": "Default, UseTypeStyleOnConstructor, CapturingLambdaExpression",
  "Labels": [
    {
      "Label": "!",
      "StyleID": "Emphasis"
    },
    {
      "Label": "#",
      "StyleID": "Emphasis"
    },
    {
      "Label": "?",
      "StyleID": "Question"
    },
    {
      "Label": "!?"
    },
    {
      "Label": "x",
      "IgnoreCase": true,
      "StyleID": "Deletion"
    },
    {
      "Label": "+++",
      "StyleID": "Heading1"
    },
    {
      "Label": "!!",
      "StyleID": "Heading1"
    },
    {
      "Label": "++",
      "StyleID": "Heading2"
    },
    {
      "Label": "+",
      "StyleID": "Heading3"
    },
    {
      "Label": "-",
      "StyleID": "Heading4"
    },
    {
      "Label": "--",
      "StyleID": "Heading5"
    },
    {
      "Label": "---",
      "StyleID": "Heading6"
    },
    {
      "AllowPunctuationDelimiter": true,
      "Label": "TODO",
      "IgnoreCase": true,
      "StyleID": "ToDo"
    },
    {
      "AllowPunctuationDelimiter": true,
      "Label": "TO-DO",
      "IgnoreCase": true,
      "StyleID": "ToDo"
    },
    {
      "AllowPunctuationDelimiter": true,
      "Label": "undone",
      "IgnoreCase": true,
      "StyleID": "Undone"
    },
    {
      "AllowPunctuationDelimiter": true,
      "Label": "NOTE",
      "IgnoreCase": true,
      "StyleID": "Note"
    },
    {
      "AllowPunctuationDelimiter": true,
      "Label": "HACK",
      "IgnoreCase": true,
      "StyleID": "Hack"
    }
  ],
  "QuickInfo": {},
  "Styles": [
    {
      "Key": "Keyword",
      "ForegroundColor": "#5B6BFF"
    },
    {
      "Key": "class name",
      "Bold": true,
      "ForegroundColor": "#0080B0"
    },
    {
      "Key": "record class name",
      "Bold": true
    },
    {
      "Key": "struct name",
      "Bold": true,
      "ForegroundColor": "#8D00EC"
    },
    {
      "Key": "record struct name",
      "Bold": true
    },
    {
      "Key": "interface name",
      "Bold": true,
      "Italic": true,
      "ForegroundColor": "#2DC6FF"
    },
    {
      "Key": "enum name",
      "Bold": true,
      "ForegroundColor": "#A36201"
    },
    {
      "Key": "enum member name",
      "Bold": true,
      "ForegroundColor": "#623100"
    },
    {
      "Key": "delegate name",
      "Bold": true,
      "Italic": true,
      "ForegroundColor": "#FE01D1"
    },
    {
      "Key": "Number",
      "Bold": true,
      "ForegroundColor": "#FF0000"
    },
    {
      "Key": "String",
      "Bold": true,
      "ForegroundColor": "#009700"
    },
    {
      "Key": "string - verbatim",
      "Bold": true,
      "ForegroundColor": "#009700"
    },
    {
      "Key": "operator",
      "Bold": true,
      "ForegroundColor": "#E89C00"
    },
    {
      "Key": "punctuation",
      "Bold": true,
      "ForegroundColor": "#FF8000"
    },
    {
      "Key": "comment",
      "Italic": true,
      "ForegroundColor": "#C0C0C0"
    },
    {
      "Key": "C#: Control flow keyword",
      "Bold": false,
      "ForegroundColor": "#3865FE"
    },
    {
      "Key": "C#: Branching keyword",
      "ForegroundColor": "#0000FF"
    },
    {
      "Key": "C#: Static member",
      "Italic": true,
      "ForegroundColor": "#8C0062"
    },
    {
      "Key": "C#: Local declaration",
      "ForegroundColor": "#000000"
    },
    {
      "Key": "C#: Local variable",
      "ForegroundColor": "#000000"
    },
    {
      "Key": "C#: Namespace",
      "Bold": true,
      "ForegroundColor": "#7E6F01"
    },
    {
      "Key": "C#: Read-only struct",
      "Bold": true,
      "ForegroundColor": "#8D00EC"
    },
    {
      "Key": "C#: Event",
      "Bold": true,
      "ForegroundColor": "#FE01D1"
    },
    {
      "Key": "C#: Type parameter",
      "Bold": true,
      "ForegroundColor": "#93B66B"
    },
    {
      "Key": "C#: Field",
      "Bold": true
    },
    {
      "Key": "C#: Enum field",
      "Bold": true,
      "ForegroundColor": "#6F3700"
    },
    {
      "Key": "C#: Property",
      "Bold": true,
      "ForegroundColor": "#0000BB"
    },
    {
      "Key": "C#: Method",
      "Bold": true,
      "ForegroundColor": "#B30004"
    },
    {
      "Key": "C#: Extension method",
      "ForegroundColor": "#297A72"
    },
    {
      "Key": "C#: Parameter",
      "Underline": true,
      "ForegroundColor": "#23383A"
    },
    {
      "Key": "keyword - control",
      "ForegroundColor": "#5B6BFF"
    },
    {
      "Key": "operator - overloaded",
      "Bold": true,
      "ForegroundColor": "#FF0080"
    }
  ],
  "MarkerSettings": [],
  "SearchEngines": [
    {
      "Name": "Bing",
      "Pattern": "https://www.bing.com/search?q=%s"
    },
    {
      "Name": "StackOverflow",
      "Pattern": "https://stackoverflow.com/search?q=%s"
    },
    {
      "Name": "GitHub",
      "Pattern": "https://github.com/search?q=%s"
    },
    {
      "Name": "CodeProject",
      "Pattern": "https://www.codeproject.com/search.aspx?q=%s&x=0&y=0&sbo=kw"
    },
    {
      "Name": ".NET Core Source",
      "Pattern": "https://source.dot.net/#q=%s"
    },
    {
      "Name": ".NET Framework Source",
      "Pattern": "https://referencesource.microsoft.com/#q=%s"
    }
  ],
  "WrapTexts": [
    {
      "Name": "\"\"",
      "Pattern": "\"$\"",
      "Indicator": "$"
    },
    {
      "Name": "()",
      "Pattern": "($)",
      "Indicator": "$"
    },
    {
      "Name": "''",
      "Pattern": "'$'",
      "Indicator": "$"
    },
    {
      "Name": "[]",
      "Pattern": "[$]",
      "Indicator": "$"
    },
    {
      "Name": "{}",
      "Pattern": "{$}",
      "Indicator": "$"
    },
    {
      "Name": "<>",
      "Pattern": "<$>",
      "Indicator": "$"
    },
    {
      "Name": "%%",
      "Pattern": "%$%",
      "Indicator": "$"
    }
  ],
  "SymbolReferenceMarkerSettings": {
    "ReferenceMarkerColor": "#00FFFF",
    "WriteMarkerColor": "#F0E68C"
  }
}
```

</details>

**Comment by wmjordan** [comment]
> > I couldn't infer anything from the screenshot you posted.
> 
> https://github.com/hypeartist/Synthexer/blob/69a70e08752f7b3847fbee8142be2a85d10fcae1/Synthexer/Core/SynthexerTagger.cs#L322

Codist is not supposed to override your syntax highlight extension, in which **you have set all your formats of the highest priority**!

**Comment by hypeartist** [comment]
> Codist is not supposed to override your syntax highlight extension

No-no-no! I'm not using my extension. Only Codist. It was just an example of how "sub-classification" for static symbols could be done.

**Comment by wmjordan** [comment]
OK! You are right.
You have got to select this checkbox at this moment.

<img width="683" alt="image" src="https://github.com/wmjordan/Codist/assets/12182730/de0adbd2-caec-46ef-a8e8-03d68f055d62">

It is so weird... that the attribute annotation has dependency on this option.

**Comment by wmjordan** [comment]
I've gotten this bug fixed.
Now attribute notation no longer depends on the brace and parentheses settings.
Please wait for the new beta.

**Comment by wmjordan** [comment]
The problem is fixed.
Now the style of attribute notation does not depend on other settings.

**Comment by hypeartist** [comment]
> Please download and help test with the new beta.

Confirmed as fixed in the latest beta!
Thanks!

**Comment by wmjordan** [comment]
Thanks for the feedback.

As for the first request, I can't think of an efficient and flexible interface to configure the combinations.

For instance, once we offer "static class", "static method" and "static field", for completeness, we will also have to offer "static struct", "static property", "static event", etc. The list will be long.

Will someone else see this and then ask for "Since there are static series, I want to special style for private class, private method, private field, private struct, private interface, private enum, private property, private delegate, private event, etc."

Even if the configuration is possible, the implementation has got to care about the above specific situations and tag symbols specially with the classifications, which adds extra burden to the tagger.
