### ISSUE TITLE
Scrollbar Marker freezes VS for a few seconds

### ISSUE THREAD

**Issue by xuesky** [wmjordan/Codist#268]
插件很好用，在使用的过程中发现鼠标点击==或!=条件表达式时会发生卡顿

**Comment by wmjordan** [comment]
我用了这么多年都没遇到你说的情况。

issue 中提供的信息太少了，无法重现你的问题。

**Comment by xuesky** [comment]
@wmjordan 特别是`if (info == null)
                        {
                            recipeInfos.Add(recipeInfo);
                        }`这种判断为null的情况，第次都会卡顿

**Comment by wmjordan** [comment]
请看看：

1. 正在编辑的解决方案，其代码规模有多大？
2. 是否每个项目都会出现这样的现象？
3. 如果换掉字体，不用 Fira Code，是否还会出现卡顿？
4. 鼠标移到“==”出现上述卡顿后，是否能显示与等号相关的代码提示？
5. 禁用 Codist 的语法突出显示之后，是否还会出现此问题？
6. 禁用 Codist 的超级代码提示之后，是否还会出现此问题？

**Comment by wmjordan** [comment]
请看看：

1. 正在编辑的解决方案，其代码规模有多大？
2. 是否每个项目都会出现这样的现象？
3. 如果换掉字体，不用 Fira Code，是否还会出现卡顿？
4. 鼠标移到“==”出现上述卡顿后，是否能显示与等号相关的代码提示？
5. 禁用 Codist 的语法突出显示之后，是否还会出现此问题？
6. 禁用 Codist 的超级代码提示之后，是否还会出现此问题？

**Comment by wmjordan** [comment]
我在我的电脑上安装了 Fira Code 并使用它作为代码窗口的字体，我所编辑的解决方案里也有上千个文件了，点击任何逻辑相等或不等的位置，还是没有遇到卡顿现象。

**Comment by xuesky** [comment]
> 请看看：
> 
> 1. 正在编辑的解决方案，其代码规模有多大？
> 2. 是否每个项目都会出现这样的现象？
> 3. 如果换掉字体，不用 Fira Code，是否还会出现卡顿？
> 4. 鼠标移到“==”出现上述卡顿后，是否能显示与等号相关的代码提示？
> 5. 禁用 Codist 的语法突出显示之后，是否还会出现此问题？
> 6. 禁用 Codist 的超级代码提示之后，是否还会出现此问题？

1.编辑的项目确实有点大，直接会出现把VS卡死几秒钟
2.我找开其他小型项目，也会出现短暂的卡顿
3.跟字体无关
4.鼠标移到“==”出现上述卡顿后，是否能显示与等号相关的代码提示？---->不会，是造成VS假死几秒钟
5.禁用就不会出现这个问题
6.经过我逐个的插件功能测试，如果取消滚动条标记特性，就不会卡顿了

**Comment by wmjordan** [comment]
滚动条标记中有好几项，例如行号、选中内容、注释、成员声明线等等，请测试一下是哪项可能造成卡顿

**Comment by xuesky** [comment]
> 滚动条标记中有好几项，例如行号、选中内容、注释、成员声明线等等，请测试一下是哪项可能造成卡顿

选择的时候会卡顿，谢谢你提醒了我，因我在选择代码的时候，如:if (info == null) { recipeInfos.Add(recipeInfo); }也会造成明显卡顿，从前往后，从后往前选择都会出现这种情况

**Comment by wmjordan** [comment]
我拿了一个有将近6000行的代码文件来编辑，还是重现不出你的问题。
在点击鼠标的过程中，成员声明线的内容不会变化，应该不会造成卡顿。
一般来说可能是匹配符号的滚动条标记会消耗比较多的CPU。

**Comment by xuesky** [comment]
> 我拿了一个有将近6000行的代码文件来编辑，还是重现不出你的问题。 在点击鼠标的过程中，成员声明线的内容不会变化，应该不会造成卡顿。 一般来说可能是匹配符号的滚动条标记会消耗比较多的CPU。

经过多次测试，是滚动条标记里的->匹配符号，去掉就不卡顿了

**Comment by wmjordan** [comment]
匹配符号造成的卡顿消失后，是否可把整个滚动条截图下来给我看看，一共匹配了多少个符号

**Comment by xuesky** [comment]
<img width="139" alt="微信图片_20230520105009" src="https://github.com/wmjordan/Codist/assets/1439285/0bf6bf49-fea3-4a36-b907-078884635c16">


> 匹配符号造成的卡顿消失后，是否可把整个滚动条截图下来给我看看，一共匹配了多少个符号

**Comment by xuesky** [comment]
多点几次就卡死了，就是判断条件里的==null，！=null会卡，类似，if(a=="b")这种判断条件又不会卡

**Comment by xuesky** [comment]
<img width="165" alt="Snipaste_2023-05-20_11-01-21" src="https://github.com/wmjordan/Codist/assets/1439285/e5244eda-59a0-4737-b22b-d1edfb9525f0">

**Comment by wmjordan** [comment]
啊，这文件里才那么一点儿代码行数。

两等号左边的类型是否有“==”和“!=”的运算符重载？

**Comment by xuesky** [comment]
> 啊，这文件里才那么一点儿代码行数。
> 
> 两等号左边的类型是否有“==”和“!=”的运算符重载？

没有重载过，都是用默认行为

**Comment by xuesky** [comment]
<img width="194" alt="微信图片_20230520105009" src="https://github.com/wmjordan/Codist/assets/1439285/825c7532-6cf9-4395-a8f5-5395a238f3f5">
其实这个文件还是在呢，因为用的partial，分文件处理的，我在小项目的单个文件也会存在这个问题，应该跟代码行数没有关系

**Comment by wmjordan** [comment]
两等号左边的类型是什么类型呢？

**Comment by xuesky** [comment]
<img width="654" alt="Snipaste_2023-05-20_11-28-07" src="https://github.com/wmjordan/Codist/assets/1439285/7aa29414-82fd-42a7-8d4a-28b4be0d6821">
一个简单的类型都会卡1S

**Comment by wmjordan** [comment]
在你的机器上貌似有太多的任务跑到主线程上执行了，我试试调整代码，回头再请你测试一下

**Comment by wmjordan** [comment]
请下载上面的 Beta 7.5 看看此问题是否能得到改善

**Comment by xuesky** [comment]
> 请下载上面的 Beta 7.5 看看此问题是否能得到改善

OK

**Comment by xuesky** [comment]
<img width="164" alt="Snipaste_2023-05-20_15-31-29" src="https://github.com/wmjordan/Codist/assets/1439285/bdb4adda-0408-4912-abd6-c54949de6fed">
下载的8777，还是卡呢

**Comment by wmjordan** [comment]
请打开 Visual Studio 的选项对话框，找到 Codist 的配置节，点击打开配置文件夹按钮，把配置文件上传到这里

**Comment by xuesky** [comment]
> 请打开 Visual Studio 的选项对话框，找到 Codist 的配置节，点击打开配置文件夹按钮，把配置文件上传到这里

我看了下VS里怎么还是7.4，我先卸载了再试下

**Comment by xuesky** [comment]
{
  "Version": "7.4.0",
  "Labels": [
    {
      "Label": "!",
      "StyleID": "Emphasis"
    },
    {
      "Label": "#",
      "StyleID": "Emphasis"
    },
    {
      "Label": "?",
      "StyleID": "Question"
    },
    {
      "Label": "!?",
      "StyleID": "Exclamation"
    },
    {
      "Label": "x",
      "IgnoreCase": true,
      "StyleID": "Deletion"
    },
    {
      "Label": "+++",
      "StyleID": "Heading1"
    },
    {
      "Label": "!!",
      "StyleID": "Heading1"
    },
    {
      "Label": "++",
      "StyleID": "Heading2"
    },
    {
      "Label": "+",
      "StyleID": "Heading3"
    },
    {
      "Label": "-",
      "StyleID": "Heading4"
    },
    {
      "Label": "--",
      "StyleID": "Heading5"
    },
    {
      "Label": "---",
      "StyleID": "Heading6"
    },
    {
      "AllowPunctuationDelimiter": true,
      "Label": "TODO",
      "IgnoreCase": true,
      "StyleID": "ToDo"
    },
    {
      "AllowPunctuationDelimiter": true,
      "Label": "TO-DO",
      "IgnoreCase": true,
      "StyleID": "ToDo"
    },
    {
      "AllowPunctuationDelimiter": true,
      "Label": "undone",
      "IgnoreCase": true,
      "StyleID": "Undone"
    },
    {
      "AllowPunctuationDelimiter": true,
      "Label": "NOTE",
      "IgnoreCase": true,
      "StyleID": "Note"
    },
    {
      "AllowPunctuationDelimiter": true,
      "Label": "HACK",
      "IgnoreCase": true,
      "StyleID": "Hack"
    }
  ],
  "QuickInfo": {},
  "Styles": [
    {
      "Key": "struct name",
      "ForegroundColor": "#4EB0C9"
    },
    {
      "Key": "interface name",
      "ForegroundColor": "#00ACFF"
    },
    {
      "Key": "enum name",
      "ForegroundColor": "#C94EC9"
    },
    {
      "Key": "delegate name",
      "ForegroundColor": "#B5FFFF",
      "BackgroundColor": "#80004040",
      "BackgroundEffect": "ToBottom"
    },
    {
      "Key": "Number",
      "Bold": true
    },
    {
      "Key": "preprocessor text",
      "Bold": true,
      "ForegroundColor": "#FFFFFF",
      "BackgroundColor": "#0080FF"
    },
    {
      "Key": "comment",
      "Italic": true,
      "ForegroundColor": "#DF"
    },
    {
      "Key": "unnecessary code",
      "Strikethrough": true
    },
    {
      "Key": "Codist: Emphasis",
      "Bold": true,
      "FontSize": 7.0
    },
    {
      "Key": "Codist: Question",
      "ForegroundColor": "#9370DB"
    },
    {
      "Key": "Codist: Exclamation",
      "ForegroundColor": "#F9FF0080"
    },
    {
      "Key": "Codist: Deletion",
      "Strikethrough": true,
      "ForegroundColor": "#808080"
    },
    {
      "Key": "Codist: Task - ToDo",
      "ForegroundColor": "#CCCCCC",
      "BackgroundColor": "#800000A0"
    },
    {
      "Key": "Codist: Task - Note",
      "Bold": true,
      "ForegroundColor": "#000000",
      "BackgroundColor": "#FFA500"
    },
    {
      "Key": "Codist: Task - Hack",
      "ForegroundColor": "#00F279",
      "BackgroundColor": "#004000"
    },
    {
      "Key": "Codist: Task - Undone",
      "ForegroundColor": "#A4AFD1",
      "BackgroundColor": "#714136"
    },
    {
      "Key": "Codist: Heading 1",
      "FontSize": 12.0
    },
    {
      "Key": "Codist: Heading 2",
      "FontSize": 8.0
    },
    {
      "Key": "Codist: Heading 3",
      "FontSize": 4.0
    },
    {
      "Key": "Codist: Heading 4",
      "FontSize": -1.0,
      "ForegroundColor": "#008000"
    },
    {
      "Key": "Codist: Heading 5",
      "FontSize": -2.0,
      "ForegroundColor": "#008000"
    },
    {
      "Key": "Codist: Heading 6",
      "FontSize": -3.0,
      "ForegroundColor": "#008000"
    },
    {
      "Key": "Codist: Task 1",
      "Italic": false,
      "FontSize": 10.0,
      "ForegroundColor": "#800000",
      "BackgroundColor": "#FF80FF"
    },
    {
      "Key": "Codist: Task 2",
      "Italic": false,
      "FontSize": 7.0,
      "ForegroundColor": "#F9C6C6",
      "BackgroundColor": "#FF80FF",
      "BackgroundEffect": "ToBottom"
    },
    {
      "Key": "Codist: Task 3",
      "Bold": true,
      "Italic": false,
      "FontSize": 2.0,
      "ForegroundColor": "#FF0000",
      "BackgroundColor": "#FFFF80"
    },
    {
      "Key": "C#: Control flow keyword",
      "Italic": true,
      "FontSize": 2.0,
      "ForegroundColor": "#E28E3A"
    },
    {
      "Key": "C#: Abstraction keyword",
      "Bold": true,
      "ForegroundColor": "#0060BF"
    },
    {
      "Key": "C#: Branching keyword",
      "ForegroundColor": "#8080FF"
    },
    {
      "Key": "C#: Loop keyword",
      "Bold": true,
      "ForegroundColor": "#40CFFF"
    },
    {
      "Key": "C#: Type cast keyword",
      "Bold": true,
      "ForegroundColor": "#00B900"
    },
    {
      "Key": "C#: Resource keyword",
      "Bold": true,
      "ForegroundColor": "#CF3030"
    },
    {
      "Key": "C#: Declaration",
      "FontSize": 8.0
    },
    {
      "Key": "C#: Member declaration",
      "FontSize": 5.0
    },
    {
      "Key": "C#: Declaration brace",
      "FontSize": 2.0
    },
    {
      "Key": "C#: Static member",
      "Bold": false,
      "Underline": true
    },
    {
      "Key": "C#: Override member",
      "BackgroundColor": "#E1004F15",
      "BackgroundEffect": "ToBottom"
    },
    {
      "Key": "C#: Virtual member",
      "BackgroundColor": "#000040",
      "BackgroundEffect": "ToBottom"
    },
    {
      "Key": "C#: Local declaration",
      "Italic": false,
      "BackgroundColor": "#7F606000"
    },
    {
      "Key": "C#: Local variable",
      "Italic": true,
      "ForegroundColor": "#D4D4D4"
    },
    {
      "Key": "C#: Label",
      "Bold": true,
      "ForegroundColor": "#FFFFFF",
      "BackgroundColor": "#0000FF"
    },
    {
      "Key": "C#: Attribute notation",
      "Italic": true,
      "FontSize": -2.0,
      "ForegroundColor": "#BF808080"
    },
    {
      "Key": "C#: Namespace",
      "ForegroundColor": "#808080"
    },
    {
      "Key": "C#: Sealed class or member",
      "BackgroundColor": "#4F0000",
      "BackgroundEffect": "ToBottom"
    },
    {
      "Key": "C#: Event",
      "ForegroundColor": "#22FF91",
      "BackgroundColor": "#80004000",
      "BackgroundEffect": "ToBottom"
    },
    {
      "Key": "C#: Type parameter",
      "ForegroundColor": "#FFB693"
    },
    {
      "Key": "C#: Constructor method",
      "ForegroundColor": "#DB8024"
    },
    {
      "Key": "C#: Field",
      "Italic": true,
      "ForegroundColor": "#ACAC00"
    },
    {
      "Key": "C#: Const field",
      "ForegroundColor": "#C94EC9"
    },
    {
      "Key": "C#: Read-only field",
      "Italic": false,
      "ForegroundColor": "#808000"
    },
    {
      "Key": "C#: Volatile field",
      "BackgroundColor": "#808000",
      "BackgroundEffect": "ToBottom"
    },
    {
      "Key": "C#: Property",
      "ForegroundColor": "#7ABCFE"
    },
    {
      "Key": "C#: Method",
      "ForegroundColor": "#E46B6B"
    },
    {
      "Key": "C#: Extension method",
      "Italic": true
    },
    {
      "Key": "C#: Extern method",
      "BackgroundColor": "#7D800000",
      "BackgroundEffect": "ToBottom"
    },
    {
      "Key": "C#: Parameter",
      "Italic": true,
      "ForegroundColor": "#FF44A2"
    },
    {
      "Key": "C#: XML Doc",
      "FontSize": -1.0,
      "ForegroundColor": "#DF"
    },
    {
      "Key": "xml doc comment - name",
      "ForegroundColor": "#7EAB6D"
    },
    {
      "Key": "xml doc comment - attribute name",
      "Italic": true
    },
    {
      "Key": "xml doc comment - cdata section",
      "ForegroundColor": "#6AFF6A"
    },
    {
      "Key": "Codist: Highlight 1",
      "BackgroundColor": "#B91D06"
    },
    {
      "Key": "Codist: Highlight 2",
      "BackgroundColor": "#B97606"
    },
    {
      "Key": "Codist: Highlight 3",
      "BackgroundColor": "#B9B906"
    },
    {
      "Key": "Codist: Highlight 4",
      "BackgroundColor": "#1DB906"
    },
    {
      "Key": "Codist: Highlight 5",
      "BackgroundColor": "#06B984"
    },
    {
      "Key": "Codist: Highlight 6",
      "BackgroundColor": "#068CB9"
    },
    {
      "Key": "Codist: Highlight 7",
      "BackgroundColor": "#6006B9"
    },
    {
      "Key": "Codist: Highlight 8",
      "BackgroundColor": "#5F5F5F"
    },
    {
      "Key": "Codist: Highlight 9",
      "BackgroundColor": "#FFFFFF"
    },
    {
      "Key": "C#: Metadata symbol",
      "Bold": true
    }
  ],
  "MarkerSettings": [],
  "SearchEngines": [
    {
      "Name": "Bing",
      "Pattern": "https://www.bing.com/search?q=%s"
    },
    {
      "Name": "Google",
      "Pattern": "https://www.google.com/search?q=%s"
    },
    {
      "Name": "StackOverflow",
      "Pattern": "https://stackoverflow.com/search?q=%s"
    },
    {
      "Name": "GitHub",
      "Pattern": "https://github.com/search?q=%s"
    },
    {
      "Name": "CodeProject",
      "Pattern": "https://www.codeproject.com/search.aspx?q=%s&x=0&y=0&sbo=kw"
    },
    {
      "Name": ".NET Core Source",
      "Pattern": "https://source.dot.net/#q=%s"
    },
    {
      "Name": ".NET Framework Source",
      "Pattern": "https://referencesource.microsoft.com/#q=%s"
    }
  ],
  "WrapTexts": [
    {
      "Name": "\"\"",
      "Pattern": "\"$\"",
      "Indicator": "$"
    },
    {
      "Name": "()",
      "Pattern": "($)",
      "Indicator": "$"
    },
    {
      "Name": "''",
      "Pattern": "'$'",
      "Indicator": "$"
    },
    {
      "Name": "[]",
      "Pattern": "[$]",
      "Indicator": "$"
    },
    {
      "Name": "{}",
      "Pattern": "{$}",
      "Indicator": "$"
    },
    {
      "Name": "<>",
      "Pattern": "<$>",
      "Indicator": "$"
    },
    {
      "Name": "%%",
      "Pattern": "%$%",
      "Indicator": "$"
    }
  ],
  "SymbolReferenceMarkerSettings": {
    "ReferenceMarkerColor": "#00FFFF",
    "WriteMarkerColor": "#F0E68C"
  }
}

**Comment by wmjordan** [comment]
没错，是7.4的，Beta 版是只更改修订号，不会更改版本号的

**Comment by wmjordan** [comment]
使用了你的配置文件，还是无法重现你遇到的问题。
你的 VS 上还安装了哪些插件呢？

**Comment by xuesky** [comment]
<img width="337" alt="Snipaste_2023-05-20_15-54-59" src="https://github.com/wmjordan/Codist/assets/1439285/6b80e89a-b822-490d-8569-4c76ede980cc">
<img width="332" alt="Snipaste_2023-05-20_15-55-22" src="https://github.com/wmjordan/Codist/assets/1439285/bde6347d-772a-425b-89be-7201e376046f">
<img width="333" alt="Snipaste_2023-05-20_15-56-34" src="https://github.com/wmjordan/Codist/assets/1439285/ae148344-7188-4805-bd56-bc62b20c8668">

**Comment by wmjordan** [comment]
装了上面好几个插件，还是重现不了你的问题

**Comment by xuesky** [comment]
好的，谢谢，那就不找原因了，我把滚动条关了就不会发生那种情况

**Comment by wmjordan** [comment]
请下载新的Beta版看看是否能解决这个问题

**Comment by xuesky** [comment]
> 请下载新的Beta版看看是否能解决这个问题

试了，还是会卡

**Comment by wmjordan** [comment]
是否能试试禁用其它插件，看看是否会卡

**Comment by xuesky** [comment]
> 是否能试试禁用其它插件，看看是否会卡

插件全部禁用还是会卡

**Comment by wmjordan** [comment]
太奇怪了。
是否可点击“工具”菜单，将Visual Studio的配置导出来？我把它导进来试试，看是否与VS的配置有关。

**Comment by xuesky** [comment]
[Exported-2023-05-22.zip](https://github.com/wmjordan/Codist/files/11527601/Exported-2023-05-22.zip)

**Comment by wmjordan** [comment]
看来与线程调度有关，和配置和插件似乎都无关。我用一个 Debug 版本的 VS 实例重现了这个问题。

**Comment by xuesky** [comment]
> 看来与线程调度有关，和配置和插件似乎都无关。我用一个 Debug 版本的 VS 实例重现了这个问题。

OK,大神牛B，找到问题就好

**Comment by wmjordan** [comment]
之前也遇到这种问题，异步方法有时会跑到用户界面线程上运行，导致界面卡住。
请再下载个新版本看看。这个版本在我这边不会导致点击双等号时卡住，你试试看。

**Comment by xuesky** [comment]
> 之前也遇到这种问题，异步方法有时会跑到用户界面线程上运行，导致界面卡住。 请再下载个新版本看看。这个版本在我这边不会导致点击双等号时卡住，你试试看。

在a==null时还是会卡，其他情况不会

**Comment by wmjordan** [comment]
我拿台笔记本电脑，在Debug模式下编辑Roslyn这个大型解决方案都不会卡——除了刚刚打开项目的时候Roslyn还未完全加载解决方案时反应慢一些。
你的解决方案里有多少项目、多少代码文件啊？

**Comment by xuesky** [comment]
> 我拿台笔记本电脑，在Debug模式下编辑Roslyn这个大型解决方案都不会卡——除了刚刚打开项目的时候Roslyn还未完全加载解决方案时反应慢一些。 你的解决方案里有多少项目、多少代码文件啊？

给你个向日葵，你试试，呵呵

**Comment by wmjordan** [comment]
> > 我拿台笔记本电脑，在Debug模式下编辑Roslyn这个大型解决方案都不会卡——除了刚刚打开项目的时候Roslyn还未完全加载解决方案时反应慢一些。 你的解决方案里有多少项目、多少代码文件啊？
> 
> 我拿小项目来试都会卡，哈哈，a==null跟a==1来比较明显会有卡顿

可以弄一个在你那边会卡的演示型小项目过来吗？

**Comment by xuesky** [comment]
> > > 我拿台笔记本电脑，在Debug模式下编辑Roslyn这个大型解决方案都不会卡——除了刚刚打开项目的时候Roslyn还未完全加载解决方案时反应慢一些。 你的解决方案里有多少项目、多少代码文件啊？
> > 
> > 
> > 我拿小项目来试都会卡，哈哈，a==null跟a==1来比较明显会有卡顿
> 
> 可以弄一个在你那边会卡的演示型小项目过来吗？

这个还是涉及到我的业务项目，没办法剥离的，我新建个控制台项目，又不卡

**Comment by wmjordan** [comment]
刚刚上传了一个新的测试版，在我这边测试时，滚动条标记功能已经不再在计算匹配符号时占用主线程。
请试试看是否有改善。

**Comment by xuesky** [comment]
OK，我试下

**Comment by xuesky** [comment]
试过了，不卡了，最近太忙，一直没回你，呵呵

**Comment by wmjordan** [comment]
好的，谢谢反馈
