### ISSUE TITLE
Suppress Quick Info for a short time/Move Quick Info popup away from mouse

### ISSUE THREAD

**Issue by wmjordan** [wmjordan/Codist#270]
The following request comes from أشرف صبري in the VS Marketplace:
I hope if there's a setting allowing delaying the quick info tooltip to something like 200 or 300 milliseconds. Because the tooltip keeps chasing me while I move mouse cursor over code, sometimes hindering me from selecting a piece of code. I know you added a setting to make the tooltip appear only if the CTRL key is pressed, but I find it more convenient to make it appear automatically but delayed.

**Comment by wmjordan** [comment]
@fitdev, @ineedhelp

A friend posted the above comment.
Have you ever met with the aforementioned situation?
Can you share your suggestion about this?

**Comment by wmjordan** [comment]
@Ineedhelp

Thank you for your comment and the link.
It seems to me that the Quick Info is already displayed WITHOUT any delay on my side. I set some triggers into a Quick Info provider in Codist, once I hover the mouse onto a symbol, the provider is immediately requested to provide item for the Quick Info.
Since the calculation of items needs some time, so you might experience some delay (on my VS, about 150ms or so).

If my analysis is correct, it is possible to customize the delay with little effort.

**Comment by fitdev** [comment]
If anything I am mostly unhappy with VS's tooltip positioning, which does interfere with code selection and is quite annoying as it happens quite often in my use. So, instead of configuring the delay, I would rather have the tip be displayed at an offset from the current pointer position, but in one of your past replies you said that this is not possible in VS. So, a customizable delay would be the next best thing in this case (though in my case there already seems to be ~200ms delay).

**Comment by wmjordan** [comment]
Thank you for your comment, my friends.

I am very much bothered by the Quick Info positioning as well.
Having Super Quick Info, the area the Quick Info takes gets larger and this problem gets even worse.

Before finding out a way to move the Popup window of the Quick Info to the right place, other than the NNNms's delay, I have another idea:
Press the `Esc` key before you begin to select, or being bothered by the Quick Info that stands in your way--the Esc key can hide the Quick Info immediately as well. After pressing that key, Quick Info will definitely NOT show up for 5 seconds (or some other value that you can configure), so you can start to select.

**Comment by wmjordan** [comment]
?
@IneedHelp 
How do you "spam" the Esc key.

**Comment by IneedHelp** [comment]
I press it multiple times in the context of the Text Editor. An example would be navigation cancelling or completion I do with Coderush, navigation through markers (which are collected using Esc) and various other operations (even hiding the tooltip).

The delay you want to implement by pressing Esc could be useful, but I suggest you add it as an opt-in option, not as default/standard behavior.

**Comment by wmjordan** [comment]
@IneedHelp 
Understood. I've already trashed the code that Esc temporarily disables Quick Info, since I have found the fix below.

@fitdev 
Your opinion is absolutely right. The underlying problem is the positioning of the Quick Info popup.
I figured out a way to hack into the popup window and managed to move it out of our way when we are to select something with the mouse cursor.

Without the fix, the original VS Quick Info is right in the way:
![image](https://github.com/wmjordan/Codist/assets/12182730/3f0b76de-a310-4d03-92cf-b476fecbdcab)

With the fix and Super Quick Info:
![image](https://github.com/wmjordan/Codist/assets/12182730/a2a2019c-6bf9-42ca-92e6-b76eff3994fc)

**Comment by fitdev** [comment]
I am very glad you were able to find a solution. I will give it a try soon! Ideally it should also be an option, so that users can revert to default behavior in the rare cases where it won;t properly position itself (which as I understand can be tricky due to varying tooltip and desktop sizes, multiple monitors, dpis, etc.).

**Comment by fitdev** [comment]
Just tried the new beta! Seems to work really well! Excellent work! My only suggestion may be to offset the tooltip a tiny bit more: perhaps a few pixels vertically (away from the current line), and ~1 character-width horizontally away from the mouse pointer, because now it still seems to be too close to the mouse pointer.

**Comment by wmjordan** [comment]
> a few pixels vertically (away from the current line), and ~1 character-width horizontally away from the mouse pointer

Still impossible to do so at this moment:
The trigger span and the popup have to adhere together.
Once there is just a single pixel's gap between the trigger span and the popup, while the cursor leaves the text span, the popup disappears immediately, before the cursor catch up on the popup.

**Comment by fitdev** [comment]
Oh I see. I did not realize it is based on a span of text. Thought it is purely in terms of XY coordinates.

**Comment by fitdev** [comment]
I see. Never mind then. What you did already is great compared to what it was! Thank you!

**Comment by wmjordan** [comment]
@fitdev 
I managed to find out a way to move the Quick Info a bit rightwards. Please try the new beta.
However, if the Quick Info is big, it still have a chance to be placed under the mouse cursor.

**Comment by fitdev** [comment]
Now I see very often larger tooltips being displayed on another screen. This is not ideal. Perhaps you can then revert previous behavior as in 8839.

**Comment by fitdev** [comment]
![Screenshot_20230602_142618](https://github.com/wmjordan/Codist/assets/8166847/3b2f7e1d-67b4-4d2a-9835-a061676c25ee)

**Comment by fitdev** [comment]
But I mean it was never an issue previously. So perhaps it would be easier for you to simply revert to the previous behavior in such cases.

**Comment by wmjordan** [comment]
I have made another beta which truncates the popup if there is no enough vertical room on the screen.
Please try it and compare what's the better.

**Comment by fitdev** [comment]
Thank you for a quick fix! This now works well - it is displayed on the same screen, though it does appear right under the mouse pointer (so the mouse pointer is located in the middle of a tooltip), but it is better than it being displayed on another screen.

**Comment by wmjordan** [comment]
Yes, I deliberately place the popup below, and align to, the left bottom of the text, instead the original place (top left corner under mouse cursor).
So, we can move to the big button and symbol name in a shorter distance.
