### ISSUE TITLE
[Feature request] auto complete only on one tab click

### ISSUE THREAD

**Issue by BachiMjavanadze** [wmjordan/Codist#273]
By default, you need to click `Tab` button twice to insert a snippet. Please add option to your extension (or create new extension) for inserting snippets on single `Tab` click, like in `VSCode`.

**Comment by IneedHelp** [comment]
I'm not speaking on behalf of @wmjordan , but I think you're missing the point of what Codist is and does, which is mainly 
![image](https://github.com/wmjordan/Codist/assets/1366970/6a514c84-1d38-4c0f-960c-6b3ec257d132)

**Comment by IneedHelp** [comment]
> It is just a `Feature request`, maybe he will implement it

I get it, but it seems out of scope, especially when you say "or create new extension".

**Comment by wmjordan** [comment]
I have the same feeling as @IneedHelp.

1. It saves you little time. 
2. I don't care pressing Tab twice at all.
3. The snippet thing is still a mystery to me. Mission impossible at this moment even if I have any motivation to do so.

**Comment by BachiMjavanadze** [comment]
@wmjordan I did it: [Auto Close & Surround Punctuations](https://marketplace.visualstudio.com/items?itemName=BachiMjavanadze.AutoCloseAndSurroundPunctuations). Fill free to include it to your extension
