### ISSUE TITLE
[Feature request] Var CodeLens

### ISSUE THREAD

**Issue by BachiMjavanadze** [wmjordan/Codist#275]
Please add `var` CodeLens feature. Give us ability to set font color and size. also give us ability to show only last part of the type

![image](https://github.com/wmjordan/Codist/assets/38082501/733f7b20-bbbc-4749-b53d-8667ff639337)

**Comment by wmjordan** [comment]
There's already an extension for this job.
https://marketplace.visualstudio.com/items?itemName=AlexanderGayko.VarAdorner

**Comment by wmjordan** [comment]
Since:
1. CodeLens takes extra space, less code will be displayed in one screen
2. when I do care for the concrete type of a `var`, Super Quick Info has done its job of showing concrete type for a `var` type, plus extra information, for instance, custom attributes, interface implementation, XML Doc, base types etc,

I have little motivation to implement this feature. You'd better contact the author to improve his extension.

**Comment by BachiMjavanadze** [comment]
> There's already an extension for this job. https://marketplace.visualstudio.com/items?itemName=AlexanderGayko.VarAdorner

I know about it but it doesn’t work correctly. it didn’t even have its own repository on github, I asked and the dude did it. He promised to fix it but seems to have forgotten about it.
this is my bug report: [https://github.com/AdmiralSnyder/VarCodeLensExtension/issues/1](https://github.com/AdmiralSnyder/VarCodeLensExtension/issues/1)

**Comment by BachiMjavanadze** [comment]
> Since:
> 
> 1. CodeLens takes extra space, less code will be displayed in one screen

this feature will not work by default, someone wants to turn it on and someone will turn it off

**Comment by laicasaane** [comment]
There are already options to show inline hints in Visual Studio 2022. This is not what you want?
![image](https://github.com/wmjordan/Codist/assets/1594982/a251dc6e-fa02-4927-8ae4-3089083ebb82)

**Comment by BachiMjavanadze** [comment]
@laicasaane 
I know this function but `VarCodeLence` is more convenient for me:

![image](https://github.com/wmjordan/Codist/assets/38082501/b481d5ee-83f6-407d-b3cb-bff27dbcae03)

**Comment by wmjordan** [comment]
There's no API to change the appearance of code lens labels.
I'll give up.
