### ISSUE TITLE
Change font and style of super quick info?

### ISSUE THREAD

**Issue by wmjordan** [wmjordan/Codist#276]
is it possible to change font and style of super quick info?

_Originally posted by @yekanchi in https://github.com/wmjordan/Codist/issues/267#issuecomment-1568777199_

**Comment by wmjordan** [comment]
The font in Super Quick Info is inconsistent with the Editor Tooltip font setting in VS today.
It is better to use that setting.

**Comment by yekanchi** [comment]
I think the current implementation which control the style with Editor Tooltip does not give the developer full control. for example for someone the icon size might seem quite large(there is no control over it).
 I suggest to add more settings over Quick Info Style in Codist Settings.

**Comment by wmjordan** [comment]
> for example for someone the icon size might seem quite large

Do you mean the big button in C# Quick Info?

**Comment by yekanchi** [comment]
yes this icon:
![image](https://github.com/wmjordan/Codist/assets/25511175/5fae47f1-2010-42e7-aa8b-219d61f46977)

**Comment by wmjordan** [comment]
Well. The big button just looks perfect and works perfectly for me. 😎 It is big so it is easy to click. I access functions in its popup menu very frequently. If it is small I will feel uncomfortable.

I will remember it. I will add customization for it when I have time or some more users complain about it.

However, it looks strange that the "Student" on your tip looks too small. It is supposed to be bigger as well.
<img width="169" alt="image" src="https://github.com/wmjordan/Codist/assets/12182730/5fa849b6-31c4-4aa0-a598-0d9c4e590b92">

**Comment by yekanchi** [comment]
> 

yes it's small because I edited it with hope to make icon smaller.
then it's fine.

**Comment by wmjordan** [comment]
@yekanchi 
Please download the new beta which automatically sizes the Big Button according to the Editor ToolTip font size.

**Comment by yekanchi** [comment]
> @yekanchi Please download the new beta which automatically sizes the Big Button according to the Editor ToolTip font size.

nice work.
