### ISSUE TITLE
能否实现自动插入包围的功能

### ISSUE THREAD

**Issue by heartacker** [wmjordan/Codist#277]
1. 在VSCode 中。 如果你选中 一段文字， 比如 
`var a = abc;`
然后你选中 abc,并用键盘输入 "  。他会自动在abc 前后包围 
变为
`var a = "abc";`

这是一个非常实用的功能。  也就是 可以匹配的一对符号 如",',{,<,[, 等等都是可以的，

但是在VS 2022 里面一直找不到这个功能。
这个实在是太困惑了。

2. 请求可以在这这里实现这个功能，
非常感谢

**Comment by wmjordan** [comment]
早在几个星期前就实现了，但是在使用过程中，我们发现这个功能不是很好使。这里有相关讨论：
https://github.com/wmjordan/Codist/issues/254#issuecomment-1542317811
https://github.com/wmjordan/Codist/issues/254#issuecomment-1549549807

一开始我觉得这功能挺有趣的，软件集市上有现成的插件已经实现这个功能了。你可以在前面的讨论中看到相关插件。我觉得在 Codist 里面实现这功能也不难，于是就自己做了一个，甚至增加了配对插入中文括号、引号、书名号等等功能。但我用了这个功能一个星期、一位测试用户用了一天之后，我们发现经常发生这样的事情：选择一个表达式，本来想插入一个符号来替换掉这个表达式的，结果成了插入一对符号来包围这个表达式，用着用着，发现这功能捣乱的次数比它派上用场的次数还多。于是我就没有将它放到 7.4 版。

**Comment by heartacker** [comment]
>我们发现经常发生这样的事情：选择一个表达式，本来想插入一个符号来替换掉这个表达式的，结果成了插入一对符号来包围这个表达式，用着用着，发现这功能捣乱的次数比它派上用场的次数还多。

这个确实是个问题。 但是我觉得更是习惯问题
我用VSCode, 用惯了，遇到他这个场景，我觉得我会
选->删->输
而不是 选->输

**Comment by wmjordan** [comment]
你先装个其它插件用用，例如AutoSurround、[Surrounder](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.Surrounder)等等

**Comment by wmjordan** [comment]
Codist 的智能工具条也有个插入包围文本的功能。

选中文本后，点击下图所示的按钮：
<img width="394" alt="image" src="https://github.com/wmjordan/Codist/assets/12182730/6bace038-0b3f-493b-ae8a-c0edde004ed7">

右键点击：弹出候选菜单；
左键点击：插入上一次选中的项（默认是菜单中的第一项）。

**Comment by wmjordan** [comment]
我最近想到一种方法，用了几天，发现它似乎比较好地避免了插入功能在我需要覆盖文本时捣乱的情形。
请下载新的测试版试试看。

**Comment by wmjordan** [comment]
这个自动包围功能还支持中文的多种括号、引号和书名号。

**Comment by heartacker** [comment]
> 我最近想到一种方法，用了几天，发现它似乎比较好地避免了插入功能在我需要覆盖文本时捣乱的情形。 请下载新的测试版试试看。

有详细一丁点的介绍不？

**Comment by wmjordan** [comment]
你先下载新的测试版看看，先试用试用(#283)。
