### ISSUE TITLE
[Bug] Sub tooltip popup delay speed error

### ISSUE THREAD

**Issue by BachiMjavanadze** [wmjordan/Codist#279]
My Settings are:

`Super Quick Info` >` Delay Display` > `Deley time` = 500ms

But when I hover mouse cursor on the modal window on some entities (i.e. method Foo) then new modal window pops up immediately. Is it possible to delay it?

![image](https://github.com/wmjordan/Codist/assets/38082501/5903156f-a432-473c-b241-5a2037fd7834)

**Comment by wmjordan** [comment]
This issue unexpectedly took me **HOURS** to fix 😵  due to `DataTemplate`s or `Style`s in WPF do not allow hooking event handlers.

Please try the new beta version (#283).
