### ISSUE TITLE
Visual Studio Stoped responding for 8 seconds. Disabling the extension Codist 7.5.0.8911 might help

### ISSUE THREAD

**Issue by SlimeNull** [wmjordan/Codist#284]
![image](https://github.com/wmjordan/Codist/assets/69663231/404bd662-9726-4f8b-8056-beafd4130795)

**Comment by wmjordan** [comment]
Could you provide more info what you were doing while VS was not responding?

**Comment by wmjordan** [comment]
I found a problem in the symbol match marker in version 7.5 and uploaded a 8912 to the marketplace to fix the problem.

And now we have a beta 7.6. Please try the new beta which might have fixed this issue as well.

**Comment by wmjordan** [comment]
Have you tried the new release and how it works now?
