### ISSUE TITLE
每次更新完毕，打开 VS2022 打开一个弹窗，导致无法操作

### ISSUE THREAD

**Issue by heartacker** [wmjordan/Codist#285]
每次更新完毕，打开 VS2022 打开一个弹窗，导致无法操作,因为他默认现在在vs 2022的后面了。

所以导致我们一直点击 vs 2022 无法操作， 除非通过 alt+tab 将这个更新的提示切换到最前

![image](https://github.com/wmjordan/Codist/assets/1876302/fdcf4127-3f58-4d53-bfeb-2acdee668ca1)

**Comment by wmjordan** [comment]
谢谢告知。这是个烦人的问题。
下午发个新版本。

**Comment by heartacker** [comment]
嗯嗯，谢谢， 这个我一开始也搞了不明白，甚至用 任务管理器 将 vs 2022 kill 掉。

直到有一次， alt+tab

**Comment by wmjordan** [comment]
新的版本应该可以解决这个问题。
把这个提示小窗的属性改成置顶了。

我一直都禁用那个开始窗口，启动 VS 时直接进入空的开发环境。VS 最近的预览版还引入了新的开始页面（又回到 VS 2017 那种开始页面了），也不会受这个问题的影响。刚好在这里反馈的朋友似乎不少人都在用预览版，所以他们也没有发现这个问题。
