### ISSUE TITLE
checkbox 让人困惑

### ISSUE THREAD

**Issue by heartacker** [wmjordan/Codist#286]
一开始，看到这个么多 checkbox 搞得一头雾水

因为 checkbox 一般都是代表 使能/启用的意思，我一直在想如何开启，如果将所有勾选。

但是这里代表当前聚焦的意思（直没转过来）。

如果是聚焦选中的，应该使用 高亮等等，而不是  checkbox

![image](https://github.com/wmjordan/Codist/assets/1876302/b442f584-20d4-4325-9123-902dc55ab06c)

![image](https://github.com/wmjordan/Codist/assets/1876302/a5464b93-5b1a-4bdc-b7a8-d77d61490aff)

**Comment by wmjordan** [comment]
新的版本把复选框改成了 RadioButton
