### ISSUE TITLE
Auto Pair Punctuation doesn't work at all

### ISSUE THREAD

**Issue by DimitarCC** [wmjordan/Codist#290]
The title says it. It doesn't work at all in my case on Visual Studio 2022 Community.
When i select a text and press double quote for example it just crear the text and not surrounding it.

**Comment by wmjordan** [comment]
Have you enabled it in the Options page?
That feature is by default turned off.

**Comment by DimitarCC** [comment]
@wmjordan Yes it is enabled in settings but it doesn't work on my side.

**Comment by wmjordan** [comment]
That's weird.

That feature extends `ICommandHandler<TypeCharCommandArgs>` interface in VS. If some other extension happens to hook up that extension point and it is possible that the event is swallowed by that extension and Codist will not have a chance to play its role.

Is there any similar extension installed in your VS?

**Comment by DimitarCC** [comment]
Aha OK i understand. Maybe that is the case i will look is there other extension that can interfere with that.

**Comment by DimitarCC** [comment]
Well today i repaired my Visual studio installation which removed all plugins and settings from it. Then i installed only Codist and tried Auto pair punctuation functionality but it still doesn't work at all.

**Comment by wmjordan** [comment]
I tried your config.json file that you uploaded in another issue and it was working on my computer.
The Auto-pair function requires you to select something then input the start punctuation.
For instance,
````
1 + 1 = 2;
````
If you want to surround a pair of parentheses around `1 + 1`, you should select that expression first, then type the `(` character. Afterwards, you will see
````
(1 + 1) = 2;
````
