### ISSUE TITLE
"private member" comes with wrong foreground color

### ISSUE THREAD

**Issue by HeinzKessler** [wmjordan/Codist#292]
In my understanding, format settings add up from the lowest row in the list to the highest, so that every row modifies the format settings of the rows below it, see screenshot.
But wherever there is a "private member" attribute somewhere in the list, this fixes the foreground color to grey, regardless of the foreground color settings of the rows above.
In my case, "Method" should set the foreground color to dark orange, but "private member" below inhibits this and makes the foreground color stay grey. This also applies to private properties, fields etc. instead of methods.
Sometimes I manage to make it work correctly, but I can't tell how, and only until the next start of VS.
Note: The opacity of 12 for "private member" shall dim al subsequent colors if it's a private method, property etc.
Interestingly this bug only applies to the _foreground_ color, not the _background_ color.

![Codist2023-08-06_11-13-25](https://github.com/wmjordan/Codist/assets/24476114/74bba563-e0d9-4938-9c88-5d5f37add101)
[CodistStyles.zip](https://github.com/wmjordan/Codist/files/12269653/CodistStyles.zip)

I am using version 7.7. Beta

**Comment by wmjordan** [comment]
Do not set foreground color for the private member. It has higher precedence over method, field, property etc., so it can override your specific style on those elements.
There is opacity for background, just **below** the foreground opacity. If you want to dim the background, you should specify value for background opacity.

**Comment by wmjordan** [comment]
I altered the precedence of private member and sealed member. Now they have lower precedence.
Please try the new beta.

**Comment by wmjordan** [comment]
> If I click on “All Languages” in the menu on the left, VS freezes for about a minute, and then crashes.
> Shall I open a new issue for that?

Yes, please.

And please take a look at the Windows Event Viewer and find out corresponding entry there, where a stack trace is logged.
The stack trace can be helpful.
