### ISSUE TITLE
VS Freeze and Crash when clicking on "All Languages"

### ISSUE THREAD

**Issue by HeinzKessler** [wmjordan/Codist#293]
In the Codist configuration window, when I click on "All Languages", VS freezes for ~1 minute, then crashes.
Event view log entries are attached.
[Vscrash.txt](https://github.com/wmjordan/Codist/files/12288108/Vscrash.txt)

**Comment by wmjordan** [comment]
Thank you for taking time to help address this problem.

Please download the following version and try again.
Further investigation is required.
Error box will appear when it fails. Let's see which syntax style causes the problem.

[Codist.zip](https://github.com/wmjordan/Codist/files/12288296/Codist.zip)

**Comment by HeinzKessler** [comment]
Here comes the screenshot, where I mixed in the message box and the tooltip for "Invisible"
![VsCrashDiag](https://github.com/wmjordan/Codist/assets/24476114/c0718dd2-171c-4abf-85d9-2160f92f0d46)

**Comment by wmjordan** [comment]
Thank you very much.
The extra tooltip helps a lot!

Please download the new beta and see whether it works.

**Comment by HeinzKessler** [comment]
With the latest beta, it works correctly.

 

Thanks a lot!

 

Von: WMJ ***@***.***> 
Gesendet: Dienstag, 8. August 2023 11:08
An: wmjordan/Codist ***@***.***>
Cc: Heinz Kessler ***@***.***>; Author ***@***.***>
Betreff: Re: [wmjordan/Codist] VS Freeze and Crash when clicking on "All Languages" (Issue #293)

 

Thank you very much.
The extra tooltip helps a lot!

Please download the new beta and see whether it works.
