### ISSUE TITLE
v7.7 加载错误

### ISSUE THREAD

**Issue by mzy666888** [wmjordan/Codist#294]
![image](https://github.com/wmjordan/Codist/assets/2587129/19eda503-8f04-4c90-a53c-dc177dd6fa7d)

不知道为什么安装上7.7版本后，加载不上，弹出来如上错误。
更新后不起作用，重新卸载后在进行安装就出现这个问题了

**Comment by wmjordan** [comment]
请把上图所示的“ActivityLog.xml”文件压缩后发上来看看

**Comment by wmjordan** [comment]
谢谢告知，已重现故障

**Comment by wmjordan** [comment]
刚刚已上传了一个新版到 Release 以及 Visual Studio 的插件集市修复这个问题，请下载新的版本。
