### ISSUE TITLE
SyntaxHighliting doesnt work on VS2022 17.7.1

### ISSUE THREAD

**Issue by DimitarCC** [wmjordan/Codist#295]
Title say it all.

**Comment by wmjordan** [comment]
Please zip and upload the config.json file and let me test it.

**Comment by DimitarCC** [comment]
[Config.zip](https://github.com/wmjordan/Codist/files/12365751/Config.zip)

Here it is. I noticed that only Foreground color doesn't work. Background colors work just fine.
All was working on VS 17.7 and got broken on 17.7.1 (latest update)

**Comment by wmjordan** [comment]
Thank you for your file.
I saw that bug on my machine.

<img width="520" alt="image" src="https://github.com/wmjordan/Codist/assets/12182730/ea1ba730-a0f9-40c4-b30f-67a02d6819b9">

**Comment by wmjordan** [comment]
It seems to be a bug in VS.
Somehow the Formal language has gotten higher priority than C# method name--The latter is based from the former and expected to have higher priority.
<img width="398" alt="image" src="https://github.com/wmjordan/Codist/assets/12182730/c7714079-fb77-4dbb-864b-c6910bfb40f7">

At this time, you can remove the foreground color from Formal language. After that your colors will look right.

**Comment by DimitarCC** [comment]
Yup it works like that. Unfortunately, since its VS bug then Microsoft have to fix it.

**Comment by wmjordan** [comment]
Merged into #303.
