### ISSUE TITLE
"private member" foreground color doesnt work

### ISSUE THREAD

**Issue by Hakoyu** [wmjordan/Codist#296]
![image](https://github.com/wmjordan/Codist/assets/48956359/71e61527-e85d-44f1-81fa-0024108cb31c)

But background is work

![image](https://github.com/wmjordan/Codist/assets/48956359/a00bf90a-13e4-4326-8461-c273de7f20b6)

**Comment by Hakoyu** [comment]
Version: 7.7.1.9318

**Comment by wmjordan** [comment]
是这样设计的。
属性样式的优先级高于私有成员样式的优先级。

**Comment by Hakoyu** [comment]
但这样就不容易分辨出啥是私有了
有其他解决办法吗

**Comment by wmjordan** [comment]
如果私有成员样式的优先级超过了属性样式的优先级，那么你就无法分辨哪些是私有方法，哪些是私有字段，哪些是私有属性了。你可以考虑用斜体，或者别的字体，或者下划线（可以设置特定的下划线颜色），或者背景色等样式来标记私有成员。

**Comment by Hakoyu** [comment]
主要是之前橙色看习惯了还不适应
行 我换个法子
