### ISSUE TITLE
在 VS2022 更新至 17.7.3 后 方法色彩失效

### ISSUE THREAD

**Issue by Hakoyu** [wmjordan/Codist#299]
![image](https://github.com/wmjordan/Codist/assets/48956359/9d7d1e79-3eaa-40a3-8b07-98c12561b17e)

**Comment by wmjordan** [comment]
请尝试升级到最新版的 Codist。

这个问题和 #297 、 #295 都是一类问题，似乎是由于 VS 调整了它语法着色混合优先级排序规则而引起的。暂时没有什么好办法可以解决。

临时解决办法：不要指定 identifier 的颜色。

**Comment by wmjordan** [comment]
如果你目前已在用最新版的 Codist，而且也没有配置过 idenitfier 的颜色，那暂时就没辙了。
VS 的安装程序里有回滚到上一个可用版本的功能，可以尝试还原到前一个版本的 VS。

**Comment by Hakoyu** [comment]
触发方式具有不确定性 重新打开项目可能会恢复正常

**Comment by wmjordan** [comment]
或者尝试指定“C#: Method”的颜色，看看是否能将 identifier 的颜色给覆盖掉

**Comment by LuohuaRain** [comment]
同失效，不知道还有没有啥好办法

**Comment by wmjordan** [comment]
暂时还没找到什么很好的办法。
最近VS每升一个版本，就有一批语法无法正常突显，真是苦恼。

**Comment by wmjordan** [comment]
本报告与其它相关故障报告已合并到 #303
