### ISSUE TITLE
Suggestion: Make Smart Bar Togglable with a Modifier Key

### ISSUE THREAD

**Issue by fitdev** [wmjordan/Codist#30]
It would be nice if it was possible to toggle the Bar's visibility with a modifier key (similar to how it is done with Tooltips). So that the bar will only be shown if there is a selection AND modifier key (say Ctrl) was pressed.

What I find is that the Smart Bar often gets in the way when doing mouse manipulations with the text.

Also, that would probably "solve" the crashes I reported and all related possible future crashes, since it would no longer be displayed automatically on selection but instead also require a key toggle.

**Comment by wmjordan** [comment]
The difference behavior of Smart Bar and the Quick Info is that the former usually appears after the selection is changed. The Ctrl key will change the behavior of selecting text (select words) and by default it will navigate to the definition of the symbol which was clicked. Thus the key modifier approach might not be viable.

Recent version of Codist automatically hides the Smart Bar while you drag text over it.

I would love to hear from you about how it _gets in the way_ when you work with your mouse.

**Comment by fitdev** [comment]
Thank you for your response! I agree the modifier key setup may be tricky. Don't really know what the would be the better alternative...

As for how it gets in the way, I will try to monitor it more closely and let you know. But just from the memory, I would frequently accidentally click on one of the buttons when adjusting selection with a mouse or dragging it. Maybe it is no longer true in the latest version. I will need to watch it more closely and let you know.

**Comment by wmjordan** [comment]
Thank you very much for your feedback.

The dragging would no longer be a problem.
Nowadays, the Smart Bar could get into our way while we were selecting text with the keyboard. I did have the similar experience before and your reply had reminded me that.
Instead of disabling the appearing of Smart Bar, maybe it is viable to suppress it when keyboard modifier keys are pressed--that is, Smart Bar will only appear when we select text via mouse or external commands. How do you think about that?

**Comment by wmjordan** [comment]
I released a new version which suppresses Smart Bar when Shift key is pressed. That version should also hopefully solve issue #23 . Please test it.

**Comment by fitdev** [comment]
Sorry for the late response. I am using the latest version apparently. However haven't noticed how the Shift key affects the smart bar yet. But no crashes so far. I will let you know in case it happens. Thanks for all your awesome work!

**Comment by wmjordan** [comment]
I'll provide an option to suppress the Smart Bar when Shift key is pressed.

**Comment by wmjordan** [comment]
Please test with this new beta version, which provides an option to show Smart Bar only when Shift key is pressed.

[Codist.zip](https://github.com/wmjordan/Codist/files/2407602/Codist.zip)



This version also provides a better preview in syntax highlight options pages.

**Comment by fitdev** [comment]
Gave the new feature a try and so far it seems a bit confusing...

After I have re-enabled Smart Bar feature, enabled the option to show it only when Shift key is pressed, and restarted VS...

1. If I make a selection, and then press Shift, the Smart Bar _does not_ appear. I thought it should appear under exactly those circumstances and remain visible either _while_ Shift key is pressed, or _until_ it is pressed _again_ (i.e. works like a toggle).

2. It does appear if I _simultaneously_ make a selection (with a mouse) and hold down Shift key. However this results in improper selection, since the Shift key affects the selection I am making with a mouse.

3. Then, after it appears it behaves strangely as well. It may disappear moments later once Shift is released (which would make sense if the Shift being pressed is the requirement for it to be displayed, but as I wrote in 1 and 2 it does not appear to function that way). More logical thing would be (if Shift works as a toggle, not as the "hold down" mode) is for the Smart Bar to remain visible once shown until either: Shift is pressed again (if it works as a toggle), or until selection goes away.

4. For me the more logical way for it to work would be one of the following:
I. Toggle mode:
1) Selection is made -> nothing appears.
2) Shift key is pressed and released -> Smart Bar is shown (won;t be shown if selection was cleared).
3) Either selection is cleared or Shift key is pressed again -> Smart Bar is hidden.

II. Press mode:
1)  Selection is made -> nothing appears.
2) _While_ the Shift key is pressed (after the selection has been made) Smart Bar is visible.
3) Either selection is cleared or Shift key is _released_ -> Smart Bar is hidden.

Hope it helps.

**Comment by wmjordan** [comment]
Thanks for the reply and suggestion. I'll look into the toggle mode and see whether it could be implemented.
As for enabling/disabling any feature, you need to close the document windows and reopen them.

**Comment by wmjordan** [comment]
Please test with this new beta:

- A new option to use Shift key toggle the display of _Smart Bar_.
- A new option to suppress the automatic display of _Smart Bar_.
- Meanwhile, I changed the display position of _Smart Bar_ to avoid it getting in our way.

The _Smart Bar_ can be displayed with the Shift key even when nothing is selected in this version (I wanna do this for quite some time). I think it can be useful too. Let's test it.

[Codist.zip](https://github.com/wmjordan/Codist/files/2409424/Codist.zip)

**Comment by wmjordan** [comment]
Press Shift key twice to show the _Smart Bar_, once again to hide it.

[Codist.zip](https://github.com/wmjordan/Codist/files/2409573/Codist.zip)

**Comment by fitdev** [comment]
Thank you for the new version. I will give it a try and let you know how it goes.

Yes, as I was writing about the selection being the requirement for Smart Bar display, I too was thinking that it could be useful at times even without selection. So I am glad you are considering this as well.

**Comment by wmjordan** [comment]
I have been working with the new version for sometime, after implementing the toggle today.
The _Shift double-tap to bring out Smart Bar_ feature makes me feel good.

I remember that it has been quite a few times that I wanted to Smart Bar to reappear but I had to reselect some text once again. With the new toggle feature, there is no need to reselect.

There are two reasons here for me why the toggle key is implemented as a double tap rather than a single tap:

1. Prevent programmers from mistakenly bringing out the Smart Bar which may get in their way.
2. The Chinese, Japanese and Korean programmers may have their input method editor (IME) configured to use the Shift key to toggle the input method. A single tap of Shift will change their input method to their mother language. And one more tap will change the input method back to English. So, double-tapping is preferred.

**Comment by fitdev** [comment]
I agree with your observation that being able to toggle Smart Bar without the need to re-select text is a definite plus! I have tried it for a day, and so far it worked just fine. Granted, I do not use Smart Bar often, the way it currently works seems to be very good!

**Comment by wmjordan** [comment]
Good to hear that.
I am going to release a new version this week including this improvement then.
