### ISSUE TITLE
Suggestion: 大文件语法着色禁用

### ISSUE THREAD

**Issue by hoowhen** [wmjordan/Codist#301]
使用插件并且编辑较大文件时，会导致vs长时间无响应，可否加一个开关使当前超过指定行数的文件禁用codist语法着色

**Comment by wmjordan** [comment]
你的文件有多大呢？
我手头上有个开源项目，里面有个文件有5856行，257280个字符，把 Codist 所有功能全开，编辑过程中也不会无响应，只是CPU 转得厉害（大部分的开销在 Roslyn 上，无法避免）。

**Comment by hoowhen** [comment]
> 你的文件有多大呢？ 我手头上有个开源项目，里面有个文件有5856行，257280个字符，把 Codist 所有功能全开，编辑过程中也不会无响应，只是CPU 转得厉害（大部分的开销在 Roslyn 上，无法避免）。


2500行左右
打开文件20s左右，编辑文件保存时卡顿20s以上

**Comment by wmjordan** [comment]
才 2500 行，也不算很大。整个解决方案有多大呢？
我用 Roslyn 项目的解决方案来测试 Codist 的性能都没遇到超过几秒钟的卡顿。
Codist 的版本号是多少？

**Comment by hoowhen** [comment]
language | files | code | comment | blank | total
-- | -- | -- | -- | -- | --
C# | 4,907 | 358,662 | 139,253 | 43,196 | 541,111
XAML | 625 | 130,441 | 0 | 7,797 | 138,238


Codist 版本 7.7.2.9324

**Comment by wmjordan** [comment]
代码量也不算很多啊。怎么会卡成这个样子。
请把 Codist 的配置文件压缩后发上来给我测试一下看看。

**Comment by hoowhen** [comment]
[Codist.zip](https://github.com/wmjordan/Codist/files/12518695/Codist.zip)

**Comment by wmjordan** [comment]
使用上面的配置，目前还无法重现出明显的卡顿。
在你的VS上还安装了哪些插件呢？

**Comment by wmjordan** [comment]
因无法重现问题，故关闭之
