### ISSUE TITLE
Some syntax highlight styles got broken or failed to apply after VS 17.7.1

### ISSUE THREAD

**Issue by wmjordan** [wmjordan/Codist#303]
As stated in the following issues: #295, #297, #299, which were not yet solved and merged to this one.

Every update after VS 17.7.1 prevented one or two syntax highlights from working properly.
Some classifications were not sorted in proper priority.
Some classifications could not be styled.
Very weird!

**Comment by wmjordan** [comment]
I just upgraded to VS 17.8 preview 6.
It seemed that the VS team had realized their broken syntax highlighting system and fixed it.
Now the Codist Highlight is working as expected on my machine again.

**Comment by LuohuaRain** [comment]
FYI: https://github.com/dotnet/roslyn/pull/70416

**Comment by fitdev** [comment]
Running VS 17.9 Preview 1, again syntax highlights are broken. This time restarting VS / reinstalling Codist (tried different versions) did not fix the issues.

- User comment tags are completely broken - in both C# and XML. It seems that only _base_ (comment) style is being applied, while the various user tag styles are not applied at all. This is the biggest one for me.
- Operator overloads are also not applied correctly - again it seems that only _base_ (operator) style is applied, but if the operator is a custom one, it should be colored differently, but it's not.

Now I use latest released Codist version.

Attached are my styles.
[Codist.styles.zip](https://github.com/wmjordan/Codist/files/13362514/Codist.styles.zip)

Hope you can look into this when you have time, as it seriously hinders cripples feature.

**Comment by fitdev** [comment]
Here are some illustrations:

![Screenshot_20231115_121839](https://github.com/wmjordan/Codist/assets/8166847/77c344fd-5595-42f8-8e74-2c4f963cb4e5)

![Screenshot_20231115_121903](https://github.com/wmjordan/Codist/assets/8166847/16ad2d20-bac2-4a75-bad2-ba36e2035f83)

![Screenshot_20231115_121951](https://github.com/wmjordan/Codist/assets/8166847/8f4ca814-0ed2-462d-b9b0-5342dd0ea649)

Note: Cyan background over `FIX` is correct - it uses VS's highlight current word feature, so not part of the style.

**Comment by wmjordan** [comment]
I just upgraded to 17.9 preview 1 and experienced the same issue. Comment taggers were broken.
Unfortunately, the experimental instance of my VS also got broken after the upgrade, thus I had a hard time debugging the extension.

**Comment by fitdev** [comment]
Thank you for confirming that this is not just something on my end. Hopefully a workaround can be made soon. I really miss those user comment highlights.

**Comment by wmjordan** [comment]
It could take some time since I could not debug the VS with the broken experimental instance. It happened once in a previous VS preview version which had also ruined the experimental instance. Hopefully it could be fixed in 17.9 preview 2.

**Comment by fitdev** [comment]
Seems 17.9 preview 1 is buggy. Pity I upgraded to it so soon, but I needed DotNet 8 RTM, so I had little choice. Perhaps you will get the experimental instance fixed so you can try debugging it there.

**Comment by wmjordan** [comment]
> Seems 17.9 preview 1 is buggy. Pity I upgraded to it so soon, but I needed DotNet 8 RTM, so I had little choice. Perhaps you will get the experimental instance fixed so you can try debugging it there. Thank you for all your hard work!

@fitdev 
I spent half an hour tracking the failure of comment tagger. Since the experiment instance was broken, it was very time consuming.
Codist previously used an `ITagAggregator<IClassificationTag>` to gather and tag classified comments. In the current preview version of VS, the tag aggregator provided by VS no longer returned anything in C#, which broke the C# comment tagger.
Since things were working well before the last VS preview, I will not spend any more time trying to fix it and will wait for their next preview versions.

**Comment by fitdev** [comment]
I see. Thank you for looking into this. Hopefully they will fix in in their next preview.

PS. I thought that Codist was manually parsing all regular comments and then using RegEx or something like this to see if a comment contains the tag and therefore should be styled.

**Comment by wmjordan** [comment]
> PS. I thought that Codist was manually parsing all regular comments and then using RegEx or something like this to see if a comment contains the tag and therefore should be styled.

Yes, it is working somewhat like that, but without Regular Expression.
Before parsing, we have got to find out where are those _comment_s, that is what the aforementioned `ITagAggregator<IClassificationTag>` supposed to do.

**Comment by fitdev** [comment]
Just to let you know, for the moment I am suing [Highlighter Extension](https://marketplace.visualstudio.com/items?itemName=DaxPandhi.Highlighter1&ssr=false) to get a similar result with comment tags. It is not nearly as good as Codist, but at least makes it possibly to more readily identify the tags in the comments. Unfortunately I could not find a source code for it. But perhaps you may find it useful.

**Comment by wmjordan** [comment]
Highlighter is open-sourced. And [the magic happens there](https://github.com/QuadSpinner/Highlighter/blob/main/src/Core/Adorner.cs#L97). It examines every visible line in the editor window and compares against predefined/customized rules. Actually I had once planned to do something like that in [a code file which has not yet been put into use](https://github.com/wmjordan/Codist/blob/master/Codist/Taggers/CustomTagger.cs), before the COVID pandemic, 4 years ago. Somehow I think it of low priority and put it down.

**Comment by fitdev** [comment]
I see. I think it may be a useful feature, since it gives one more control and flexibility over what and how to highlight. As a bonus it allows highlights to work even when VS upgrade screws things up like it did with 17.9.P1. So, if it is relatively simple to finish integrating the draft version you already have into Codist, I think it will be a great addition to the already excellent Codist's highlighting capabilities!

**Comment by fitdev** [comment]
Thanks for the fix! So nice to see old highlights back! I will let you know if I encounter any issues. Hopefully the performance penalty is not too bad.

**Comment by fitdev** [comment]
I noticed in the new version, sometimes highlight would be lost - for no apparent reason - like after typing ion the document - either in the highlighted part or nearby. To fix it, you need to reopen the document, then highlight is restored.

**Comment by wmjordan** [comment]
> sometimes highlight would be lost - for no apparent reason - like after typing ion the document - either in the highlighted part or nearby. To fix it, you need to reopen the document, then highlight is restored.

I have not yet encountered this.

**Comment by fitdev** [comment]
Happens pretty regularly actually. It does not matter where you type - within the comment, or elsewhere in the document, sometimes the highlighting (of the comment tags) just disappears _everywhere in the document at once_. The solution is to close and reopen the document. I have not noticed any pattern to this. BTW, I did disable the other highlighter extension of course.

**Comment by fitdev** [comment]
Doubt that it will be helpful, but here is an example:

After I returned to VS after about an hour of inactivity and started typing `//TOD...` on a new line below the lines in the screenshot, comment tag highlighting got removed everywhere in the document:

![Screenshot_20231218_154633](https://github.com/wmjordan/Codist/assets/8166847/875df305-2a6c-4b04-9323-c3c0dc83b0f3)

Then, once I closed and reopened the document, everything is back to normal, but for how long?

![Screenshot_20231218_154754](https://github.com/wmjordan/Codist/assets/8166847/f8fd325e-ad23-4bfb-a185-c26d2cd4ad81)
