### ISSUE TITLE
Nested types were not properly displayed on C# Quick Info

### ISSUE THREAD

**Issue by laicasaane** [wmjordan/Codist#304]
For example, the `Data` type in this screenshot is nested inside `IntervalRateCollection`, and I expect it to be shown as `IntervalRateCollection.Data` instead.

![image](https://github.com/wmjordan/Codist/assets/1594982/28cd75e9-b3c2-4168-b925-0181e9086869)

**Comment by wmjordan** [comment]
I've just uploaded a new version to the marketplace to fix this bug.
Please upgrade Codist from VS.
