### ISSUE TITLE
Import Theme starts in random(?) folder

### ISSUE THREAD

**Issue by nurbles** [wmjordan/Codist#305]
Actually, once I use the import function once, then it seems to use the same folder for the remainder of the session and perhaps even until my computer is rebooted.

However...  The **first** time I click the **Import...** button each day (necessary because of a change to VS2022 that affected Codist colors) the initial folder selected seems to be _almost_ random.  I say _almost_ because it is usually a folder I've looked at with Windows File Explorer and/or some other (non VS2022) program during the past day or so.

It would be nice if the starting folder was consistent.  It would be GREAT if the starting folder was the folder most recently used as an import source.

If this is how it is intended to work, how can I figure out why my system does not work that way?  Thanks!

Oh, using Codist 7.7.2.9370 in VS2022 17.8.2.  Oh, I just notices that Codist is also listed in the VS2022 'About' dialog as version 7.7.0 -- I hope that's normal and expected.

**Comment by wmjordan** [comment]
The import function does not opens at a special folder. Thus I don't know what folder it will open with.

The mostly opened or saved folder for theme files can be the possible candidate of initial folder, in the future version.
