### ISSUE TITLE
Bug：Some Bugs in the Super Quick Info（超级代码提升）

### ISSUE THREAD

**Issue by kwonganding** [wmjordan/Codist#306]
如果内容中有换行标记`<br/>`则会重复：

![image](https://github.com/wmjordan/Codist/assets/16829626/06853d65-8a9e-4fdf-8d7e-9fadd6b3e823)

`<summary>` `<remarks>`中的`<list>`列表显示效果不支持：

![image](https://github.com/wmjordan/Codist/assets/16829626/766c7385-46eb-480f-bf03-2e581f133fe5)

**Comment by wmjordan** [comment]
确认有这个问题。
我这边的Visual Studio预览版有故障，要等微软的人升级解决问题了才能调试解决上述问题。
