### ISSUE TITLE
Broken syntax highlighting with latest Codist and VS 17.9.0 Preview 1.1

### ISSUE THREAD

**Issue by laicasaane** [wmjordan/Codist#309]
I'm trying out VS 17.9.0 Preview 1.1 and notice that syntax highlighting is broken if I have Codist enabled. It returns to normal when Codist is disabled.

Codist enabled:
![image](https://github.com/wmjordan/Codist/assets/1594982/584bffc7-61e3-4f6c-b0b5-566b87b1592a)

Codist disabled:
![image](https://github.com/wmjordan/Codist/assets/1594982/ff738afa-ccf0-4d1e-8974-bda4e6be31bc)

Note: I don't use Codist syntax highlight. I'm using the default of VS.
Note 2: Even Codist syntax highlight doesn't work too.

**Comment by wmjordan** [comment]
I also noticed that, after upgrading to this preview, Codist was not working at the first run. But on the second run, things got back to normal. Was it always broken on your side?

**Comment by laicasaane** [comment]
I've tried to disable other extensions, but it seems to randomly work.

**Comment by fitdev** [comment]
It seems that VS 17.9 Preview 1+ has several issues in this regard, and 1.1 has not fixed it. For example, in my case tagged user comments do not work at all (see #303 ), and operator overloads (user operators) are not properly highlighted.
Hoping that Preview 2 will fix these.

**Comment by fitdev** [comment]
BTW Just installed 17.9 Preview 2 released today. Unfortunately it did not fix custom comment tags/highlights.
