### ISSUE TITLE
在查看Resharper反编译的代码时，有可能会抛出异常IndexOutOfRangeException

### ISSUE THREAD

**Issue by QianMoXi** [wmjordan/Codist#315]
# 可复现步骤
1. 安装microsoft.entityframeworkcore 8.0.0版本的nuget包
2. 反编译Microsoft.EntityFrameworkCore.Metadata.RuntimeModel代码
3. 滚动到290行代码，鼠标移动到`IsIndexerMethod`或`methodInfo`上
![image](https://github.com/wmjordan/Codist/assets/26250460/c3db36a5-d992-4af4-9689-84f637aa83b8)
4. 然后会弹出报错
![image](https://github.com/wmjordan/Codist/assets/26250460/8656f00c-c1f0-4e76-b66b-b5384b08f0ae)

# 报错
```
System.IndexOutOfRangeException: 索引超出了数组界限。
   在 Codist.SymbolFormatter.FormatMethodName(InlineCollection text, ISymbol symbol, String alias, Boolean bold) 位置 D:\Codes\Open Source Projects\Codist\Codist\Semantics\SymbolFormatter.cs:行号 769
   在 Codist.SymbolFormatter.ShowSignature(ISymbol symbol) 位置 D:\Codes\Open Source Projects\Codist\Codist\Semantics\SymbolFormatter.cs:行号 120
   在 Codist.QuickInfo.QuickInfoOverride.UIOverride.ShowAlternativeSignature() 位置 D:\Codes\Open Source Projects\Codist\Codist\QuickInfo\QuickInfoOverride.cs:行号 550
   在 Codist.QuickInfo.QuickInfoOverride.UIOverride.OnVisualParentChanged(DependencyObject oldParent) 位置 D:\Codes\Open Source Projects\Codist\Codist\QuickInfo\QuickInfoOverride.cs:行号 415
```

# 预期情况
正常显示提示，不会弹出异常报错窗口。
即使无法解析，也希望不要鼠标移动上去，一直弹出相同的报错，可弹出一次后续遇到相同的异常就不再提示了。不然的话，复制之类的操作不太方便

**Comment by wmjordan** [comment]
可能导致弹出报错窗口的相关代码如下所示。

https://github.com/wmjordan/Codist/blob/980aa20be2375370e2378c77e2f67ed7d3f7aa4e/Codist/Semantics/SymbolFormatter.cs#L781-L783

一个方法的类型既然是 `ExplicitInterfaceImplementation`，在 `ExplicitInterfaceImplementations` 就应该具有至少一个实现。出现 `IndexOutOfRangeException` 意味着没有接口方法实现。这应该是 Roslyn 的缺陷。

**Comment by wmjordan** [comment]
哦，原来是 Resharper 的问题。
我没有安装那个插件，所以无法重现出故障。VS 从来都没有这样的问题。

也许可以调整报错机制，在弹出的报错对话框中，增加一个“不再报告同类异常”的复选框。选中该复选框后，在重启 VS 之前就不再对相同的异常报错。

**Comment by wmjordan** [comment]
请下载这个测试版。它允许你暂时禁止 Codist 报告那个异常，直到重新启动 VS。
从根本上而言，要让 Resharper 解决问题。
[Codist.zip](https://github.com/wmjordan/Codist/files/14173559/Codist.zip)
