### ISSUE TITLE
Add support for changing Inline Hits

### ISSUE THREAD

**Issue by M0n7y5** [wmjordan/Codist#319]
Hi, i was not able to find a way to set custom font and color for inline hits and codelens. I assume its not supported yet.
Can you please add this feature?

**Comment by wmjordan** [comment]
You can do that in the Fonts and Colors dialog.
![image](https://github.com/wmjordan/Codist/assets/12182730/096d8433-803d-4489-9421-d1171e6ce733)

![image](https://github.com/wmjordan/Codist/assets/12182730/c21818ca-f075-4661-b87f-4eacdf5662f0)

**Comment by wmjordan** [comment]
Have you ever post your request to the VS feedback?

**Comment by M0n7y5** [comment]
No since they rarely implement what people want or need.

**Comment by wmjordan** [comment]
Unfortunately, I can not find a way to do so. No open API supports this. You have to turn to the VS team.

**Comment by M0n7y5** [comment]
> Unfortunately, I can not find a way to do so. No open API supports this. You have to turn to the VS team.

Really? They don't expose the API for this? Damn, that's a bummer. Ok then. I'll open issue on VS Feedback.
Can i let this issue open? I'll also post the link to VS Feedback here if you don't mind.

**Comment by wmjordan** [comment]
No. No API.
Actually, some features in Codist are implemented without VS API, but WPF hacks. However, I can neither find a way to efficiently hack into the inline hints.

**Comment by wmjordan** [comment]
No can implement. Have to close this.
