### ISSUE TITLE
Feature Request: Super Quick Info separator lines

### ISSUE THREAD

**Issue by IneedHelp** [wmjordan/Codist#32]
Super Quick Info is well executed and extremely useful, thank you for such a great tool.

Sometimes information in the Quick Info tooltip can be overwhelming with a lot of rows displaying different kinds of information, so it would be great to have an option that allows separating sections using lines or dotted lines (and maybe even section names, similarly to the group box control).

I think it would make the Super Quick Info tooltip more aesthetically pleasing and would help the user to visually separate different sections of it.

Thank you!

**Comment by wmjordan** [comment]
Thank you for making this request and the interests in Codist.
Actually, I've gotten the similar idea before. And your post on another issue #31 about _ReSharper.EnhancedTooltip_ had reminded me of this.

However, currently I am busy with practical parts of the project, hence the artistic polish may come later.
Please stay tuned. 😃

**Comment by wmjordan** [comment]
The next version will have a redesigned look for the Quick Info.
![default](https://user-images.githubusercontent.com/12182730/50559759-35e2e200-0d35-11e9-82d8-a8aa975265eb.png)
![default](https://user-images.githubusercontent.com/12182730/50559811-5f037280-0d35-11e9-9158-0e02d7516e1e.png)
![default](https://user-images.githubusercontent.com/12182730/50559865-a558d180-0d35-11e9-8d16-bfdc2aa4cfbe.png)
