### ISSUE TITLE
方向键失效

### ISSUE THREAD

**Issue by mufeng1122** [wmjordan/Codist#321]
安装插件后，方向键失效，点上箭头跑到了文件代码的面包屑操作项上。左右方向失效。不会平移鼠标光标了

**Comment by wmjordan** [comment]
其他用户用了几年也没反馈过这个问题，请描述出现问题的详细操作步骤、打开的文件类型，以及尝试禁用其他插件

**Comment by wmjordan** [comment]
无法复现此问题
