### ISSUE TITLE
小问题：为什么 IDisposable 接口图标是带警告的⚠️

### ISSUE THREAD

**Issue by CodingOctocat** [wmjordan/Codist#322]
![image](https://github.com/wmjordan/Codist/assets/7220248/8d57726c-ac8d-4e40-8852-99d402164a06)

**Comment by wmjordan** [comment]
按照一般的编程约定，必须确保这个接口的 Dispose 方法得到调用，否则可能会造成资源泄漏。因此，给这个接口一个特殊的图标。

**Comment by wmjordan** [comment]
按照一般的编程约定，必须确保这个接口的 Dispose 方法得到调用，否则可能会造成资源泄漏。因此，给这个接口一个特殊的图标。

**Comment by CodingOctocat** [comment]
我觉得这个图标有点歧义，它和 VS 中引入兼容的依赖项的警告图标类似。

**Comment by wmjordan** [comment]
置顶的 Beta 版更改了一批图标。请试用一下，给点反馈吧。

**Comment by wmjordan** [comment]
闪电符号在Visual Studio里表示事件，不合适。
感叹号表示警告，似乎的确也不太好。
或者再换个别的。

**Comment by wmjordan** [comment]
新的测试版换了个图标

**Comment by CodingOctocat** [comment]
新测试版图标不错，不过不是很明显，另外还是建议提供 ToolTip，不然应该挺多人会有疑惑。

![image](https://github.com/wmjordan/Codist/assets/7220248/73cc8748-23ff-4705-870b-dfd4705c3e73)
