### ISSUE TITLE
Super Quick Info中文XML注释有锯齿

### ISSUE THREAD

**Issue by actforjason** [wmjordan/Codist#324]
“文档注释”可以看到一些笔画粗细异常，原生的字体比较圆润。
Editor Tooltip字体为HarmonyOS Sans SC，只有微软系列字体正常。
![图片](https://github.com/wmjordan/Codist/assets/57058325/1a282853-2443-48a4-a4d0-7c17ff45c5e1)
![图片](https://github.com/wmjordan/Codist/assets/57058325/22903887-477b-4262-ba7d-9ae44e2ff651)

**Comment by wmjordan** [comment]
Codist的选项里有优化显示效果的选项，选中它们，看看显示效果是否有改善。

<img width="563" alt="image" src="https://github.com/wmjordan/Codist/assets/12182730/200817f7-c43d-4961-b11a-bdcc9e267cf8">

**Comment by actforjason** [comment]
取消掉这两个选项后正常了，默认好像是勾选的。
