### ISSUE TITLE
[Feature] Quick Info 给 xml <code><example> 代码提供语法着色和外框

### ISSUE THREAD

**Issue by CodingOctocat** [wmjordan/Codist#326]
这是现在的样子，xml 文档中的代码没有着色，并且底纹是突兀的黑色：
![image](https://github.com/wmjordan/Codist/assets/7220248/e868d554-0f4f-4476-a35a-98d3df976ad6)

建议提供语法着色和圆角边框。
![image](https://github.com/wmjordan/Codist/assets/7220248/98858829-433b-4e1b-8581-65537cb8d553)

**Comment by wmjordan** [comment]
我知道是不太好看。
但如果改成你想要的那个样子，框里的文本就复制不出来了。
我宁可保持现状。

**Comment by wmjordan** [comment]
花了一天的时间，搞唔掂。
只能做到下图的样子。

![image](https://github.com/wmjordan/Codist/assets/12182730/86f3d0c3-7655-4f71-b8f8-cddc75f147be)

**Comment by CodingOctocat** [comment]
可以，比之前的黑色底纹效果要好不少。

**Comment by wmjordan** [comment]
请下载 issues 置顶的 Beta 版本。
