### ISSUE TITLE
XmlDoc Custom Link Text Not Working For cref in see and seealso

### ISSUE THREAD

**Issue by Stekeblad** [wmjordan/Codist#327]
I noticed that Super quick info does not support custom link text in xml documentation for `see` and `seealso` when using the `cref` attribute, `href` links do work. See screenshots below.

When preparing the screenshots I also noticed that `seealso` looses the space between the link and the following text. (For both `cref` and `href`.)

Codist: 7.8.3.9575
Visual Studio: Community 17.10.0

## Code example

```C#
public static class ExampleClass
{
  /// <summary>
  /// <para>Also look at <see cref="TestMethod">this</see> method</para>
  /// <para>Also look at <see href="https://example.com/">this</see> url</para>
  /// <para>Also look at <seealso cref="TestMethod">this</seealso> method</para>
  /// <para>Also look at <seealso href="https://example.com">this</seealso> url</para>
  /// </summary>
  public static string ExampleMethod() => "Example";
  public static string TestMethod() => "Test";
}
```

### With Codist
![image](https://github.com/wmjordan/Codist/assets/12627375/4ec8b8a7-e6d4-45d1-808d-8b6172daa5fe)

### Without Codist
![image](https://github.com/wmjordan/Codist/assets/12627375/1403a3e1-2ee4-456f-a146-6d97479fcf5b)

**Comment by wmjordan** [comment]
Please download the new beta.

**Comment by Stekeblad** [comment]
Looks good in beta 9861

**Comment by wmjordan** [comment]
The previous beta has a problem, please download the new one.
