### ISSUE TITLE
Suggestion: Support Comment Tagger in web-related files: razor, cshtml, js, css

### ISSUE THREAD

**Issue by fitdev** [wmjordan/Codist#328]
It would be really nice if Comment Tagger would also work in `.razor`, `.cshtml`, and perhaps even `.css`, `.less`, `.scss`, and `.js` files as well. Ideally anywhere VS is able to provide an API that such a run of text is a comment, it should work.

Also, I noticed recently that in `.csproj` files Comment Tagger no longer works.

**Comment by wmjordan** [comment]
It was designed to support that. Is it broken again?

**Comment by fitdev** [comment]
`*.cs`:
![Screenshot_20240605_092516](https://github.com/wmjordan/Codist/assets/8166847/5a8c11b4-682c-4669-aefb-f37ac15c9d76)

`*.csproj`:
![Screenshot_20240605_092445](https://github.com/wmjordan/Codist/assets/8166847/9e215262-e649-4ffd-b9e2-db53f5554cf5)

`*.razor`:
![Screenshot_20240605_092359](https://github.com/wmjordan/Codist/assets/8166847/88013be6-9548-44e9-9e9f-49f2f2a95eb5)

Though I am using VS 17.9 P2 (was planning to update later this month), but I doubted if it has anything to do with me using VS version that is a few months older than the latest preview. I try not to update unnecessarily these days to avoid even more issues with VS in later previews.

**Comment by wmjordan** [comment]
.csproj: VS team has changed the classification of XML comments. The comment tags are now XML Delimiter, no longer part of XML comment. I will take a  look into it.

.razor: Please do the following steps and post the results here.

1. Open the Codist option, enable the SmartBar.
2. Enable the _Add "Show Active Window Properties" command to File Menu_ option and the  _Add "Show Syntax Classification Info" command to Smart Bar_ option in the _Extension Development_ section.
3. Open a razor file.
4. Click into that file document window.
5. Execute the "Show Active Window Properties" command from the _File_ menu.
6. Copy the indented lines under the `TextBuffer.ContentType:` in the window and paste them here.
7. Close that dialog window.
8. Select a comment in the razor file, and click the rightmost button on the Smart Bar. --note: the comment should be short, otherwise the button won't show up.
9. Copy the content of the popup _Syntax Classification Info_ window and paste them here.

**Comment by fitdev** [comment]
```
TextBuffer.ContentType:
 Razor
  code-languageserver-preview
   code-languageserver-base
    languageserver-base
     any
    code
     text
   code-languageserver-textmate-color
   code-languageserver-textmate-structure
   code-languageserver-textmate-brace
   code-languageserver-textmate-indentation
   code-textmate-commentselection
```

Selected "FIX: Duration title (name - change word)" within the `@*` and `*@`
```
Classifications for selected content:
[5186..5226) HTML Comment;Semantic - comment;Syntactic - (TRANSIENT): FIX: Duration title (name - change word)

Classification tags:
[5186..5226) HTML Comment
[5185..5186) RazorDirective
[5186..5226) comment
[5226..5227) RazorDirective
[5185..5186) RazorDirective
[5186..5226) comment
[5226..5227) RazorDirective
```

Also, noticed that regular C# comment tags do not work either in razor files:

![Screenshot_20240605_152824](https://github.com/wmjordan/Codist/assets/8166847/a955386d-0dcc-42d8-a5fb-83316d1ec833)

```
Classifications for selected content:
[8..37) comment;Semantic - comment;Syntactic - (TRANSIENT): FIX: Display all visible edns

Classification tags:
[6..37) comment
[6..37) comment
[6..37) comment
```

**Comment by wmjordan** [comment]
I just looked into the csproj stuff. It might be caused by another code fix.

**Comment by wmjordan** [comment]
Please try the new beta.

**Comment by fitdev** [comment]
You are so fast!
Yes, I can confirm, the latest beta restored `.csproj` user comment tag highlighting! Great work!

**Comment by fitdev** [comment]
Still the same - `.razor` does not work - neither `//TAG: ...` within `@{ ... }` blocks, nor razor-specific ones like `@*NOTE: ... *@`.
Not sure if other file types like json, js, css, or less are supposed to work at all, but they do not get highlighted either.

**Comment by fitdev** [comment]
Also just noticed that latest beta seems to have broken rendering of Symbol names in SuperQuickInfos, i.e. `<see cref="SymbolName"/>` appears as blank `` text.

**Comment by wmjordan** [comment]
The new beta supports less and json now.
Please try your luck with the .razor type.

**Comment by fitdev** [comment]
Thank you so much for the new beta!
Razor now works great! Thank you so much! This was the big one for me!

However regular C# code sections do not work at all in `.razor` files:

```
@{
  var foo = 23;
 //NOTE: This is not highlighted at all
}
```

The output for the `//` style comment in the razor file within the `@{  }` section:
```
Classifications for selected content:
[1281..1317) comment;Semantic - comment;Syntactic - (TRANSIENT): NOTE: This is not highlighted at all

Classification tags:
[1279..1317) comment
[1279..1317) comment
[1279..1317) comment
```


JavaScript also works great!

What would be nice is this:
- `.less`: It would be nice to also support the `//` style comments also allowed by less. Right now only `/* */` syntax works.
- `.scss`: This is another very popular css-preprocessor, would be nice if both `//` and `/* */` would be supported.

**Comment by wmjordan** [comment]
The razor thing requires quite some hard work.
I don't program web stuff thus I have not installed the VS workload.

The less file type is working fine here.
![image](https://github.com/wmjordan/Codist/assets/12182730/e6523a15-7e12-4690-9f9e-8c676fc4bcf3)

Please use the Active Window Properties command and let me see what's the content type at your site.

And please do so to the scss files too.

**Comment by fitdev** [comment]
`*.less`:

Strangely, for me `//` does not work, while `/* */` works.

```
LESS
  css.extensions
    css
      projection
        any
      text
      code
```

`*.scss`:
Right now neither `//` nor `/* */` work.

```
SCSS
  css.extensions
    css
      projection
        any
      text
      code
```

**Comment by fitdev** [comment]
> The razor thing requires quite some hard work

That's understandable. But does this apply even to Super Quick Info? I miss the ability to click on various elements there to quickly navigate to them.

**Comment by wmjordan** [comment]
> `*.less`:
> 
> Strangely, for me `//` does not work, while `/* */` works.

Please use the button on the Smart Bar to get syntax classification results and post it here.

**Comment by wmjordan** [comment]
> > The razor thing requires quite some hard work
> 
> That's understandable. But does this apply even to Super Quick Info? I miss the ability to click on various elements there to quickly navigate to them.

Maybe.

**Comment by fitdev** [comment]
`//NOTE: foo` (Selected "NOTE: foo"): 
```
Classifications for selected content:
[180..189) CSS Comment: NOTE: foo

Classification tags:
[178..189) CSS Comment
```

`/*NOTE: foo*/` (Selected "NOTE: foo"):
```
Classifications for selected content:
[193..202) CSS Comment: NOTE: foo

Classification tags:
[191..193) CSS Comment
[193..202) CSS Comment
[202..204) CSS Comment
```

**Comment by wmjordan** [comment]
Please try your luck with the new beta.

**Comment by fitdev** [comment]
You are amazing! Works great! Thanks for all your incredible work!
