### ISSUE TITLE
Conflicts in tooltip when using Codist and Enhanced Tooltip

### ISSUE THREAD

**Issue by IneedHelp** [wmjordan/Codist#329]
Hello, I am using the latest VS 2022 version (not Preview) with the latest release of Codist, I am also using Enhanced Tooltip (https://github.com/MrJul/ReSharper.EnhancedTooltip) and this is what happens:

![image](https://github.com/wmjordan/Codist/assets/1366970/ab499d83-d80b-48ac-8bab-895abf593498)

upper and lower part of the tooltip has transparent background and there's no way for me to move the cursor over the tooltip.

Is this a known occurrence ?

I've been using Codist 7.4.0.8762 so far because that was the last version of Codist that was integrating nicely with Enhanced Tooltip.

**Comment by wmjordan** [comment]
I don't use Resharper and I can not do anything about it.
