### ISSUE TITLE
Feature Request: Show remarks of XML Doc on Super Quick Info

### ISSUE THREAD

**Issue by IneedHelp** [wmjordan/Codist#33]
Super Quick info already does an excellent job as it is, but I fell like the XML Doc description can be further improved by adding a couple more features to it.

Considering the following code: https://www.servicehusky.com/textbin/WTXjcib1
Results in the following Super Quick Info tooltip: https://imgur.com/bwPgMDu

As you can see, the remarks aren't displayed in the tooltip. however, the exceptions are being displayed, but not their documentation.

So I think having these additions to the Super Quick Info would increase its usefulness.

Thank you!

**Comment by wmjordan** [comment]
The request of display of Exception documentations has been posted on #16 .
And this one has added a request of displaying the remarks, well.
What to do if the remarks are lengthy?

**Comment by IneedHelp** [comment]
I have rarely encountered documentation with extremely lengthy summaries or remarks, but when that happened, they would just go offscreen and becomes useless. I'm guessing that a scrollviewer with vertical scroll bars would fix that since the user is already able to directly interact with Super Quick Info.

There's already the option for the max width and height, so an embedded scrollviewer should take care of extremely lengthy documentation, be it summaries or exceptions or remarks.

**Comment by wmjordan** [comment]
A simple implementation of showing the `<remarks>` content will be implemented in the next version.
