### ISSUE TITLE
Why does code coloring fail when I use the copy shortcut key ctrl+c or ctrl+x? Please answer, thank you!

### ISSUE THREAD

**Issue by 2tenthree** [wmjordan/Codist#330]
As the question is, as long as I press ctrl+c or ctrl+x, the code coloring will fail, and I will resume when I restart vs. Have you encountered this problem? I have been troubled for several days and I can't solve it. VS2022 Community 17.9.4, codist7.8 and 7.9 all have this problem.

**Comment by 2tenthree** [comment]
I just found out that only the currently opened cs file will lose code coloring. It is normal to open other files.

**Comment by wmjordan** [comment]
No, I never encounter such kind of problem.
Cut and copy are very frequent operations. Had it caused trouble, I should have noticed that.

**Comment by 2tenthree** [comment]
The Copy As Html 2022 plug-in caused this problem, and the problem was solved after I disabled it

**Comment by 2tenthree** [comment]
The Copy As Html 2022 plug-in caused this problem, and the problem was solved after I disabled it

**Comment by 2tenthree** [comment]
The Copy As Html 2022 plug-in caused this problem, and the problem was solved after I disabled it

**Comment by 2tenthree** [comment]
The Copy As Html 2022 plug-in caused this problem, and the problem was solved after I disabled it

**Comment by wmjordan** [comment]
I installed the Copy as Html extension and still could not reproduce this issue.
