### ISSUE TITLE
Improve highlighting for UnnecessaryCodeDiagnostic

### ISSUE THREAD

**Issue by laicasaane** [wmjordan/Codist#339]
With Codist highlighting enabled, the code marked as UnnecessaryCodeDiagnostic appears like this:

![image](https://github.com/user-attachments/assets/222684a2-a9b5-4919-9d3b-f68863a17a0c)

However I want the code retain its colors so I can apply different opacity to make it dimmer. Similar to the default VS highlighting:

![image](https://github.com/user-attachments/assets/f64cbb2d-b0c6-46c7-b74d-7b70ed3509f0)

**Comment by wmjordan** [comment]
Please download the latest beta, it should have fixed this issue.

**Comment by wmjordan** [comment]
I'd just released a new version in the market place which includes this fixes.
However, new features in 8.0 beta version are not yet included there. So, you are encouraged to try out the new beta.
