### ISSUE TITLE
Some visual discrepancies in Super Quick Info tooltip display

### ISSUE THREAD

**Issue by IneedHelp** [wmjordan/Codist#34]
Since I just recently started using Codist, and especially the Super Quick Info, I discover a lot of its beauties, but also a couple discrepancies from a visual perspective.

I make heavy use of XML documentation and its tags, and one of those tags is the _c_ tag which is used to put emphasis on certain parts of the documentation comment, the problem is that text in the code tag is being displayed as bold white text over a nearly white background which makes it very hard to read. Ideally, an option to allow the user how certain elements are displayed would be great (i.e. choosing font, font size, foreground/background color), but if not, at least something that's readable. Also notice that only the _c_ tag is being rendered, while the _code_ tag is ignored, and they should give the same result (the only difference being that one is for in-line and the other for multi-line).
![image](https://i.imgur.com/dxU4SfC.png)

My second remark would be in regard to enumerators, which I also use a lot. I very much appreciate the fact that Super Quick Info can display an enum's decimal, hexadecimal and binary values, the only visual issue with it is that the text boxes are not in line with the Visual Studio theme, making them stand out more than I'd like for my eyes:
![image](https://i.imgur.com/w5DmBej.png)

The high contrast between the overall dark theme and extremely luminous elements like the way the code tag is displayed or the text boxes for the enum values are a discomfort for the eye, and I'm sure the same would apply to people using light themes.

If this can already be adjusted and I don't know how yet, my apologies.
These are my enabled modules in Codist:
![image](https://i.imgur.com/jYSVm5n.png)

Thanks again for this wonderful free product!

Other references:
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/code-inline
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/code

**Comment by wmjordan** [comment]
Thank you for the feedback.

For the `<c>` element and the text-boxes for Enum info, they looked quite good in the light theme, and I work with the light theme only. I'd realized the problem of theming before, but since I never used dark themes at all and Codist was not so popular, I left the discrepancy behind.
I'll try to find out some colors suite the themes and use them on those places you mentioned.

I overlooked the `<code>` element. It will be added later.
