### ISSUE TITLE
Support XML DOC inheritdoc on Super Quick Info

### ISSUE THREAD

**Issue by IneedHelp** [wmjordan/Codist#36]
Hello,
I have finally managed to compile the extension from the source code today to the latest provided version.
The improvements are much appreciated!

While using the latest version, I have noticed that inherited documentation doesn't work.
![image](https://i.imgur.com/vTp5gW7.png)

My apologies if I'm doing something wrong.

**Comment by wmjordan** [comment]
Currently the "inherit document" feature does not parse the `<inheritdoc>` element, but looks up corresponding documentations from base types or implemented interfaces.
I understood your feature request and I will try and see whether it is possible to parse the `<inheritdoc>` element.

**Comment by IneedHelp** [comment]
Hello. May I ask, are there any updates on this feature?

I am extremely torn between using Codist and EnhancedTooltips for ReSharper, they both have features that would complement each other extremely well, unfortunately I can't use both at the same time and for now I am sticking with the EnhancedTooltips (which was updated recently) just because I have too much documentation I need to work with, but I feel like your extensions has some very strong aspects to it, like showing the source assembly of a type/member and hotspots for navigation.

**Comment by wmjordan** [comment]
`inheritdoc` and `inheritdocCref` are on my plan now.

**Comment by wmjordan** [comment]
I'd just committed new code to support this.
Please compile and test the code.
The `<inheritdoc cref>` support is by default disabled. Please turn it on in the options page.
