### ISSUE TITLE
Suggestion: Icon for compiler/analyzer messages on Super Quick Info

### ISSUE THREAD

**Issue by fitdev** [wmjordan/Codist#37]
It would be nice if Compiler/Analyzer errors/warnings/suggestions would be somehow separated from the rest of the text (such as member description), for example by having an appropriate icon (cross, exclamation, tip) to the left of the message as I suggest on the screenshot:

![2018-09-04 21_01_47-workspace net - microsoft visual studio](https://user-images.githubusercontent.com/8166847/45049164-76cc3200-b086-11e8-96e0-1466ee3d7a40.jpg)

**Comment by wmjordan** [comment]
I have had the same idea months ago.
The problem is that in VS 15.8 there is no way to identify where the tool tip item comes from.

**Comment by wmjordan** [comment]
For the same reason, #16 can not be implemented at this moment either.

**Comment by fitdev** [comment]
Oh I see. I hope they will add appropriate API to VS in the future. Would be quite useful! But at least, can you perhaps distinguish between item description and any extra info? That way you could still somehow visually separate the description from the rest.

**Comment by wmjordan** [comment]
> distinguish between item description and any extra info

Yes, this is possible.

**Comment by fitdev** [comment]
That's great that it can be visually distinguished! That would help quite a bit!

Sorry to mention it here, since this is related to Super Quick Info, but maybe too small of a thing for a new issue... It would be nice if Super Quick Info could display xml doc comments for namespaces as well. Currently it displays no xml doc comment when you hover over a namespace, even though xml doc is defined for that namespace.

**Comment by IneedHelp** [comment]
>  Currently it displays no xml doc comment when you hover over a namespace, even though xml doc is defined for that namespace.

I don't think namespaces are a valid language element to place XML comments on.

**Comment by wmjordan** [comment]
The compiler does not generate XML Doc for namespaces. So it is impossible to show them.

How do you think the 'distinguish' shall look like?

**Comment by IneedHelp** [comment]
> How do you think the 'distinguish' shall look like?

I don't mean to hijack @fitdev 's thread, but I would suggest separating data into groupboxes, that gives a nice visual representation of different blocks of information and it can also have a label explicitly showing the type of information.

**Comment by fitdev** [comment]
> How do you think the 'distinguish' shall look like?
Maybe a VS icon or some other icon to the left of the compiler-generated comment? A horizontal line between the description and compiler comment would be another option.

**Comment by wmjordan** [comment]
> Maybe a VS icon or some other icon to the left of the compiler-generated comment

Everybody knows that paragraph under the first line of the quick info is the documentation. I am sorry that I don't think it makes any practical sense.

However, after hours' attempts, I managed to make an icon on the diagnostics info.

![default](https://user-images.githubusercontent.com/12182730/45127673-00c1eb00-b1ac-11e8-8bc9-9268819c7c37.PNG)

**Comment by wmjordan** [comment]
> separating data into groupboxes, that gives a nice visual representation of different blocks of information

This will cost me hours. I am sorry that I am not good at WPF programming.
Nevertheless, don't take that as a declination.

**Comment by fitdev** [comment]
To me, after you have added the icon - it looks **much better**! I really like it. Perhaps in the future you, or someone else will figure out the "appropriate" part. But even with this small change it's great!

**Comment by wmjordan** [comment]
@fitdev 
I found a way to distinguish and classify the diagnostics messages today. Your request is now completely possible.

**Comment by fitdev** [comment]
@wmjordan That's really awesome! I already really enjoy using the updated Quick Info Tooltips with the info icon that you added. For one thing it now makes it much clearer that there is in fact more than one "issue" with the code (since multiple icons will be displayed), whereas previously it was harder to notice that and you had to in a way exert more to figure that out.

**Comment by wmjordan** [comment]
I approached a little bit forward.
However, currently I could only get diagnostics messages from the compiler, not from other analyzers.
Could we get those messages from analyzers, it is done.

**Comment by wmjordan** [comment]
@IneedHelp 
After hours' work, in the next version, I am making information grouped, as well as some other improvements to the _Super Quick Info_.
Please take a look at #68 where some screenshots were posted.

**Comment by wmjordan** [comment]
Thank you for your feedback.
Unfortunately no progress to the distinguishability yet.

**Comment by fitdev** [comment]
Latest VS 2019 versions have this functionality. So I am closing this issue.
