### ISSUE TITLE
Small Improvement to Parenthesis Colorization for Casts

### ISSUE THREAD

**Issue by fitdev** [wmjordan/Codist#39]
It would be nice if the parenthesis in the `(type)variable` cast operator would be colored differently (i.e. blue by default) if the type inside the parenthesis is written as a language keyword (all lower case, i.e. `bool`) as opposed to being written-out fully as type (i.e. `Boolean`). Right now, in all cases the latter formatting is assumed.

So, is it possible to have this:
![2018-09-13 12_22_12-workspace net - microsoft visual studio](https://user-images.githubusercontent.com/8166847/45479700-df36a580-b74f-11e8-8a63-cd531a25ea91.jpg)
turned into this (ignore the bold style of the parenthesis):
![2018-09-13 12_22_12-workspace net - microsoft visual studio_2](https://user-images.githubusercontent.com/8166847/45480016-9f23f280-b750-11e8-9e67-8a67b70e3b2a.jpg)

**Comment by wmjordan** [comment]
While I firstly implements the syntax highlight for braces, I had the same feeling as you got.
Afterward, I got used to it.

**Comment by fitdev** [comment]
I know it's a tiny thing. But maybe if you get around to it, if the fix is easy, it would be real nice. Though your extension is already very good! One of the best I have tried over 5 years! Keep up the excellent work!

**Comment by wmjordan** [comment]
I'll see whether it could be implemented in a way that affects performance as little as possible, _when I have time_. Meanwhile, I am developing new functions now. So many new ideas are coming forth once the gate to VSIX is opened for me.
So please be very very patient and don't take this as a declination.

**Comment by wmjordan** [comment]
Thank you very much for your high accolade!

**Comment by wmjordan** [comment]
I am consider closing this issue without implementation, since `(bool)` and `(Boolean)` are actually the same thing in C#, the parentheses should not be colorized differently.

**Comment by fitdev** [comment]
I understand. It's really a matter of personal preference, and you certainly have other priorities, as this is a tiny thing.
