### ISSUE TITLE
ValueTuple-Based Return Types not Properly Colorized

### ISSUE THREAD

**Issue by fitdev** [wmjordan/Codist#44]
Using your latest beta version, I just noticed that syntax highlighting seems to be completely wrong for cases when a method returns a value tuple with non-system (primitive) types. The colors are wrong, and there seems to be no user/non-user code distinction either...

Wrong:
![2018-10-05 11_14_25-](https://user-images.githubusercontent.com/8166847/46523916-e6089200-c88f-11e8-807e-4c80b40f3679.jpg)

Correct:
![2018-10-05 11_15_02-workspace net - microsoft visual studio](https://user-images.githubusercontent.com/8166847/46523950-f91b6200-c88f-11e8-81b9-2e09ca31cadf.jpg)

**Comment by wmjordan** [comment]
Got it.
I'll see how to add the `ValueTuple` support later.

**Comment by wmjordan** [comment]
I'd updated the Roslyn to the latest version. Could you still reproduce this issue with the new version?

**Comment by wmjordan** [comment]
The reason of the classification result is that the classifier could not only identify the _CharSpan_ in your example as a type, but also a **field** of the tuple.
If you explicitly name the field of the tuple fields, it could properly classify them.
I made a new version to address this issue. Please try this: [Codist.zip](https://github.com/wmjordan/Codist/files/2501300/Codist.zip)
