### ISSUE TITLE
Super Quick Info Suggestion - Add Framework Availability Info

### ISSUE THREAD

**Issue by fitdev** [wmjordan/Codist#45]
Perhaps you could further extend the Super Quick Info with information on whether the API is available in a particular framework (i.e. something like: ".Net Framework 4.5+, .Net Core 2.0+, ...").

The only feasible way to implement this that I see would probably to use [ApisOf.Net](https://apisof.net/) website. Of course there will be some latency (not sure if it is even possible to update VS tooltip once it has been displayed), but at least it would be a much more convenient way to find out about framework differences than by going to the browser and manually looking for it.

Of course on top of that you can include additional info from the website, like popularity.

**Comment by wmjordan** [comment]
Nowadays VS gives warning in Quick Info for symbols which are not included in a target platform, if a solution/project has multiple targetting platforms and the symbol is not available in any one of them.
Occasionally, I had similar requirements like that. But it took not so much time I found it on MSDN, not only the first version which introduced the API but also its documentations. Since it happened so scarcely, I am not sure whether this feature should be included in Codist.

**Comment by fitdev** [comment]
I see. Thank you for considering it. The issue I am having is because I rely on Shared Projects a lot, with them being used in both .Net Frameworek-based projects and .Net Core-based projects (though in different solutions often), so VS in this case is not telling me whether a particular API is available. But, I understand that potentially it requires quite a bit of work, so maybe you can get back to it later, once you have worked on higher priority items.

**Comment by wmjordan** [comment]
I understood your requirement. It is reasonable to have it, just like we need browser compatibility information for CSS properties or HTML elements, years ago.
Could you please help provide some code about how to access the information exposed from _ApisOf.net_?

**Comment by fitdev** [comment]
Yes, exactly like browser compatibility!

I tried to figure out the API for getting member/type information on their website, but to my surprise it seems to be html-only (having rest API just for search). So I guess, at this point, it would be problematic to implement this feature, unless they provide a publicly accessible API.

**Comment by wmjordan** [comment]
You may create a .NET Core project, including all source code files in your shared project, and change the target frameworks element (`Project/PropertyGroup/TargetFrameworks`), listing all platforms your code targets there and let Visual Studio show the availability information to you.

**Comment by wmjordan** [comment]
At this moment, you may need this tool:
https://marketplace.visualstudio.com/items?itemName=ConnieYau.NETPortabilityAnalyzer

However, it has not been updated for quite some time.

**Comment by fitdev** [comment]
Thank you for pointing this out. But for me the need for this feature has mostly passed. It seems that VS has already started highlighting API availability issues in code. Plus with the unification of Mono and Core BCLs this is not as big of a deal anymore.

**Comment by wmjordan** [comment]
Alright then.
I am closing this.
