### ISSUE TITLE
Feature Request: Code Statistics in NavBar or elsewhere

### ISSUE THREAD

**Issue by fitdev** [wmjordan/Codist#48]
Perhaps you can find a way to display useful statistics in the NavBar (either directly on the headers/titles, or in the tooltips, or some other way):

- number of lines that make up a member (if more than 1)
- number and kinds of members in a type / region 
- number of types in a namespace

Somewhere else it might be useful too to include:

- number of lines with code (in a file / type)
- number of empty/blank lines (in a file / type)
- number of comment / xml-doc-comment lines (in a file / type)

This is a low priority thing - just something to maybe integrate eventually in a useful way into the extension.

**Comment by wmjordan** [comment]
It is possible to show something beneath the member list now.
I can pick up this issue and show some statistics, for instance number of members, number of lines of code.

**Comment by fitdev** [comment]
Great news! Yes, that would be really nice! As for members - perhaps you can segregate those by member kind: method, property, field, etc.

**Comment by wmjordan** [comment]
There's new beta version which implements this feature.
By default it is not turned on. You have to turn it on by checking the "Code statistics" checkbox.
[Codist.zip](https://github.com/wmjordan/Codist/files/3169701/Codist.zip)

**Comment by fitdev** [comment]
Thank you for the new version! Really liked how you implemented statistics! It consumes very little space and does not get in your way. Great work!

One thing I noticed is that the member tooltip is functioning again for the items in the drop-down of Navi Bar. However, it seems to be very slow, in fact you can easily notice that as you hover with the mouse over the items in the drop-down, there is a visible delay between when the hover rectangle moves from one item to the next (apparently delay has to do with computing the info for the tooltip). Also, and perhaps related: the "Show Symbol Info Tip" option in the Navi Bar options does not do anything - whether it is checked or not, the tooltip is always displayed when you hover the mouse over NaviBar items.

**Comment by wmjordan** [comment]
Thank you for the quick feedback.

The member tool tip is not slow at all. Actually I'd spent hours on trying to control the "visible delay" you mentioned but failed to change it. On my machine, it is just too fast--no delay at all. I'd love to have a 300ms's delay between items.

I have trouble in providing an option for the member tool tip. The member tool tip is now shared by both NaviBar and SmartBar, since both of them use the same SymbolList control. They have to be disabled or enabled at the same time.

**Comment by fitdev** [comment]
I see. The delay for the tooltip makes sense, and 300ms is absolutely reasonable. What I noticed is that as I move my mouse vertically over the items in the dropdown of the NaviBar, the hover effect is being delayed. That is the item shown as being hovered i slagging behind the mouse. I just did some more tests and noticed that it does not always happen, but usually it happens _after the tooltip has been shown (and hidden)_. The behavior is back to normal (i.e. no delay for drawing the item hover state) after the dropown has been closed and reopened and no tooltip has yet been displayed OR after VS has lost focus. So, it seems that somehow tooltip delay (which is a correct behavior - tooltips should not be shown instantly, so you are absolutely right about this) is also sometimes causing the item hover redraw delay as well.

**Comment by wmjordan** [comment]
It was weird. The hover effect should not be delayed.
Would it be delayed, it could because VS was busy parsing the solution and preparing XML Documentations from your code.

**Comment by fitdev** [comment]
No, it happens all the time - even long after everything has been loaded and parsed. Here's the preview. In the first half of the video everything is smooth. But after the tooltip has been displayed, in the second half of the video the subsequent hovers are delayed. It is not as noticeable in this gif due to gif encoding, in real life the delay is a bit more pronounced.

![navibardelay](https://user-images.githubusercontent.com/8166847/57611694-14fc8a00-757c-11e9-9219-280b40656fe4.gif)

**Comment by wmjordan** [comment]
Since the statistics do not consume too much CPU and those numbers really help, I am going to remove the option and make it arbitrarily turned on.

**Comment by fitdev** [comment]
Perhaps you should leave the option so that if some people do not like to see the extra numbers, they can turn it off. Just make the default value for it to be turned on.

**Comment by wmjordan** [comment]
I am not very satisfied with the previous implementation which displayed filter buttons no matter corresponding members exist or not. For instance, a struct without methods or nested types should not have buttons for fields and types.

**Comment by fitdev** [comment]
Oh I see. That makes complete sense!

**Comment by wmjordan** [comment]
> Perhaps you can find a way to display useful statistics in the NavBar (either directly on the headers/titles, or in the tooltips, or some other way):
> 
> * number of lines that make up a member (if more than 1)

Planned.

> * number and kinds of members in a type / region
Done for type.
No plan for region.

> * number of types in a namespace
Planned.
It will not only show numbers, but also allow you to jump to any of them.

> 
> Somewhere else it might be useful too to include:
> 
> * number of lines with code (in a file / type)
Done.

> * number of empty/blank lines (in a file / type)
No plan.

> * number of comment / xml-doc-comment lines (in a file / type)
No plan.

**Comment by wmjordan** [comment]
In the recent beta version, if you select a namespace (anywhere in your code window), and choose the _Analysis symbol.../Find Members..._ command, you can list all types within a `namespace`. The buttons on the list are specially designed to help filter type kinds.

![捕获](https://user-images.githubusercontent.com/12182730/58375074-80cbf300-7f7d-11e9-80ee-51705b4835a8.PNG)

**Comment by fitdev** [comment]
That's great! I was not using the Smart Bar until now, but the functionality in _Analyze Symbol..._ makes it very worthwhile. Is there a way to trigger the _Analyze Symbol..._ menu purely from keyboard (when the cursor is over a valid symbol)? The best way would be if you can integrate this menu into VS's standard Quick Actions menu (accessible via Ctrl+. or Alt+Enter).

Also, another tiny suggestion: I just discovered that you can click on the Namespace / Type name in the Quick Info tooltip and it will show a new tooltip that lists all the files where that particular namespace or type is defined (in cases where it is defined in more than one file). That is very useful! However, could you also display full path information in yet another tooltip which appears when you hover over individual files?

**Comment by wmjordan** [comment]
> * Make this list scrollable
> * Also display full path information

They have already been planned after my symbol list control is developed. I am going to make greater use of that control in a next version after version 5 is released.
