### ISSUE TITLE
NavBar Keyboard Shortcut Interference

### ISSUE THREAD

**Issue by fitdev** [wmjordan/Codist#50]
I have noticed that whenever I am using Alt+[Letter] keyboard shortcuts in VS (Alt+D to duplicate line, or Alt+F, Alt+M to filter Intellisense completion list) NavBar gets focus and editor loses focus, causing unintended navigation. Using Codist 4.1.0.2718.

**Comment by wmjordan** [comment]
I am sorry that I could not reproduce this issue.
I tried every Alt + * combinations, none of them made NavBar got focus.

**Comment by wmjordan** [comment]
Theoretically there is no code to specify keyboard shortcut to the bar. I even especially used `TextBlock` to disable it.
Be sure to make a screen shot if it occurs again.

**Comment by fitdev** [comment]
Just happened now... See screenshot below.

All I did was (while trying to figure out _when_ it happens):
1. Place the cursor at the `RecipientName`
2. Press LeftAlt+D 2 times to duplicate line 2 times.
3. On the second duplication NavBar got focus, with the "//" element being selected, and the editor lost focus.

![2018-10-30 10_04_51-window](https://user-images.githubusercontent.com/8166847/47701602-66ba7400-dc2b-11e8-8baa-3004f8d2dee0.jpg)

**Comment by wmjordan** [comment]
Still no can reproduce.
I tried to assign Alt+D to the duplicate command, but nothing went wrong.

Why not use Ctrl+D to duplicate?

**Comment by fitdev** [comment]
I am used to Alt+D, but the problem is that it happens with Intellisense filter as well, not just with this particular command. Maybe another extension is causing some conflict, since it seems to happen only when Alt key is involved.

**Comment by fitdev** [comment]
Thank you for the new beta! I still get the same issue.

**Comment by wmjordan** [comment]
Then I could not do anything more about this issue :(

**Comment by fitdev** [comment]
I will let you know if I discover more hints. But right now, the Alt+D to duplicate the line is an almost sure way to switch focus from the editor to the NavBar. The strange thing is that before NavBar was introduced editor would never lose focus. I am not saying of course that it is the NavBar itself which somehow triggers it but that's an interesting observation. Anyways, don;t think too hard about it, since it isn't a major issue and your time would better be spent on major new features ;-)

**Comment by wmjordan** [comment]
You might have to use Ctrl+D instead of Alt+D since I could not reproduce your issue here even if I assigned that shortcut to the _Duplicate_ command here.

**Comment by fitdev** [comment]
I know, the thing is sometimes it happens with Intellisense drop-down open as I try to filter-out certain item types, and they use Alt+[letter] for that as well.

**Comment by wmjordan** [comment]
That's so weird.
Could you try disabling other third party extensions and see whether the conflict continually occurs?

**Comment by wmjordan** [comment]
I installed a minimal VS 2019 and the _Desktop Development_ payload with _Codist_.
I still could not reproduce this issue. You may have to examine other extensions.
