### ISSUE TITLE
Suggestion: NavBar Multiple Nested Namespaces Support

### ISSUE THREAD

**Issue by fitdev** [wmjordan/Codist#51]
Please add NavBar support for displaying multiple nested namespaces:

![2018-10-31 16_21_10-window](https://user-images.githubusercontent.com/8166847/47790761-0c9fd880-dd29-11e8-8114-887e147be6ef.jpg)

It would be great, if, for the above example, the **COLLECTIONS** drop-down also included _sub-namespaces_ `SORTING` and `TREES`. Of course, similarly, this should apply at all levels (if those namespaces, in turn would have included a sub-namespace as well).

**Comment by wmjordan** [comment]
Please try this beta:
