### ISSUE TITLE
Parenthesis Colorization of catch clause

### ISSUE THREAD

**Issue by fitdev** [wmjordan/Codist#55]
Perhaps this is a bug? I think that the parenthesis of the `catch ( ... )` clause in the example below should be colorized as well.

![2018-11-19 13_49_02-workspace net - microsoft visual studio](https://user-images.githubusercontent.com/8166847/48702563-46fee600-ec02-11e8-8de8-6223f185aaff.jpg)

**Comment by wmjordan** [comment]
Please try this new beta.

[Codist.zip](https://github.com/wmjordan/Codist/files/2597695/Codist.zip)

**Comment by fitdev** [comment]
Works great! Thank you!
