### ISSUE TITLE
VS 2019 Support

### ISSUE THREAD

**Issue by raznet** [wmjordan/Codist#58]
Please support VS 2019
Thanks for the great job!

**Comment by wmjordan** [comment]
Hi, thanks for the notifications. I'd been watching the preview version for quite a few weeks. Unfortunately I have gotten projects to work on. I am afraid that I could not afford the time installing the preview version.
I will try to alter the manifest file of the extension installation file later and let's try our lucks. If it runs on VS 2019, it runs. Otherwise, I will work on it when the RTM version is released.

**Comment by wmjordan** [comment]
Please try this new beta.
[Codist.zip](https://github.com/wmjordan/Codist/files/2648070/Codist.zip)

**Comment by wmjordan** [comment]
I am closing this issue if no problem is reported.
Please open an issue if Codist is not compatible with the final release version of VS 2019, and don't post issues about its pre-release versions.

**Comment by raznet** [comment]
Yes sry, i was not able to test it, too busy :(

I will do it tomorrow and inform you.
Thanks for the effort

**Comment by wmjordan** [comment]
Never mind.
I changed my mind to keep this issue open until VS 2019 is released.

**Comment by raznet** [comment]
Works like a charm, no problems at all

Thank you!

**Comment by wmjordan** [comment]
The updated VS 2019 Preview 2 has introduced new syntax highlight items, part of which overlap with those identified by Codist.
The new preview has also disabled the feature of identifying source code symbols from imported symbols.

**Comment by wmjordan** [comment]
This version fixed the broken syntax highlight in VS 2019 preview 2.

[Codist.zip](https://github.com/wmjordan/Codist/files/2798664/Codist.zip)

It is quite weird that the foreground color for local variable could not be black ARGB(0xFF,0,0,0). If it is black, the default syntax color will be used.

**Comment by wmjordan** [comment]
The new release version 4.6 had addressed the syntax highlight issue and made compatible with VS 2019 preview 2.

**Comment by wmjordan** [comment]
I've installed the preview version of VS 2019 and probably Codist will keep track of the support of the latest version.
