### ISSUE TITLE
Attributes Syntax Highlighting Bug in Certain Cases

### ISSUE THREAD

**Issue by fitdev** [wmjordan/Codist#60]
Hi! I am using your latest beta 4.2.2.2983 in VS2019 Preview. Everything is working great except, under some circumstances (presumable when nested inside `{   }` on a single line) attribute values are not properly highlighted (font size). See the pic below:

![2018-12-06 20_12_44-workspace net - indexrange cs](https://user-images.githubusercontent.com/8166847/49600434-443b1980-f994-11e8-8517-ab9d7a66d1ea.jpg)

In the sample above bothe the `(MethodImplOptions.AggressiveInlining)` as well as the leading `[` and trailing `]` should be smaller - same as the rest of the attribute.

**Comment by wmjordan** [comment]
Please try this new beta.
[Codist.zip](https://github.com/wmjordan/Codist/files/2655508/Codist.zip)

**Comment by fitdev** [comment]
Works great! Thank you so much!
