### ISSUE TITLE
Improvement: Display Operator Type/Name in the Members Dropdown on NavBar

### ISSUE THREAD

**Issue by fitdev** [wmjordan/Codist#61]
It would be nice, if the name (type) of operator was displayed in the drop-down for the Members on NavBar:

![2018-12-07 13_15_25-](https://user-images.githubusercontent.com/8166847/49641822-55326c00-fa22-11e8-8eff-1155c868c8ec.jpg)

As you can see from the screenshot above, right now all operators for a type look alike (unless they have different arguments). So, perhaps before (or after) the `operator` you would include symbolic/textual representation of what kind of operator it is.

**Comment by fitdev** [comment]
Oh and another issue:
The filter for "Fields and Properties" in the NavBar currently also includes implicit conversion operators for some reason. Clearly, operators, including implicit conversion ones, deserve their own category, or perhaps be included with methods, but certainly not fields and properties.

**Comment by fitdev** [comment]
And just a quick thumbs up: I really like how you display the values of constants and static fields in the NavBar's dropdowns right-aligned. That is very thoughtful and helps quite a lot!

**Comment by wmjordan** [comment]
Oh, I see. It must be a mistake. I will look into it.

**Comment by wmjordan** [comment]
Please try this new beta:
[Codist.zip](https://github.com/wmjordan/Codist/files/2657476/Codist.zip)

**Comment by fitdev** [comment]
Wow! Thanks for such a quick fix! Everything is looking good!

**Comment by wmjordan** [comment]
Previous betas had an issue which would crash VS in the Navi Bar.
Please update to the new version:

**Comment by fitdev** [comment]
Thank you for letting me know. I updated just in case, even though it never crashed on me.
