### ISSUE TITLE
List Group Headers in Syntax Highlight Options Page Were Hard to Read

### ISSUE THREAD

**Issue by fantasyz** [wmjordan/Codist#63]
Hi, its me again. 
Just want to let you know there is a little color issue in the config panel.

![group name issue](https://user-images.githubusercontent.com/3223242/50027508-73eac100-0027-11e9-8e8c-46b05c676901.jpg)

**Comment by wmjordan** [comment]
Known issue.
It is a WinForms ListView control. There's no way to customize the color or backgroud color of group headers in a ListView.

**Comment by wmjordan** [comment]
Please try this new beta:
[Codist.zip](https://github.com/wmjordan/Codist/files/2682433/Codist.zip)
