### ISSUE TITLE
VS 2019 Crash when Editing

### ISSUE THREAD

**Issue by fitdev** [wmjordan/Codist#64]
Using your latest version of Codist 4.3.0.3085, VS 2019 Crashes when I edit the file (by removing the text before `yield return` inside a method):

> Application: devenv.exe
> Framework Version: v4.0.30319
> Description: The process was terminated due to an unhandled exception.
> Exception Info: System.NullReferenceException
>    at Codist.CodeAnalysisHelper.GetExpressionSignature(Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax)
>    at Codist.CodeAnalysisHelper.GetDeclarationSignature(Microsoft.CodeAnalysis.SyntaxNode, Int32)
>    at Codist.NaviBar.CSharpBar+NaviItem.SetHeader(Microsoft.CodeAnalysis.SyntaxNode, Boolean, Boolean, Boolean)
>    at Codist.NaviBar.CSharpBar+<<Update>g__Update|9_0>d.MoveNext()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
>    at Codist.NaviBar.CSharpBar+<Update>d__9.MoveNext()
>    at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0(System.Object)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
>    at System.Windows.Threading.DispatcherOperation.InvokeImpl()
>    at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
>    at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
>    at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
>    at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
>    at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
>    at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
>    at System.Windows.Threading.DispatcherOperation.Invoke()
>    at System.Windows.Threading.Dispatcher.ProcessQueue()
>    at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
>    at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
>    at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
>    at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
>    at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)

**Comment by fitdev** [comment]
Thanks for a quick reply. Unfortunately I still get the crash:

> Application: devenv.exe
> Framework Version: v4.0.30319
> Description: The process was terminated due to an unhandled exception.
> Exception Info: System.NullReferenceException
>    at Codist.CodeAnalysisHelper.GetExpressionSignature(Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax)
>    at Codist.CodeAnalysisHelper.GetDeclarationSignature(Microsoft.CodeAnalysis.SyntaxNode, Int32)
>    at Codist.NaviBar.CSharpBar+NaviItem.SetHeader(Microsoft.CodeAnalysis.SyntaxNode, Boolean, Boolean, Boolean)
>    at Codist.NaviBar.CSharpBar+<<Update>g__Update|10_0>d.MoveNext()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
>    at Codist.NaviBar.CSharpBar+<Update>d__10.MoveNext()
>    at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0(System.Object)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
>    at System.Windows.Threading.DispatcherOperation.InvokeImpl()
>    at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
>    at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
>    at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
>    at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
>    at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
>    at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
>    at System.Windows.Threading.DispatcherOperation.Invoke()
>    at System.Windows.Threading.Dispatcher.ProcessQueue()
>    at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
>    at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
>    at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
>    at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
>    at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)

What happens is this:

```
  public abstract class ItemReaderBase<T> : IEnumerable<T> where T : ItemBase, new() {

    protected abstract bool GetT(XElement itemElement, ref T initializedItem);

    public IEnumerator<T> GetEnumerator() {
      foreach (var i in doc.Descendants(itemElementName))
          var t = new T();
          if (GetT(i, ref t)) yield return t;
    }

    IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
  }
```

As soon as I delete (backspace) `t` in the `if (GetT(i, ref t)) yield return t;`, an Intellisense popup appears. I ignore the popup and click off somewhere, so the popup closes and I have erroneous `if (GetT(i, ref t)) yield return ;`. Then after about a second later VS freezes for like 5 seconds, and then terminates. Hope it helps.

**Comment by wmjordan** [comment]
It did help.
Please use this new beta.
[Codist.zip](https://github.com/wmjordan/Codist/files/2689275/Codist.zip)

**Comment by wmjordan** [comment]
I just uploaded a new beta which altered the Navi Bar.
Please help test it and give some feedback.
[Codist.zip](https://github.com/wmjordan/Codist/files/2690014/Codist.zip)

**Comment by fitdev** [comment]
Thank you for your awesome work! The bug appears to be fixed now, VS no longer freezes or crashes.

As for the updated NavBar, I think you did a good job of merging the two. In fact, at first I was surprised to see that there even was this extra button before the namespace, as I was not sure what it did.

One tiny thing (but don't take it too seriously) is that the icon for the "Search Declaration", to me, looked like the stereotypical spherical bomb (with a lit fuse), only upon closer examination I discovered that the "fuse" was the magnifying glass, and the "bomb" was an abstract shape. But it could be just me :)

The new design, however begs for a serious extension of the NavBar (in my view), extending its purpose, I guess. Here's what I mean, the first button now is the namespace. More often than not, it's not a root namespace, but a subnamespace. So if a `file1.cs` has `namespace RootNS.SubNS { class ClassA { ... } }`, then the NavBar would begin with `SubNS`. However it would be great, if it began with the entire namespace hierarchy (but grayed-out / dimmed) so that:

 - User see a bigger picture of where a particular namespace and types that are defined in the current file fit
 - Also it would allow for a much easier navigation, and quicker understanding of the project structure in general
 - When a user click on one of the dimmed "super"-namespace buttons, the dropdown would show a list of namespaces and or types defined within that namespace (all dimmed too, unless they are part of the current file).
 - When the user click on the "current" namespace button (i.e. currently the first button being displayed), it would show not only the types defined in the current file, but also in other files (dimmed, since they are not part of the current file).

So, in effect, it would kind of expose the functionality of Class Viewer in a much more accessible and user-friendly way. I realize it can be a lot of work, and might potentially slow things down, but I think it would be a great extension of the already very capable Nav Bar!

**Comment by wmjordan** [comment]
Thank you very much for the in-depth feedback and proposal.
The hierarchical view of namespace **may not slow things down too much**, I guess, at this moment. Thus, it is technically viable.
But I am not very sure whether that design will _allow for a much easier navigation_.

The very similar idea once came into my mind at the beginning of the design and development of NaviBar, but finally I dropped it, being afraid of the namespace parts taking too much space on the bar and leaving less space for syntax node details about branches, expressions, parameter lists.
However, after some daily use of the Navi Bar, I found that the syntax node details were not so useful to me and I recently disabled them in my configurations. Therefore, some room was made available for the namespace hierarchical nodes.

**Comment by wmjordan** [comment]
_The icon for the "Search Declaration"_ was really bad, for me too, but it was the one defined in VS for "Search Members". I will use another one despite of that.

**Comment by fitdev** [comment]
You are very welcome! Glad to hear you had a similar idea!

Good to know it won't slow things down much, because that was one of my main concerns. One of the things I really like about your extension, compared with others, is that generally it is very fast, so you don't notice it affecting VS performance in any way, which is great.

> But I am not very sure whether that design will _allow for a much easier navigation._

Well, maybe not _much_ easier, but it would certainly help, especially in cases where a single file might have several types defined that belong to different (perhaps nested) namespaces. That way you would immediately know where in the hierarchy you are, so to speak, just by looking at the Navi Bar, instead of having to scroll up or hover over type name in code to actually see the namespace hierarchy.

Plus, if you combine that with ability to list other types (those that are _not_ defined in the current file) in the parent namespaces, then it really becomes very useful. In fact, you could add browser-like behavior for opening their respected code files: regular click - open in current tab, middle-click - open in new tab (but that's a matter of preferences really - just a quick idea in case you like it).

> However, after some daily use of the Navi Bar, I found that the syntax node details were not so useful to me...

I felt the same way actually! I still think that sub-member navigation may be useful in the following cases though:

- Local functions
- Really long methods with regions (probably pretty rare)
- Really long methods with a lot of different / nested scopes that do not fit in one screen

So, perhaps, you could have it as an option. In fact, now that I think about it, you could have 4 distinct parts for the Navi Bar:

1. "Upper" / Parent Namespaces
2. Current Namespaces, Types, Regions, Members - all present in the active file
3. Sub-member scopes: Local Functions, Regions, Large Scopes
4. All the way down to the expression-level - parameters, operands, etc.

Then you could have 1, 3, and 4 toggleable as options for the Navi Bar. Perhaps with 4 and maybe 1 too being turned off by default (though I would suggest leave 1 on and wait for feedback, otherwise this feature might not be easily discovered / understood).

And as for space in general, it's good that you have been conservative in that regard, but in all my usage, I hardly saw the NaviBar being filled to more than 60% of the width, even with sub-member parts included. Plus, though not sure if VS lets you do that, you might reduce the size of the Project Selector Combobox that's to the left of the Navi Bar. Right now it takes 1/3 of the window width, but in my case at least, 70% of that space is wasted - since few projects have names that are so long. So, if you could shrink Project Selector Combobox, and just give it some minimum width, that would give more space for the Navi Bar.

> _The icon for the "Search Declaration"_ was really bad, for me too, but it was the one defined in VS for "Search Members". I will use another one despite of that.

Oh, I am sorry, I didn't know it was a built in icon. Well, MS was never really good in the UI design department, so no surprises there I guess.

**Comment by wmjordan** [comment]
Thank you for sharing your thoughts!

About the nested namespace items:
I'd read quite a few open source projects, but none of them write nested namespaces within a single code file.
Currently, the namespace drop down menu has a file/project scope declaration search box. If there are more than one namespace drop down menus, where shall we place the search box? To avoid confusion, there should not be more than one search box. Is it appropriate to place the search box in drop down menu of the first namespace on the bar?

**Comment by fitdev** [comment]
I agree, it is quite rare, but sometimes could be useful. One possible example could be something like:

```
namespace Core {
  namespace Feature {
    public class Something {}
  }
  public static partial class CommonExtensions {
    // Extension methods for Feature.Something type.
  }
}
```

But regardless of whether or not the active file has nested namespaces, the ability to include "parent" namespaces in the Navi Bar (albeit dimmed / grayed if they are not contained in the active file) is highly valuable! So, just to be clear, I also meant the inclusion even of those namespaces that are not present in the active file, i.e. "parent" ones. So, for instance, if you are editing `Core.Geometry.Point2D` inside the `Point2D.cs` file (and that file contains _just_ the `Point2D` type), the Navi Bar would display: `{} Core` (Dimmed, because not part of the file) > `Geometry` (normal color, since directly a parent of the type defined in the active file) > `Point2D`.

Good point about the search box, now that it has been merged! I think there is a good way to have multiple search boxes (one for each namespace drop-down) that provide value and avoid confusion. Basically for each namespace dropdown the search would be limited to the appropriate namespace, so that it can search the whole project, but only look inside a specific namespace (for which the dropdown is being displayed). To make this clear, you can change title to: "Search Declaration in [Namespace Goes Here]".

So, I think you can salvage the current design, avoid confusion, and provide more granular functionality - all at the same time! In fact, it's easy to imagine a scenario where user wants to limit search results for say "con..." to only a particular namespace, as otherwise he/she would be overwhelmed by too many results from everywhere, since "con" is a frequently occurring text.

Hope this suggestion makes sense.

**Comment by wmjordan** [comment]
I opened issue #67 for the full namespace path feature request, which sounds quite reasonable.
Please take part in the discussion there.
