### ISSUE TITLE
Performance Was Bad when Navi Bar or Smart Bar Menus Were Populating Lots of Items

### ISSUE THREAD

**Issue by wmjordan** [wmjordan/Codist#65]
It took a lot of time when the drop down menus in the _Navigation Bar_ or _Smart Bar_ were populating a lot of items, for instance, executing Find Members command against `KnownImageIds` which contained almost 3600 items.

**Comment by fitdev** [comment]
I also noticed a slowdown when opening a drop-down for a partial type. In my case it is split between around 10-15 files, and each file has around 10-50 members. The delay before the dropdown appeared was around 4 seconds, and the CPU spiked. Not sure if it can be helped, but just from the intuition, it does seem a bit too much for this sort of workload, since generating a list of ~500-800 items should not take that long. I am sure you will be able to find a way to speed it up though!

**Comment by wmjordan** [comment]
Yes, currently more than 100 items in a menu can cause obvious pause and 500-up items are definitely slow.
I am going to avoid the use of menus, since they do not support drag and drop, nor run fast enough, and use virtualized `ListBox`es.

**Comment by wmjordan** [comment]
@fitdev I began to work on this issue today. There are so much to do and the next version could not emerge within the recent weeks. Anyway, the work has begun.

**Comment by fitdev** [comment]
@wmjordan That's awesome news! Wish you luck with this! I sure will be the first to test it out when it comes out!

**Comment by wmjordan** [comment]
Things seemed to go on well after two days' hard work.

In the internal test version, the drop-down class member menu in _NaviBar_ appeared within a second even in debug mode, compared with the public release version which could hang VS for 10 to 20 seconds, when trying to display members of the `KnownImageIds` class with almost 3600 members.

**Comment by fitdev** [comment]
This is a huge improvement! Great work! Perhaps then you will be able to implement drag-drop functionality to move items around, once you fully switch to a list-based approach for drop-down menus.

**Comment by wmjordan** [comment]
Yes, supporting drag-and-drop is my goal.

**Comment by wmjordan** [comment]
There is a new test version of [Codist.zip](https://github.com/wmjordan/Codist/files/3155439/Codist.zip).

With the newly programmed symbol list control, it is much faster to list types containing hundreds of members. Please test it and give post new issues if you find one.

**Comment by fitdev** [comment]
Yeah, the speed is amazing now! Excellent work!

I did not yet give it a proper try though, so I may add more notes in the near future, but the only thing that I noticed right away is that there is no longer a tooltip when you hover over items (members) in the list as well as on the Navi Bar itself. Hope you add those back.

As an aside I liked the inclusion of background icons in the Super Quick Info that designate the kind of identifier (struct, class, method, etc). The only thing (it's a matter of preference of course), is that perhaps it will better to display it in the upper-left corner (before the title) as a smaller icon with full opacity (as opposed to a bigger, semi-transparent icons in the background in the lower-left corner as it is now).

**Comment by wmjordan** [comment]
Thank you for your quick reply.

For the tooltip--yep, it will be back later.

The icon in the Super Quick Info was deliberately moved from the top left to bottom right for the _Alternative Style_ (you can turn it off and revert to the original appearance by unchecking the corresponding setting in the Options page of _Quick Info/C#_). Initially I did put it on the upper-left corner. And I found that it was inefficient. The code signature was squeezed to the right side and it reduced my productivity, since in most cases I don't want the icon located at my first sight to the Quick Info.
Therefore I tried to move it to the upper right, and then down to the bottom right, and I found the Quick Info looked quite neat and clean on the upper-left then, and it on the bottom right being a larger semi-transparent one might be better to leave with.
