### ISSUE TITLE
Tiny Syntax Highlight Bug in Fixed Block

### ISSUE THREAD

**Issue by fitdev** [wmjordan/Codist#66]
Just noticed there is a mismatch in the styles of the `fixed` keyword when used to define block scope and its braces / parenthesis:

![2018-12-18 18_59_33-window](https://user-images.githubusercontent.com/8166847/50166050-3cb23380-02f7-11e9-9f90-fa1af7fb379a.jpg)

**Comment by wmjordan** [comment]
Thank you for pointing this out.

I was fixing a problem which had haunted _Codist_ on the first day when the _advanced syntax highlight_ feature was developed--the highlighted results were hard to read on the dark red break point highlight. The fix had unintentionally broken the highlight of highlighter for classified keywords.

Please try this new beta.
[Codist.zip](https://github.com/wmjordan/Codist/files/2692856/Codist.zip)

**Comment by fitdev** [comment]
It's working great now! Thank you for such a quick fix! You are awesome!
