### ISSUE TITLE
More Color Presets for Syntax Highlight; Apply Colors only When Importing Highlight Presets

### ISSUE THREAD

**Issue by Aidolii** [wmjordan/Codist#69]
![What a mess](https://i.imgur.com/fWmXNrk.png)

The super super dark blue text are category headers or something? They just select the option right below them.

There's also this eyesore, 'Exact Method Name'

![Oh god my eyes](https://i.imgur.com/6McKoKj.png)

Anyway for the most part Codist is really good, I just wish the presets were better, it's a shame it's just color presets that need a lot of extra tuning. I think there should be more presets, showing off the text styling and sizing, perhaps independently of being able to change the colors so you can pair any color preset with any style/size preset.

**Comment by wmjordan** [comment]
Please refer to #63 where a beta version was posted to solve this.
The next version which improve that will be released in a short time.

Due to the limitation of `ListBox` in `WinForms`, gradient background could not be draw. Please click the _Extern Method Name_ item and see its simulated rendition in the Preview box.

**Comment by Aidolii** [comment]
I'm actually already using the beta version provided in #63.

**Comment by Aidolii** [comment]
My mistake, I was using the version provided in #62.

**Comment by Aidolii** [comment]
Okay, this is much better, thank you.

**Comment by wmjordan** [comment]
I'd just made a new beta which allows you to filter parts of imported themes or styles files.
Please test it.

[Codist.zip](https://github.com/wmjordan/Codist/files/2716234/Codist.zip)

**Comment by wmjordan** [comment]
Currently I don't have to to design more themes, but I have posted a pinned issue which allows users to share their themes. Nice shared themes can be integrated to future versions of _Codist_.

**Comment by Aidolii** [comment]
Not including any style changes to your default presets means you don't get to showcase the usefulness of the feature. A user may just click a theme button and never look into it again.

Making one or more of the themes do something similar to this would be appropriate: ~[](https://github.com/wmjordan/Codist/raw/master/doc/super-quick-info-12.png)

**Comment by Aidolii** [comment]
Also, would you consider using this for the color picker? It's covered under the MIT License.

https://github.com/cyotek/Cyotek.Windows.Forms.ColorPicker/
![](https://i.stack.imgur.com/4ipYA.png)

**Comment by wmjordan** [comment]
I'd just uploaded two themes on the gallery (#71) which contains effects and font sizes. Those two themes will be included as builtin themes in the next version of Codist. Please take a look at them or try them.

BTW, do you know how to host the ColorPicker control in a drop-down menu?

**Comment by wmjordan** [comment]
As your suggestion, the preset themes now leverages powers of advanced syntax highlight.

**Comment by Aidolii** [comment]
Nice, thanks!! And no, I don't know how to host that ColorPicker in a drop-down menu, sorry.
