### ISSUE TITLE
idea about region

### ISSUE THREAD

**Issue by fantasyz** [wmjordan/Codist#70]
Just little ideas about improving region. Sometimes people use region to enclose a bunch of function / or code. I occasionally find myself near the end of a region block and want to collapse it but find it not easy to do so I have the following idea:

1. Folding a region from the closing region. It seems now only possible to close a region from the [+] on the opening region by default.

2. Or being able to jump to the starting region code line. (Ctrl+Click or hot key on endregion keyword, or small button similar to [+] icon but with arrow up symbol will be nice).  We could just jump to the starting region and then close it manually. At least better than finding it by scrolling. There a plugins to jump between opening/closing brackets but seem none are supporting region.

The ideas may not be what Codist want to have. I am just posting them out and see if it is interesting to you.
Thanks.

**Comment by wmjordan** [comment]
How about that when you double click (select) the `#endregion`, the _Smart Bar_ pops up, offering a "Collapse region" button and some other operations to you?

**Comment by fantasyz** [comment]
> How about that when you double click (select) the #endregion, the Smart Bar pops up, offering a "Collapse region" button and some other operations to you?

I am not sure if it is a good idea to have an extra button to the Smart Bar. The bar already has lots of buttons. I guess some buttons on smart bar is also not applicable to region too. 

Btw, the smart bar currently also from time to time interrupt my "copy and paste" routine by suddenly popping up under my cursor before I do a click and ctrl+v...I think it is due to the fact that smart bar is using double click or selection change to trigger. Many people like me also use double click to select text for copy & paste. Selection also change by that. Thus there is a situation Smartbar is popping up unintended. Maybe adding a 3rd approach like having Smart bar visible only when certain key is holding down would be better. (Ctrl, Shift, etc ) 

About the "double click" triggering, is this a editor limitation? A more ideal behavior would be to have the button visible when focus/cursor is on the \#endregion code line without any further action (if the button is designed to be dynamic and not always visible like the [+] button). However, if such feature is designed to be part of smart bar, and if smart bar can be triggered by holding down a key like mentioned earlier, that would be convenient too. (better have unrelated buttons hidden when focus is detected to be region)

**Comment by fantasyz** [comment]
Correction: 

About the holding down to trigger suggestion. Shift key is probably not suitable because user may want to use shift key to do multi-line selection and smart bar popping up could cover surrounding codes which is not desired.

**Comment by wmjordan** [comment]
There aren't so many buttons on _Smart Bar_ when you select an `#endregion`.

I'd been using `Smart Bar` for quite a few months. I didn't notice how it "interrupted" my copy-and-paste operations, but on the contrary, it saved my left hand since I no longer needed to press Ctrl+C, Ctrl+X or Ctrl+V any more. Those shortcut keys have their corresponding counterparts on the bar. Select some text, click a button on the bar = copy / paste is done.

You have an option to disable the auto-popup of _Smart Bar_, and alternatively you can double-tap the Shift key to bring it up.

**Comment by fantasyz** [comment]
> Anyway, please share your experience about how the Smart Bar interfere your working rhythm and let's see whether it is possible to make it better.
Being able to turn off double click/selection change triggering is good enough.

Let's get back to the original topic. Are you decided to have the region button part of the smart bar? It looks like none of the buttons are related to region. If this is the case, it maybe better to have this region collapse button show dynamically when cursor is anywhere within a region block and the button simply fold current active region. (Not requiring focus to be on the \#regionend. more intiutive)

**Comment by wmjordan** [comment]
> Are you decided to have the region button part of the smart bar?

An alternative is to show up containing `#region` or even other directives on _Navi Bar_. So you can click and select them. Smart Bar showing up consequently offers you more operations on those directives.
However, the primary issue of this design is performance.
It is not so easy to retrieve enclosing directives via Roslyn, quite unfortunately. We have to **scan through the whole syntax tree** to find out them. This will definitely slow things down when _keyboard addicted programmers_ using cursor keys to move around a long document.

> it maybe better to have this region collapse button show dynamically when cursor is anywhere within a region block and the button simply fold current active region

This hopefully won't slow down things too much.

I will see whether there is a better way to handle this.

**Comment by fantasyz** [comment]
I don't know the detail about using Roslyn. But isn't it just scanning the code upward to find a \#region before a \#endregion to determine the active region? How slow are you talking about?

**Comment by wmjordan** [comment]
> isn't it just scanning the code upward to find a #region before a #endregion to determine the active region?

It is simpler said than done.

Nevertheless, I found a way to quickly find out surrounding `#regions`--unfortunately it only applies to `#region`s, not `#if`s.

![default](https://user-images.githubusercontent.com/12182730/50417579-3b868680-0862-11e9-9237-a852627da347.PNG)

**Comment by fantasyz** [comment]
This is not your fault but I think I will be in trouble by this change. All my regions in the project has decorative paddings to the name of the region to make them easier to be noticed.  If I don't fix all the region names, I have a feeling my Navi bar will not be able to show the function name due to inefficient space. haha

![region](https://user-images.githubusercontent.com/3223242/50419144-27df1e00-086a-11e9-8d19-181e3f578913.jpg)

Btw, you screenshot is also showing similar situation with two nested regions in it. It could just happen simply with a long name. Not sure if limiting the region text length would improve the situation. e.g. cap at 24 characters and append with '...' for people who type a sentence long name. For my case, I think I will just use find and replace to fix the name for me.

Anyway, thanks, looking good.

**Comment by wmjordan** [comment]
Thanks for the comment. I thought of that while I was testing.
Maybe it is possible to offer an option to strip leading and trailing non-letter characters for region names and limit their max-width.

**Comment by wmjordan** [comment]
I'd just made a new beta.
Please test it.
[Codist.zip](https://github.com/wmjordan/Codist/files/2715996/Codist.zip)

**Comment by wmjordan** [comment]
By default region names are not displayed on _Navi Bar_.
You need to turn on the setting in the options page.

**Comment by wmjordan** [comment]
I'd just made a new beta for your request.
Please test it.
By default region names are not displayed on _Navi Bar_.
You need to turn on the setting in the options page.
[Codist.zip](https://github.com/wmjordan/Codist/files/2716234/Codist.zip)

**Comment by fantasyz** [comment]
Thanks, will try when back to work.

**Comment by fantasyz** [comment]
Just tested it on my project.  Everything seems working fine. The non-alphabet trimming is chopping the text correctly.  No problem whatsoever. 
Excellent job!

**Comment by wmjordan** [comment]
It is in the new version 4.5.1 now. Thanks for sharing your ideas.
