### ISSUE TITLE
Identifier color takes precedence over namespace color

### ISSUE THREAD

**Issue by TechInterMezzo** [wmjordan/Codist#72]
Visual Studio 2017 - Community

If I set the color for "Identifier" under "All languages", then the color for "Namespace Name" under "C#" gets ignored and the identifier color is showed for namespaces. If "Identifier" is not set, everything works as expected.

**Comment by wmjordan** [comment]
Thank you for reporting this issue.
I will fix this later.

**Comment by wmjordan** [comment]
This issue should have been fixed in the last beta which has been just uploaded.
Please test with the new version.

**Comment by TechInterMezzo** [comment]
Yes, that issue seems to be solved. I tested it under VS 2019.
