### ISSUE TITLE
Suggestion: Allow color-independent opacity setting for syntax highlight style

### ISSUE THREAD

**Issue by fitdev** [wmjordan/Codist#73]
It would be nice if opacity of the (foreground/background color) could be adjusted without affecting the already assigned color (R,G,B values). Right now, if you change the opacity for a given style, the color-component is effectively set to black (or whatever color is selected). Is it possible to change opacity only, and have the original color-component unchanged?

**Comment by wmjordan** [comment]
Yes. It is possible. I thought of the previously as well.
The style configuration page has to be redesigned.

**Comment by wmjordan** [comment]
There's an updated beta version here:
https://github.com/wmjordan/Codist/issues/58#issuecomment-457805480

**Comment by fitdev** [comment]
Thank you for the new preview! It works great!

Just a quick question: I noticed that v 4.5 Codist.dll is almost 5 times as small as v 4.4. How did you manage to reduce the size so much and still add new features? I did not notice any new dlls that could account for refactoring.

**Comment by fitdev** [comment]
And one more thing regarding NavBar. Not sure how long it's been that way, but I just noticed it:

- Currently selected item in the NavBar's drop-down is barely visible (at least in VS2019 Preview 2)
- Start of Region directive is probably too bold, and may I suggest it should have a horizontal line somewhere for symmetry with the End of Region item.

![2019_01_29_10_05_32_workspace net_indexrange](https://user-images.githubusercontent.com/8166847/51890859-580c6600-23ae-11e9-8fc6-681ee0311762.jpg)

**Comment by wmjordan** [comment]
> I noticed that v 4.5 Codist.dll is almost 5 times as small as v 4.4.
> How did you manage to reduce the size so much and still add new features?

Good observation. It is weird that more and more resources were ADDED instead of updated into the DLL during the evolution of the project. I eventually realized this and trashed junk resources by executing the Clean Up command.

**Comment by wmjordan** [comment]
> * Currently selected item in the NavBar's drop-down is barely visible (at least in VS2019 Preview 2)

I noticed that too.

> * Start of Region directive is probably too bold, and may I suggest it should have a horizontal line somewhere for symmetry with the End of Region item.

I don't quite want to tweak this currently.

When solving #65 , the menu controls have to be rewritten and redesigned and the style customization can be done at that time.

**Comment by fitdev** [comment]
Oh I see. That makes sense. I was not sure actually if you have already done the redesign or not. Of course it makes sense to wait then! Really looking forward to NavBar's performance improvements!

**Comment by wmjordan** [comment]
At the time when I was about to work on the performance issue, VS 2019 Preview 2 was pushed and I found that the syntax highlight feature got broken there. You and I, as well as some other Codist users was trying it periodically. Thus I changed my schedule.

I will get back to the performance problem when the next version which supports VS 2019 Preview 2 is released.

The redesign (for #65 and #49) requires abandoning existing menus in Codist (yes, **all of them**!) and use ListBoxes instead which support item virtualization and drag-and-drop. It can take quite some hours since I have never programmed WPF drag-and-drop nor data virtualization. Please stay tuned.

**Comment by fitdev** [comment]
I see. That makes sense. Thank you for explanation. It's really nice that you are able to adjust your schedule so that priority issues are addressed first (though I have not noticed syntax highlight issue in Preview 2 before the update, but then I was not using it extensively)!

Also, glad to know that the redesign of NavBar with ListBoxes is not abandoned and you are working on it. I am certain you will be able to come up with a good solution, as you have shown time and again! Thank you for your great work!

**Comment by wmjordan** [comment]
Here is a new beta version which has addressed the vague selection issue and changed the opacity setting from numeric boxes to drop-down buttons, which might be easier to understand and use.

[Codist.zip](https://github.com/wmjordan/Codist/files/2811152/Codist.zip)

**Comment by fitdev** [comment]
Yeah the new style is a great improvement! Thank you!
