### ISSUE TITLE
Small Improvement: Show Analyzer IDs as Links in Super Quick Info 

### ISSUE THREAD

**Issue by fitdev** [wmjordan/Codist#74]
It would be nice if the ID of a specific analyzer would be shown in Super Quick Info (probably at the end of the its message). Ideally that ID would be clickable as it is in the "Lightbulb" menu:

![2019-02-05 09_36_00-workspace net - indexrange cs](https://user-images.githubusercontent.com/8166847/52256989-edb57180-2929-11e9-979e-7d4a9d271cff.jpg)

![2019-02-05 09_36_20-](https://user-images.githubusercontent.com/8166847/52256994-f5751600-2929-11e9-8fb9-669844d866c0.jpg)

So, in the above example `RCS1198` could appear after "...of value type." Perhaps in parenthesis.

**Comment by wmjordan** [comment]
Actually it is the same request as #37 .
If this can be implemented, #37 could have been implemented.

**Comment by fitdev** [comment]
Oh, I see. I didn't realize that they are connected. Perhaps VS at some point will add appropriate APIs, so that this feature can be implemented.

**Comment by wmjordan** [comment]
It seems that this can be closed, since this feature is now available in VS 2019 16.7 preview 2 and fortunately the Super Quick Info is working well together with the new improvements of VS.
