### ISSUE TITLE
Suggestion: List Interface members in Super Quick Info

### ISSUE THREAD

**Issue by fitdev** [wmjordan/Codist#75]
Lately I find that I often need to quickly see which members are part of an Interface when I hover mouse over `ISomething`. Currently Super Quick Info displays inheritance hierarchy only. I thought it would be great if a list of members (at least for the interfaces) could be provided as well, right there in the tooltip (perhaps a scrollable mini-list).

And a related feature in regards to Interfaces (though I am not sure if it will be possible) would be to add another syntax highlighting category: implemented member (declaration), so that members of classes / structs that implement interfaces could be colorized (right now there is functionality for override members only).

Thank you.

**Comment by wmjordan** [comment]
> I find that I often need to quickly see which members are part of an Interface when I hover mouse over `ISomething`.

Please upgrade to the latest version which was released yesterday and check the "**Interface members**" in the options page of _Super Quick Info_.

> members of classes / structs that implement interfaces could be colorized

This could considerably slow down the highlighter, I am afraid.

**Comment by fitdev** [comment]
That was very stupid of me. I in fact updated to the latest version before I submitted this issue, not even thinking to check in the Super Quick Info options. I forgot how quickly you implement new features! ;-) That's exactly what I was looking for, and it's really thoughtful for you to already include it!

As for colorizing members that implement interfaces - that's what I was fearing that it would add considerable overhead. Perhaps you can include it in the backlog, and wait till they introduce new functionality into Roslyn perhaps so that the feature could still be implemented but the performance hit would not be as large.

**Comment by wmjordan** [comment]
Actually the code for listing interface members have been done for [quite several weeks before](https://github.com/wmjordan/Codist/commit/991624e716f8b2feda95e3394e9ae0cc69fec8e4).

The interface implementation highlight feature may not be implemented within the recent future for its complexity.

For each member to be highlighted, we have to run the following procedures:

1. Get the containing type of the member,
2. Traverse the class hierarchy of the type and for each type in the hierarchy, find out implemented interfaces and also their parent interfaces.
3. Check each interface for a member having the same name and the same signature with the current member, for methods, we not only have to match the return type, but also each parameter types.

**Comment by fitdev** [comment]
I see, yes that's a lot of work. I thought that perhaps Roslyn had or will have in the near future something that exposes the name of the Interface a particular member implements (if any).
