### ISSUE TITLE
Enhancement: Include parameter attributes in QuickInfo

### ISSUE THREAD

**Issue by StevenBonePgh** [wmjordan/Codist#78]
QuickInfo is awesome! One thing missing is the ability to show attributes on the parameters, which would be incredibly helpful when looking at code annotated with JetBrains Resharper annotations.

**Comment by wmjordan** [comment]
Thank you very much for your comment.
I will work on it.

**Comment by wmjordan** [comment]
There is a new test version of [Codist.zip](https://github.com/wmjordan/Codist/files/3155439/Codist.zip).

It includes parameter attributes in Quick Info now.
Please test it and give post new issues if you find any.

**Comment by StevenBonePgh** [comment]
Works great, thank you for the update!
