### ISSUE TITLE
Idea/Suggestion: Add More Information to NaviBar Dropdown's Items

### ISSUE THREAD

**Issue by fitdev** [wmjordan/Codist#82]
I got an idea about improving item presentation in NaviBar's dropdowns. This is just a rough idea, but perhaps you will take parts of it and implement it in the future.

Perhaps you can visually display the "importance" or "weight" of an item / member in the NaviBar's dropdown by drawing the background as a progress bar of sorts, or giving it a color scale. This would be similar to Excel's feature of automatically coloring cells according to their value.

In the case of NaviBar's dropdown items the actual "value" that is visualized may be any of the following (ideally selectable via options):
- Lines of code
- Number of references
- Complexity

As a side note, if it is not expensive to calculate the number of references (perhaps even clickable) might be shown next to the item in the dropdown.

**Comment by wmjordan** [comment]
I thought about that previously as well.
However, very unfortunately, the _Number of references_ are **EXPENSIVE**!

If your VS have _CodeLens_, you will notice that their updates are not in real time, but quite somewhat delayed, due to the complexity of calculations. I saw numbers of references not in sync with the code from time to time.

**Comment by fitdev** [comment]
Yeah, I thought so too that it would be expensive. But perhaps, later you might then consider it doing the same way as VS does it with CodeLens (i.e. delayed), but I realize it's relatively minor enhancement that would require a lot of effort - so it's just a thought basically.

**Comment by wmjordan** [comment]
What I am thinking is how to make something different but more useful to programmers from what VS provides today by CodeLens.

**Comment by fitdev** [comment]
I agree! There is no point in simply duplicating existing VS features. But if NaviBar can provide an easier access to those features (like you did with drag-drop support for rearranging members), then it can make sense to extend its functionality.

**Comment by wmjordan** [comment]
Nevertheless, it is much less expensive to calculate number of lines a node takes and highlight those that span through N lines.

**Comment by wmjordan** [comment]
The recent versions has added an option to show number of lines for each member.
And the `Find Callers` command in the context menu serves the purpose of Number of references.
The implementation did not add info to the list, but what you need to know can be achieved without great efforts.

**Comment by wmjordan** [comment]
Someone has implemented a thing you may need:
https://marketplace.visualstudio.com/items?itemName=LuizFernandoDINATO.cicodelensinfo

**Comment by fitdev** [comment]
Thank you for letting me know about this. Seems like a nice extension, but very basic of course. I think the fact that you show some of that info (member kinds) in the NaviBar and Member Lists is more helpful than seeing it directly in code, where you already have a good idea of that.
