### ISSUE TITLE
Bugged after updated to 5.1

### ISSUE THREAD

**Issue by fantasyz** [wmjordan/Codist#86]
There are two issues I found in recent version. 

1. After updated to newest version, I found that the find filter (Ctrl+F) will not work correctly. Every time I type just one character, it lost focus to the text editor and I can't type a complete word to do a search. 

2. Using [Edit] -> [Go To] > [Go To File...]  or triggered by short-cut, when the target go-to file is on another split view window, the caret is not moving to the other view. This issue is happening for quite a long time but I just found that it is also caused by codist.

Both issue will not happen when Codist is disabled.

**Comment by fantasyz** [comment]
Just found another issue:

3. When typing caret is at a using statements in .cs file ( using System; ), pressing the shortcut key will not bring out the navi-bar.

**Comment by wmjordan** [comment]
Thank you for reporting 1 and 2. I will work on it.

Issue 3 is because there is no active "type" when your caret is on the `using` statement. Ctrl+1,Ctrl+1 only works when the caret is in a type.

**Comment by wmjordan** [comment]
Please try this new beta.
[Codist.zip](https://github.com/wmjordan/Codist/files/3245420/Codist.zip)

**Comment by fantasyz** [comment]
Just tried the zip version.  Seems working fine now.
Thank you!

**Comment by wmjordan** [comment]
Great!

Thank you for the bug report.
I am going to release the new version on the marketplace soon.
