### ISSUE TITLE
Make Symbol List Pinnable and Draggable

### ISSUE THREAD

**Issue by wmjordan** [wmjordan/Codist#87]
It is @fitdev's voice:

> Actually, just learnt that you can already have multiple instances of the Member List Control (I right-clicked one of the members in one, chose Find All Members, and it poped up a second Member List Control), so that's great! So, perhaps you can just make those draggable and pinnable as tool windows?

**Comment by wmjordan** [comment]
[Codist.zip](https://github.com/wmjordan/Codist/files/3261221/Codist.zip)

@fitdev, Please try this new beta.

**Comment by fitdev** [comment]
Thank you for prototyping this so quickly! Works quite well! The o only issue I have is with multiple monitors: you can drag it outside the text editor area (to another monitor for example), and it is no longer visible, so you can no longer interact with the control or close it. Perhaps make them visible all the time as long as they are pinned and VS is active?

**Comment by wmjordan** [comment]
The pinned symbol list is only visible within the main window of VS IDE.
If you drag it outside of the main window, it can not be bring back.
I will try to see how to prevent it from being drag out of the visible area.

**Comment by fitdev** [comment]
Is that a VS limitation? I frequently have code windows on other screens (outside of main VS window). I just tried to make it shown on the non-main code window, and it worked, - but once again it was restricted (in terms of visibility) to the window where it originated.

**Comment by wmjordan** [comment]
It is not an limitation.
It is the implementation.
I placed those symbol list as a control within the document editor window. Thus they become parts of the main window of VS. The good is that when you switch to another document, symbol lists in previous document window disappears automatically. The bad is that they can't go outside of the main window.

**Comment by wmjordan** [comment]
> you can drag it outside the text editor area

To implement this, the symbol list must be transferred to a tool window. That is how the similar command in CodeLens does.

**Comment by fitdev** [comment]
Oh I see! It makes sense now.

**Comment by wmjordan** [comment]
Nevertheless, it is reasonable to have a floating window for the symbol analyzer, which has been planned months ago but not implemented.
It was hard for me previously, but it does not seem so difficult now. The only drawback is that it takes a lot of work.

**Comment by fitdev** [comment]
Sure, I understand! As for me, I would rather want "Tab Groups" feature far more than this. So hopefully, you will be able to add that functionality sooner than floating window support.
