### ISSUE TITLE
Displaying XML Documentation for C# Namespaces

### ISSUE THREAD

**Issue by wmjordan** [wmjordan/Codist#88]
This request has been posted by various users previously.

Due to the limitation of C# compilers, there is no way to document a namespace.

The new version of Codist uses a custom `NamespaceDoc` type which serves as the placeholder for XML Doc of its containing namespace. The mechanism works the same way as _SandCastle_: http://ewsoftware.github.io/SHFB/html/48f5a893-acde-4e50-8c17-72b83d9c3f9d.htm.

**Comment by wmjordan** [comment]
@fitdev hey buddy, come test this new version
[Codist.zip](https://github.com/wmjordan/Codist/files/3292668/Codist.zip)

**Comment by fitdev** [comment]
Thank you for the new version! This implementation works great! Though, hopefully, in the future C# will start supporting namespace comments directly.

**Comment by wmjordan** [comment]
Good. I will close this issue now.
