### ISSUE TITLE
Quick Info Tooltip Improvement Suggestion

### ISSUE THREAD

**Issue by fitdev** [wmjordan/Codist#91]
I noticed that in code like `var a = new Foo();` when I hover my mouse over `new` and when I hover my mouse over `Foo()` I get the same tooltip with documentation for the _Foo's constructor_. I think it would be better to show documentation for the constructor _only when hovering over `new` keyword_, and show documentation for the type (class/struct) itself when hovering over its name.

**Off-Topic:**

It would be nice if you could make a sticky issue to track the small issues / suggestions to avoid creating a new issue for every minor detail. It's up to you of course, but perhaps one sticky issue per major version would work better for very small things.

**Comment by wmjordan** [comment]
Currently the Super Quick Info still preserve something from the one builtin VS.
It is not difficult to show up the content you suggested, however, it will not be corresponding to the first item (member signature) of the Quick Info.

Don't worry about too many trivia issues.
Other projects on GitHub are all that way.
Once they get fixed, they will be closed.

**Comment by fitdev** [comment]
My rationale for suggesting to change the default behavior in regards to tooltips for constructors is that:

- Because of the `new` keyword it is already obvious that the method is a constructor and creates a new instance.
- I would imagine one would rarely need to distinguish between different constructors by hovering over to read their doc. descriptions. This is because all the relevant arguments are also readily visible in code, so it is usually clear exactly what the method (constructor) will do.
- The type being instantiated, on the other hand, is not always so obvious - just by looking at its name. It could be something like `FooEx` or `AdvancedFoo` or some other ambiguous name, and it would help greatly to be able to see the doc. description for the type right there by just hovering over the type name.

**Comment by wmjordan** [comment]
Thanks for sharing your idea. It is very reasonable.
Frankly speaking, I had the same feeling while I was **fix**ing the mismatched XML Docs!

I'll keep an eye on it and think it twice.

**Comment by fitdev** [comment]
Thank you for considering! Glad to know you have similar opinion.

Also another small thing I just came across in regards to XML Docs is that the support for `class NamespaceDoc { }` you recently added works but only within the assembly where the `NamespaceDoc` class resides (it does not work across assemblies). Can this be supported across assemblies? Very often the same namespace exists across multiple assemblies.

**Comment by wmjordan** [comment]
> it does not work across assemblies

I could not reproduce this.
I compiled a project which utilized the `NamespaceDoc` trick and referenced it in another newly created project from a newly created solution, the tip still showed up.

**Comment by fitdev** [comment]
I think my problem is that I have not referenced the assembly containing the XML Doc from the project (assembly) where I was checking to see if the XML Doc comment will show up.

I have a separate Documentation project (assembly) where I store documentation-like stuff, including definitions of all namespaces that are used throughout various projects. This Documentation project is not referenced by anything since it's really just documentation.

The reasons for this setup are:
- I do not want `NamespaceDoc` classes in production/deployable code.
- I do not want to defined namespace docs in the most common assembly (used by all projects) either because that would mean it would contain all namespaces visible to the public, even if the only type they have is `NamespaceDoc`.

So, is it possible to perhaps look inside all solution's projects for `NamespaceDoc`s and simply use the first match that fully matches a given namespace name?

**Comment by wmjordan** [comment]
> is it possible to perhaps look inside all solution's projects for `NamespaceDoc`s and simply use the first match that fully matches a given namespace name?

It does not sound so good to me.

You can try to use [ILRepack](https://github.com/gluck/il-repack). I added an option to it which enabled you to drop those `NamespaceDoc` classes.

**Comment by wmjordan** [comment]
Maybe you can also use `#if DEBUG` to wrap around your `NamespaceDoc`s. Thus the documentation will be available when you edit and debug your project, and that class won't appear when you release the assembly.

**Comment by fitdev** [comment]
Thank you for your suggestions. I realize that looking across entire solution might not be feasible. I will try to come with a solution.

**Comment by wmjordan** [comment]
> The type being instantiated, on the other hand, is not always so obvious - just by looking at its name. It could be something like `FooEx` or `AdvancedFoo` or some other ambiguous name, and it would help greatly to be able to see the doc. description for the type right there by just hovering over the type name.

I agree.
And it seems that Roslyn "agrees" with you too.

When we hover the cursor on the type of a creation syntax, like `Exception` in `new Exception`, the syntax node we get is the type identifier, and hence we get the symbol of the type.
Previously in a "bugged" version, it behaved that way as you described.

However, VS's Quick Info does not behave like that. It displays the signature and XML doc for the constructor. I have got to ["fix" this by looking up the parent node of the identifier](https://github.com/wmjordan/Codist/blob/v5.0/Codist/QuickInfo/CSharpQuickInfo.cs#L177).

The most annoying and nasty part of WPF hacking aforementioned, unfortunately, lies here. When I override the XML doc in Quick Info, I have got to first remove the original doc. The code can get quite complicated, which [has already been somewhat complicated](https://github.com/wmjordan/Codist/blob/v5.0/Codist/QuickInfo/QuickInfoOverrider.cs#L236).

I really hate that.

**Comment by fitdev** [comment]
Wow, I did not realize that the process to add this useful information to QuickInfo tooltips is so painful. But your efforts do pay off in that your tooltips are way more useful and helpful than VS's default ones!

Perhaps you can reach to @madskristensen who, as far as I know, is now in charge of VS's extensibility, and explain the need for QuickInfo tooltip-related APIs.

**Comment by wmjordan** [comment]
Always keep in mind that we are not "adding", but "**replacing**" the information.
Addition is quite easy with existing API.
Replacement is another story. We have to identify and remove existing stuff at first. Failing to do so will result in 1) duplicated contents or 2) removed other contents accidentally.

I don't quite hold much hope that the API can get evolved too much. The API has been there for a long time. If it is going to change, it has to tag contents in the Quick Info and tell us where the information are generated by which component and what roles the information has. It can break existing extensions.

An alternative is to add some tags to those contents generated by VS, and let the hacking process a bit easier.

**Comment by wmjordan** [comment]
Thanks for mentioning Mads.
I don't have much hope that he will listen and change.

Codist at this moment is still an obscure extension.
Although about 1700 individual installation are there, but some people just have downloaded and uninstalled it.
Not so many extension authors are working with the Quick Info either.
If there are hundreds of thousands users, there may be another story.

**Comment by madskristensen** [comment]
@gundermanc is the editor API guru. He might be able to help

**Comment by gundermanc** [comment]
> The existing API has been there for a long time and does not been designed for content replacement.

There is a [new Quick Info API in VS 2017 15.6 and later](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.language.intellisense.iasyncquickinfosourceprovider?view=visualstudiosdk-2017) which is async and off the UI thread and replaces the version you are currently using.

Unfortunately, we don't currently have support for modifying existing quick info items in the new API. Existing extensions that do so are typically quite fragile and it made the back-compat story with the previous 3 generations of the API very difficult so I had to make the decision to drop that functionality from the new API.

> I don't quite hold much hope that the API can get evolved too much.

We absolutely take into account user feedback. The most effective way to get something done is for there to be a [feedback item](https://developercommunity.visualstudio.com) with votes. These are triaged directly by the team. This seems like a useful scenario for extenders and may be addressed if filed and voted up.

If we did implement this, I'd recommend that we move away from a WPF-driven API and instead to a tagging approach where each item has a well-known tag name associated with it and extensions can be made to drop all items with that tag name.

In the meantime, you may be able to accomplish some of what you're trying to do by overriding the default VS [view element factories](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.text.adornments.iviewelementfactory?view=visualstudiosdk-2017) for tool tip contents. If you implement a conversion from `ClassifiedTextElement` to `UIElement` and order before the default one with `[Order(Before ="default ClassifiedTextElement to UIElement")]`, your factory should be called first. From here, you can choose how to render into UIElements the spans of text Roslyn gives editor. [FSharp](https://github.com/dotnet/fsharp/blob/8ea71dd368401683fcbe895965c448c2688d3899/vsintegration/src/FSharp.Editor/QuickInfo/WpfNagivableTextRunViewElementFactory.fs) uses this same mechanism to render clickable links in the tooltip.

**Comment by wmjordan** [comment]
@gundermanc 
Thanks for your kind explanation. I have read Mads' article before and I am aware of the new API for Quick Info.
The problem is that the absence of API to drop some items in the Quick Info.

I'd posted a new thread to request the new APIs there:
https://developercommunity.visualstudio.com/idea/637495/new-api-to-replace-existing-items-in-quick-info.html

The tag-name-based approach maybe an easy to implement one. However, the tags are useless if no further manipulation is required and it may not be an mandatory practice by developers. It will be up to the C# team to determine whether adding tags to their Quick Info content or not.

Thanks for telling me about the `IViewElementFactory`. I will study that API and see whether it is possible to make the Quick Info hacking life a little bit easier.

**Comment by wmjordan** [comment]
After studying `IViewElementFactory`, I am afraid that it can not help easing the Quick Info hacking problem, because:
1. there is no way to tell from which place the object passed to `CreateViewElement` are populated.
2. the Quick Info override have to work with a **whole block** of Quick Info item rather than individual classified text element (making the text blocks word-wrapped, scrollable, selectable, copyable, etc).
![shot](https://user-images.githubusercontent.com/12182730/61356616-4dd11c00-a8a9-11e9-964c-e13c6cdba0ef.png)
You can see that the block of scrollable content ranges from the member signature, `summary` of the XML Doc, extensively added `remarks` and `exception` XML Doc.
Moreover, extra icons are inserted before every text blocks.

Since each Quick Info item comes from the result of `GetQuickInfoItemAsync` or the legacy `AugmentQuickInfoSession`, maybe it is possible to have an API to intercept the source and the generated items.

**Comment by fitdev** [comment]
Sorry to ask, but just wondering - any progress on replacing the default tooltip description text for constructors with actual XML Docs for the _type_ being instantiated (when hovering over type name)? 

I find it that every day, many, many times, I would need to read about what a particular type is used for by hovering over `Foo` in `new Foo()` and instead of type's description seeing only comment for the constructor, which is almost always something like "Creates a new instance of Foo" - something which is already obvious from the code.

**Comment by wmjordan** [comment]
Still in state **need help**.
No progress yet. Sorry.
Or... if we don't replace the comment, but showing the XML Doc for the type somewhere else, where to go?

**Comment by wmjordan** [comment]
An alternative approach is, however, quite difficult, that delete _**ALL**_ XML Doc content provided by VS in the quick info and recreate them from scratch. Could you help me to enumerate how many types of content can come out from the VS nowadays?
As far as I know, they include:
1. XML Doc
2. Exception XML Doc
3. Async usage
4. Type argument
5. Availability warning of a type or a member across various project configurations
6. Captured variables

**Comment by fitdev** [comment]
I did not realize it would require so much work. I think, the easier solution would be to

> if we don't replace the comment, but showing the XML Doc for the type somewhere else

Perhaps just below the constructor XML doc's text would be good?

**Comment by wmjordan** [comment]
> Perhaps just below the constructor XML doc's text

Maybe this can be the solution.

**Comment by wmjordan** [comment]
Please try the new beta.

**Comment by fitdev** [comment]
Thank you for the new beta. I do not seem to see any difference - moving mouse over `TypeNme` in `new TypeName()` does not show `TypeName`'s XML Doc.

**Comment by wmjordan** [comment]
There were some cases that the new beta did not work correctly, for instance, the `TypeName` was qualified by namespaces.
Please try the new one.

**Comment by fitdev** [comment]
This one seems to work great! Thanks so much for such a quick response!

**Comment by wmjordan** [comment]
I still want to totally override the XML Doc on Quick Info. Have you ever met with other quick info contents besides the 6 kinds listed above?

**Comment by fitdev** [comment]
Not really. I don't think I have seen other kinds of XML Docs. I suppose remarks section is included in item 1.

If you do go that route though, perhaps you can also include somewhere the sample usage section as well (whenever that is defined).

**Comment by wmjordan** [comment]
I missed the situation of the anonymous types.
There are up to 7 kinds of doc in the Quick Info.

**Comment by fitdev** [comment]
I see. I never really came across those, as I very rarely use Anonymous Types.

**Comment by wmjordan** [comment]
I have compiled a new version which overwritten the whole XML Doc when _Override XML Documentation_ is selected. Please test it and see whether there's anything wrong within it except the following items.

1. I don't think the "Awaitable usage" is useful thus it is absent in my implementation.
2. The "Generic type argument" is incomplete yet.

**Comment by fitdev** [comment]
I will test it and let you know if I encounter any issues.

I have not come across "Awaitable usage" myself, but I expect it may be quite important when doing async stuff. So, perhaps you can include it still in the final version?

And one more thing:

![2019-09-13 16_57_14-DotNet - Microsoft Visual Studio Preview](https://user-images.githubusercontent.com/8166847/64868388-ea186480-d647-11e9-8639-a9f48e34835e.jpg)

It would be really nice if the nested tooltips would be fully functional as well, just as the original (main tooltip). In the screenshot above I was hovering over "Version", and so a new smaller tooltip got displayed. However that smaller tooltip lacks XML Doc. So, perhaps you can extend these 2nd level tooltips and show more info there too.

**Comment by wmjordan** [comment]
1. The awaitable usage originally appears when you hover on a method returns awaitable result, typically, a `Task` or `Task<>`, with something like this.

   Usage:
   `await ReadAsync(...);`

   Almost every guy programming with the async & await pattern knows this. Thus I think it hardly useful.

2. Thanks for sharing your thoughts about the symbol tool tip.
Actually I have similar feeling about that. I will see whether it is possible to do so.

**Comment by fitdev** [comment]
Oh I see. In that case you are probably right - the async usage information is not useful then.

Just a tiny bug: `partial` keyword is no longer colored the same as other keywords in static classes: `static partial class Foo` - `static` and `class` are blue, but `partial` is black.

**Comment by wmjordan** [comment]
That's weird.

It is OK on my machine and I have not made any modification targeting the `partial` keyword.
![捕获](https://user-images.githubusercontent.com/12182730/64899226-01de0000-d6bd-11e9-93ee-b56fdba4ea3e.PNG)

**Comment by wmjordan** [comment]
> It would be really nice if the nested tooltips would be fully functional as well

Please try the new beta.

**Comment by fitdev** [comment]
Works really well! Thanks for implementing it so quickly! As for `partial` - I will keep an eye on it, perhaps it is something specific to my VS installation and will be ok after next VS upgrade.

**Comment by fitdev** [comment]
I noticed that right-clicking on a symbol name within XML Doc tooltip no longer shows menu with additional commands (like list members, find references, etc.).

**Comment by fitdev** [comment]
Also, I seem to be getting other syntax highlighting issues:

![2019-09-14 15_45_19-DotNet - Microsoft Visual Studio Preview](https://user-images.githubusercontent.com/8166847/64908302-e5ff4c00-d706-11e9-9f72-720b8a6f22c6.jpg)

This is just one example. I think I started getting this after I upgraded to 4952.

**Comment by wmjordan** [comment]
That's too weird.
Could you take the trouble of disabling some of your extensions and see whether the above problem reoccurs? If it still occurs, can you send me your configuration file of Codist and let me test with it?
