### ISSUE TITLE
Small syntax highlight bug with cast operator

### ISSUE THREAD

**Issue by fitdev** [wmjordan/Codist#96]
Using Codist 5.2, there seems to be a bug where casting to genertic type parameter is not colored properly:

![2019-07-03 09_33_25-DotNet - Microsoft Visual Studio Preview](https://user-images.githubusercontent.com/8166847/60568648-11b09e00-9d76-11e9-8a8a-5ab1b3dd74ca.jpg)

**Comment by wmjordan** [comment]
I could not reproduce this.
Could you post a piece of more complete code example?
![shot](https://user-images.githubusercontent.com/12182730/60573090-8f41d180-9da9-11e9-979b-9696170469a3.png)

**Comment by fitdev** [comment]
Inside a `static class`:

```csharp
    public static T ConvertTo<T>(this object it) {
      if (!(it is null)) {
        var targetType = typeof(T);

        if (it.GetType() == targetType) return (T)it;

        var converter = TypeDescriptor.GetConverter(it);
        if (converter != null && converter.CanConvertTo(targetType))
          return (T)converter.ConvertTo(it, targetType);

        converter = TypeDescriptor.GetConverter(targetType);
        if (converter != null && converter.CanConvertFrom(it.GetType()))
          return (T)converter.ConvertFrom(it);

        if (it == DBNull.Value) return (T)(object)null;
      }
      return (T)it;
    }
```

**Comment by wmjordan** [comment]
It is good here. Or, you may try this new beta.

![shot](https://user-images.githubusercontent.com/12182730/60574710-9fa77b80-9dac-11e9-9c4a-fdca2ae385d7.png)

[Codist.zip](https://github.com/wmjordan/Codist/files/3353871/Codist.zip)

**Comment by wmjordan** [comment]
It seems that you are not very well customize the color.
You need to specify a color for _Type Parameter Name_ in the syntax highlight options page.

**Comment by fitdev** [comment]
Well, I just did not customize it, since I am ok with the VS's default teal color. I am a bit surprised that you distinguish between casting to type parameter `(T)` - where `( )` are colored the same as `T` and between casting to any other type `(object)` where `( )` are always teal-colored. I am not sue if this is proper behavior, as it is somewhat misleading:

- Either always color all `( )` casting operators the same, or 
- Have at least 3 cases:

1. `(TType)` - casting to type parameter, `( )` colored the same as type parameter.
2. `(int)` - casting to language types - colored the same way as the type (typically blue)
3. `(Foo)` - non-language types - colored the same way as the type (typically teal)
4. If there are other type-cases, then the same logic would apply.

The first option would be easier to implement, but aesthetically, I prefer the second option. But the problem is now, I guess, it is neither of the 2 which is a bit confusing.

**Comment by wmjordan** [comment]
I don't think the colorization is miss leading.
The parentheses for cast expression are always colorized as the type within it.

1. It uses the color for value type names when the type within it is a value type;
2. It uses the color for ref type names when the type within it is a ref type;
3. It uses the color for type argument names when the type within it is a type argument.

**Comment by wmjordan** [comment]
The question is the situation 3 above.

Shall we try to check out the type constraint of the generic type argument to colorize the parentheses around it to reflect that?

**Comment by fitdev** [comment]
I don't think there is a need to go that far, as it is a lot of extra work for you for a very minor feature and may still end up confusing for the user.

I didn't know about the 3 cases you outlined in a previous post. They do make sense, except that you offer more type customizations than that: Class, Struct, Interface, Enum, Type Parameter. So, for completeness, I guess, if you go by 

> The parentheses for cast expression are always colorized as the type within it.

...you should probably have the above 5 cases and not 3. Personally, however, I would be happy with just one distinct case - i.e. should be colored the same as an operator.

If you do want to keep it as it is (which is fine), or then extend it to 5 cases (by adding Enums and Interfaces) as I proposed here, then I strongly think you should consider my other proposal in #93 regarding coloring of `?`, `[]`, `( , )` (tuples) and possibly even `<>` when those are effectively used as type names / descriptors. I mean if the casting operator is colored the same as the type, shouldn't the other type-related punctuation (they are not really even operators) be also colored the same as type?

**Comment by wmjordan** [comment]
> As far as simplicity and consistency goes, personally I would be ok with just one distinct case - i.e. should be colored the same as an operator.

Good point. For instance, the following parentheses can be classified as type cast operators.

````C#
var a = (int)o;
var b = (s as string).Length;
````

**Comment by fitdev** [comment]
Not sure about the second one - don;t really have a strong opinion here. To me the second cases looks more as a grouping, and so should probably colored as normal text (or whatever is the default for general, grouping parenthesis).

**Comment by fitdev** [comment]
Perhaps I was not very clear above... I do like that you currently have 3 cases for the cast operator, depending on the kind of type. I just think that for completeness and to avoid confusion it would be better to extend it to more cases as I described, or perhaps (which may be easier to implement for you - you know best) to simply have an option - always color cast operator the same way as the type (whatever it is - including Font, Size, Color).

In fact, if you could apply the same option for type-related punctuation, that would be great. That is - you can leave it as it is, but if the option is toggled, then all the `int?`, `int[]`, `(int, bool)`, `int*`, `Foo<int>` would be colored the same way as underlying type (though tuples and generic can be tricky since they can have more than one underlying type, so perhaps leave them out for now).

But basically consider a code like:

```csharp
var chars = (char*)buffer;
```

To me, it really makes sense to think of `(char*)` as one thing, because `*` is a type "modifier", and casting `( )` is about casting to that whole type.

**Comment by wmjordan** [comment]
There is a beta which highlights parentheses surrounding type parameters taking consideration of type constraints.
[Codist.zip](https://github.com/wmjordan/Codist/files/3364311/Codist.zip)

**Comment by wmjordan** [comment]
The highlight must be turned on by selecting "type cast parentheses".

**Comment by fitdev** [comment]
I am surprised you decided to take that route, as it probably requires more processing to determine that info on generic type, and more work for you. I think for me, it would be more useful if the same logic would apply to the actual generic type name as well - and be colored differently depending on whether it's enum, value type, or a class.

**Comment by wmjordan** [comment]
I tried to apply the same trick against the type parameter.
Unfortunately, due to the mysterious precedence of syntax highlighting, the type parameters are reluctant to change according to the type constraints.

**Comment by wmjordan** [comment]
I am also afraid event if highlighting type parameter regarding type constraints can be implemented, it is less efficient than the current implementation, which is able to immediately mark type parameters with a different color and help programmers to find out where the type parameters are used in a glance.

Thus I won't try any more to apply that logic to type parameters.

**Comment by fitdev** [comment]
That makes sense. I also feel that having a distinct syntax highlighting for type parameters is already enough.

**Comment by wmjordan** [comment]
Hi,

I tried to make another way of highlighting type casting parentheses--all of them are highlighted the same as type related keywords (like `as`, `is`, `in`, `out` and `ref`).
![shot](https://user-images.githubusercontent.com/12182730/80055341-04a6aa80-8554-11ea-919b-a5485dd15d20.PNG)

How do you think about that?

**Comment by fitdev** [comment]
Yes, that makes sense too! I just have not defined a separate style for the type-related keywords, but I may want to try it now that you mentioned it.

**Comment by wmjordan** [comment]
Thank you for commenting.
Please download the latest beta and test it.
