### ISSUE TITLE
unexpected region name show up in NaviBar

### ISSUE THREAD

**Issue by fantasyz** [wmjordan/Codist#97]
![Codist Error](https://user-images.githubusercontent.com/3223242/61180460-35fb5d00-a649-11e9-8666-a909baaff06e.jpg)

As the screenshot shows, the 2nd region INSIDE the function OnEvent() is listed in the NaviBar dropdown.

**Comment by fantasyz** [comment]
note: 
Inside OnEvent(), the 1st region only encapsulate simple case break statements while the 2nd region contains {} brackets. I think this maybe the reason why the 2nd region is showing up in the NaviBar dropdown. Ideally, I would prefer any region to be hidden when placed inside a function.

**Comment by wmjordan** [comment]
Thank you for posting that.
I will see whether it is possible to implement your suggestion.

**Comment by wmjordan** [comment]
[Codist.zip](https://github.com/wmjordan/Codist/files/3394776/Codist.zip)

Please try this new beta.
It by default hides regions within type members as you suggested. Yet it is possible to enable that in the options page.
