### ISSUE TITLE
Ability to change Navigation Bar colours

### ISSUE THREAD

**Issue by MrClyfar** [wmjordan/Codist#98]
Is there an option to change the colours used in the Navigation Bar?

I use a Solarized Light theme in Visual Studio, and the problem I have is this...

![image](https://user-images.githubusercontent.com/700064/61617936-a9adf300-ac63-11e9-80c9-517a619691c0.png)

The function name at the end of the bar is highlighted in a blue shade, which makes the text very hard to read. Can the colour be changed?

**Comment by wmjordan** [comment]
Thank you for reporting this. It is really ugly. I will take a look into it.

**Comment by wmjordan** [comment]
Please try this new beta which addresses this issue.

[Codist.zip](https://github.com/wmjordan/Codist/files/3419712/Codist.zip)

**Comment by MrClyfar** [comment]
Thank you so much for the quick response.

As I cannot download files from GitHub at work (thanks to security, boo! :) I will have to wait until I get home later today to try this out for you.

**Comment by wmjordan** [comment]
OK.
Please take a bigger screenshot of your VS and let me see how it looks.

**Comment by MrClyfar** [comment]
I've just tried the Codist extension from that zip file you linked. The text looks much better...

![2019-07-23 20_21_31-UnitTestProject1 - Microsoft Visual Studio Preview](https://user-images.githubusercontent.com/700064/61740836-841a0a00-ad87-11e9-926b-2ed26e61e516.png)

Thanks for fixing this issue so quickly.

**Comment by wmjordan** [comment]
That's great.
